'use strict';
const $=id=>document.getElementById(id);
const $$=sel=>[...document.querySelectorAll(sel)];
const pick=a=>a[Math.floor(Math.random()*a.length)];
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const norm=s=>(s||'').trim().toLowerCase().replace(/[أإآ]/g,'ا').replace(/ة/g,'ه').replace(/ى/g,'ي').replace(/\s+/g,' ');
let activeTimer=null, wakeLock=null;

const GAME_DEFS=[
  {id:'trivia',emoji:'🏆',name:'تحدّي 30',desc:'باكات + صعوبة + جولات مختلفة',players:'2–10',time:'20–90 د'},
  {id:'player',emoji:'⚽',name:'مين اللاعب؟',desc:'ارفع الهاتف وخمّن اللاعب',players:'2–10',time:'5–20 د'},
  {id:'fake',emoji:'🕵️',name:'الجواب المزوّر',desc:'جواب قريب وغلط عند شخص واحد',players:'3–10',time:'10–30 د'},
  {id:'sync',emoji:'🧠',name:'نفس التفكير',desc:'اكتب بسرية وطابق أصحابك',players:'3–10',time:'10–25 د'},
  {id:'scale',emoji:'🎯',name:'على المقياس',desc:'تلميح واحد ورقم سري',players:'3–10',time:'10–25 د'},
  {id:'taboo',emoji:'🚫',name:'احكيها بدونها',desc:'وصف سريع بدون كلمات ممنوعة',players:'4–10',time:'15–40 د'},
  {id:'draw',emoji:'🎨',name:'ارسم ومرّر',desc:'رسم → تخمين → رسم',players:'3–10',time:'15–35 د'},
  {id:'bowl',emoji:'🥣',name:'وعاء الكلمات',desc:'وصف → كلمة واحدة → تمثيل',players:'4–10',time:'25–50 د'},
  {id:'bomb',emoji:'💣',name:'القنبلة',desc:'جاوب ومرّر قبل الانفجار',players:'3–10',time:'10–25 د'}
];

const HELP={
trivia:{title:'🏆 تحدّي 30',players:'2–10 • الأفضل فريقين',goal:'أول فريق يصل للنقاط المستهدفة يفوز.',steps:['اختار الفرق والصعوبة والباقات.','اختار أنواع الجولات: سؤال مباشر، من أنا، أو عدّد/مزايدة.','الحكم يقرأ السؤال ويكشف الجواب وقت الحاجة.','اضغط نقطة للفريق الذي نجح، والتطبيق يمنع تكرار الأسئلة خلال السهرة.'],tip:'خلطة 3–5 باكات أفضل لسهرة طويلة.'},
player:{title:'⚽ مين اللاعب؟',players:'2–10',goal:'صاحب الدور يعرف اللاعب الذي يراه الآخرون.',steps:['اختار باكات اللاعبين والصعوبة.','مرّر الهاتف لصاحب الدور من غير ما يشوف الشاشة.','يرفع الهاتف أمام المجموعة ويسأل فقط أسئلة نعم/لا.','إذا عرف اللاعب اضغط «عرفه» وانتقل لبطاقة جديدة.'],tip:'للمحنكين: فعّل باك الأساطير وارفع الصعوبة.'},
fake:{title:'🕵️ الجواب المزوّر',players:'3–10',goal:'اكتشفوا من معه الإجابة المزورة قبل أن يندمج معكم.',steps:['كل لاعب يستلم الهاتف سرًا ويرى سؤالًا وإجابته.','الجميع تقريبًا يرى الإجابة الحقيقية، وشخص واحد يرى إجابة قريبة وغلط.','كل لاعب يعطي تلميحًا بدون قول الإجابة حرفيًا.','صوّتوا سرًا على من تعتقدون أنه المزوّر ثم اكشفوا النتيجة.'],tip:'المزوّر نفسه لا يُخبر أنه المزوّر؛ وهذا يزيد الشك.'},
sync:{title:'🧠 نفس التفكير',players:'3–10',goal:'اكتب نفس جواب شخص آخر من غير اتفاق.',steps:['تظهر عبارة مثل «أكلة بالليل».','يمر الهاتف على الجميع وكل واحد يكتب جوابه بسرية.','في الكشف، التطابق مع شخص واحد بالضبط يعطي 3 نقاط لكل واحد؛ تطابق 3+ يعطي نقطة.','بعد عدة جولات يظهر صاحب أعلى مجموع.'],tip:'لا تكتب جوابًا غريبًا جدًا ولا جوابًا واضحًا جدًا.'},
scale:{title:'🎯 على المقياس',players:'3–10',goal:'فهم مكان الرقم السري من تلميح قائد الجولة.',steps:['القائد يرى مقياسًا مثل «رخيص ↔ غالي» ورقمًا سريًا من 0–100.','يعطي مثالًا أو كلمة تناسب المكان من غير ذكر الرقم.','المجموعة تحرك المؤشر حيث تتوقع.','كلما اقترب التخمين من الرقم، زادت النقاط.'],tip:'التلميح الجيد ليس واضحًا جدًا ولا غامضًا جدًا.'},
taboo:{title:'🚫 احكيها بدونها',players:'4–10 • فريقان',goal:'اشرح أكبر عدد من الكلمات قبل انتهاء الوقت.',steps:['صاحب الدور يرى الكلمة وأربع كلمات ممنوعة.','يشرح لفريقه بدون نطق أي كلمة ممنوعة.','صح = نقطة، تخطي حسب الإعداد، ومخالفة تخصم نقطة.','بعد انتهاء الوقت ينتقل الدور للفريق الثاني.'],tip:'السرعة أهم من شرح مثالي.'},
draw:{title:'🎨 ارسم ومرّر',players:'3–10',goal:'شاهدوا كيف تتحول الكلمة خلال سلسلة رسم وتخمين.',steps:['أول لاعب يرى كلمة ويرسمها.','الثاني يرى الرسم فقط ويكتب تخمينه.','الثالث يرى التخمين فقط ويرسمه.','استمروا حتى نهاية السلسلة ثم اكشفوا كل المراحل.'],tip:'ممنوع كتابة حروف أو أرقام داخل الرسم.'},
bowl:{title:'🥣 وعاء الكلمات',players:'4–10 • فريقان',goal:'اجمع أكبر عدد من الكلمات عبر ثلاث جولات بنفس البطاقات.',steps:['الجولة 1: اشرح بحرية من غير قول الكلمة.','الجولة 2: مسموح كلمة واحدة فقط كتلميح.','الجولة 3: تمثيل فقط، بدون كلام.','نفس الكلمات تعود في كل جولة، لذلك الذاكرة مهمة.'],tip:'هذه من أقوى الألعاب لسهرة طويلة لأنها تتصاعد طبيعيًا.'},
bomb:{title:'💣 القنبلة',players:'3–10',goal:'لا تكن ماسك الهاتف عندما ينتهي المؤقت السري.',steps:['تظهر فئة مثل «اذكر دولة عربية».','صاحب الهاتف يقول جوابًا مناسبًا غير مكرر ثم يضغط «مرّر».','ينتقل الهاتف للاعب التالي بسرعة.','المؤقت سري وعشوائي؛ من تنفجر عنده القنبلة يأخذ ضربة.'],tip:'لا تكرر جوابًا قيل في نفس الجولة.'}
};

const defaultSession=()=>({id:Date.now(),startedAt:Date.now(),rounds:0,games:{},used:{},scores:{},events:[],strikes:{}});
const state={
  names:JSON.parse(localStorage.getItem('pn.names')||'[]'),
  settings:{sound:true,haptics:true,wake:true,...JSON.parse(localStorage.getItem('pn.settings')||'{}')},
  session:JSON.parse(localStorage.getItem('pn.session')||'null')||defaultSession()
};
function persist(){localStorage.setItem('pn.names',JSON.stringify(state.names));localStorage.setItem('pn.settings',JSON.stringify(state.settings));localStorage.setItem('pn.session',JSON.stringify(state.session));renderHomeStats()}
function sessionUse(bucket,id){if(!state.session.used[bucket])state.session.used[bucket]=[];if(state.session.used[bucket].includes(id))return false;state.session.used[bucket].push(id);return true}
function uniquePick(bucket,list){if(!list.length)return null;let unused=list.filter(x=>!state.session.used[bucket]?.includes(x.id));if(!unused.length){state.session.used[bucket]=[];unused=list}const item=pick(unused);sessionUse(bucket,item.id);return item}
function record(game,detail={}){state.session.rounds++;state.session.games[game]=(state.session.games[game]||0)+1;state.session.events.push({t:Date.now(),game,...detail});if(state.session.events.length>120)state.session.events.shift();persist()}
function addScore(name,pts=1){if(!name)return;state.session.scores[name]=(state.session.scores[name]||0)+pts;persist()}
function addStrike(name){state.session.strikes[name]=(state.session.strikes[name]||0)+1;persist()}

function toast(msg){const e=$('toast');e.textContent=msg;e.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>e.classList.remove('show'),1800)}
function buzz(ms=35){if(state.settings.haptics&&navigator.vibrate)navigator.vibrate(ms)}
function beep(freq=650,dur=.07){if(!state.settings.sound)return;try{const C=window.AudioContext||window.webkitAudioContext;const c=beep.ctx||(beep.ctx=new C());const o=c.createOscillator(),g=c.createGain();o.frequency.value=freq;g.gain.value=.04;o.connect(g);g.connect(c.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,c.currentTime+dur);o.stop(c.currentTime+dur)}catch{}}
function closeTimer(){if(activeTimer){clearInterval(activeTimer);clearTimeout(activeTimer);activeTimer=null}}
function countdown(el,seconds,onEnd,progressEl){closeTimer();let left=seconds;el.textContent=left;if(progressEl)progressEl.style.width='100%';activeTimer=setInterval(()=>{left--;el.textContent=left;if(progressEl)progressEl.style.width=`${Math.max(0,left/seconds*100)}%`;if(left<=0){closeTimer();beep(220,.25);buzz([80,50,120]);onEnd?.()}},1000)}
function showScreen(id){closeTimer();$$('.screen').forEach(s=>s.classList.remove('active'));$(id).classList.add('active');window.scrollTo({top:0,behavior:'instant'});state.session.games[id]=(state.session.games[id]||0);persist();maybeWake()}
function home(){showScreen('home')}
function closeModal(id){$(id).classList.remove('open')}
function help(id){const h=HELP[id];$('helpTitle').textContent=h.title;$('helpBody').innerHTML=`<div class="chips"><span class="pill">👥 ${h.players}</span></div><p><b>الهدف:</b> ${h.goal}</p><div class="helpSteps">${h.steps.map((s,i)=>`<div class="helpStep"><b>${i+1}</b><span>${s}</span></div>`).join('')}</div><p class="muted">💡 ${h.tip}</p>`;$('helpModal').classList.add('open')}

function saveNames(){state.names=$('names').value.split(/[،,\n]/).map(x=>x.trim()).filter(Boolean).slice(0,10);persist();renderNames();toast(`تم حفظ ${state.names.length} لاعبين`)}
function renderNames(){$('names').value=state.names.join('، ');$('nameChips').innerHTML=state.names.map(n=>`<span class="chip">👤 ${n}</span>`).join('')||'<span class="tiny">أضف أسماء اللاعبين عشان نفعّل النقاط الفردية.</span>';renderHomeStats()}
function shufflePlayers(){state.names=shuffle(state.names);persist();renderNames();toast('تم خلط الترتيب')}
function requirePlayers(n=2){if(state.names.length<n){toast(`أضف ${n} لاعبين على الأقل من الرئيسية`);home();return false}return true}
function newNight(){if(!confirm('نبدأ سهرة جديدة؟ سيتم تصفير إحصائيات السهرة ومنع التكرار.'))return;state.session=defaultSession();persist();toast('✨ سهرة جديدة!')}
function quickMix(){const playable=GAME_DEFS.filter(g=>state.names.length>=parseInt(g.players));const g=pick(playable.length?playable:GAME_DEFS);toast(`🎲 ${g.name}`);setTimeout(()=>showScreen(g.id),350)}
function renderHomeStats(){$('homePlayers').textContent=state.names.length;$('homeRounds').textContent=state.session.rounds;$('homeGames').textContent=Object.values(state.session.games).filter(x=>x>0).length}
function showSession(){const scores=Object.entries(state.session.scores).sort((a,b)=>b[1]-a[1]);const games=Object.entries(state.session.games).filter(x=>x[1]>0).sort((a,b)=>b[1]-a[1]);const mins=Math.max(1,Math.round((Date.now()-state.session.startedAt)/60000));$('sessionBody').innerHTML=`<div class="statGrid"><div class="statBox"><b>${state.session.rounds}</b>جولات</div><div class="statBox"><b>${games.length}</b>ألعاب</div><div class="statBox"><b>${mins}</b>دقيقة</div></div><h3>🏅 الترتيب الفردي</h3><div class="leaderboard">${scores.length?scores.map(([n,s],i)=>`<div><span>${i===0?'🥇':i===1?'🥈':i===2?'🥉':''} ${n}</span><b>${s}</b></div>`).join(''):'<div class="muted">لسا ما في نقاط فردية.</div>'}</div><h3>🎮 الأكثر لعبًا</h3><div class="leaderboard">${games.length?games.map(([g,c])=>`<div><span>${GAME_DEFS.find(x=>x.id===g)?.name||g}</span><b>${c}</b></div>`).join(''):'<div class="muted">ابدأوا أول لعبة 😄</div>'}</div><div class="actions"><button class="danger" onclick="newNight();closeModal('sessionModal')">سهرة جديدة</button></div>`;$('sessionModal').classList.add('open')}
function showSettings(){$('settingsBody').innerHTML=`<div class="helpSteps"><label class="helpStep"><span>🔊 أصوات</span><input type="checkbox" ${state.settings.sound?'checked':''} onchange="setSetting('sound',this.checked)"></label><label class="helpStep"><span>📳 اهتزاز (إذا مدعوم)</span><input type="checkbox" ${state.settings.haptics?'checked':''} onchange="setSetting('haptics',this.checked)"></label><label class="helpStep"><span>☀️ إبقاء الشاشة مستيقظة</span><input type="checkbox" ${state.settings.wake?'checked':''} onchange="setSetting('wake',this.checked)"></label></div><p class="muted">اللعبة تحفظ الأسماء والإحصائيات محليًا وتعمل أوفلاين بعد أول تحميل.</p>`;$('settingsModal').classList.add('open')}
function setSetting(k,v){state.settings[k]=v;persist();if(k==='wake')maybeWake()}
async function maybeWake(){if(!state.settings.wake||!('wakeLock'in navigator))return;try{if(!wakeLock)wakeLock=await navigator.wakeLock.request('screen')}catch{}}
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){wakeLock=null;maybeWake()}});

function renderGameGrid(){$('gameGrid').innerHTML=GAME_DEFS.map(g=>`<article class="gameCard"><div class="emoji">${g.emoji}</div><h3>${g.name}</h3><p>${g.desc}</p><div class="gameMeta"><span>👥 ${g.players}</span><span>⏱ ${g.time}</span></div><div class="cardButtons"><button class="play" onclick="showScreen('${g.id}')">ابدأ</button><button class="info" onclick="help('${g.id}')">؟ شرح</button></div></article>`).join('');const count=PARTY_CONTENT.trivia.length+PARTY_CONTENT.players.length+PARTY_CONTENT.fake.length+PARTY_CONTENT.sync.length+PARTY_CONTENT.scale.length+PARTY_CONTENT.taboo.length+PARTY_CONTENT.draw.length+PARTY_CONTENT.bomb.length;$('contentCount').textContent=`${count}+ بطاقة ومهمة`}
function packButton(p,group,selected=true){return `<button class="packBtn ${selected?'selected':''}" data-pack="${p.id}" onclick="this.classList.toggle('selected')"><b>${p.emoji} ${p.name}</b><small>${p.desc||''}</small></button>`}
function selectedPacks(container){return $$(`#${container} .packBtn.selected`).map(x=>x.dataset.pack)}
function uniqueVals(arr,key){return [...new Set(arr.map(x=>x[key]).filter(Boolean))]}

let triviaState={a:0,b:0,current:null,bid:3,revealed:false};
function initTriviaSetup(){ $('triviaPacks').innerHTML=PARTY_CONTENT.triviaPacks.map(p=>packButton(p,'trivia',p.id==='football-general'||p.id==='ucl'||p.id==='general')).join('');const modes=[['direct','❓ مباشر'],['clues','🧩 من أنا؟'],['list','📣 عدّد/مزايدة']];$('triviaModes').innerHTML=modes.map(([id,n])=>`<span class="chip selectable selected" data-mode="${id}" onclick="this.classList.toggle('selected')">${n}</span>`).join('') }
function toggleAllTriviaPacks(){const b=$$('#triviaPacks .packBtn');const all=b.every(x=>x.classList.contains('selected'));b.forEach(x=>x.classList.toggle('selected',!all))}
function startTrivia(){let packs=selectedPacks('triviaPacks');if(!packs.length){toast('اختار باك واحد على الأقل');return}const modes=$$('#triviaModes .selected').map(x=>x.dataset.mode);if(!modes.length){toast('اختار نوع جولة');return}triviaState={a:0,b:0,current:null,bid:3,revealed:false,packs,modes,diff:$('triviaDifficulty').value,target:+$('triviaTarget').value,round:0};$('taName').textContent=$('teamA').value;$('tbName').textContent=$('teamB').value;$('taScore').textContent=0;$('tbScore').textContent=0;$('triviaSetup').classList.add('hidden');$('triviaPlay').classList.remove('hidden');nextTrivia()}
function nextTrivia(){const pool=PARTY_CONTENT.trivia.filter(q=>triviaState.packs.includes(q.pack)&&triviaState.modes.includes(q.type)&&(triviaState.diff==='all'||q.difficulty===triviaState.diff));if(!pool.length){toast('ما في أسئلة بهالفلتر — وسّع الاختيارات');return}const q=uniquePick('trivia',pool);triviaState.current=q;triviaState.round++;triviaState.revealed=false;triviaState.bid=q.min||3;$('triviaRoundLabel').textContent=`جولة ${triviaState.round}`;$('triviaPack').textContent=PARTY_CONTENT.triviaPacks.find(p=>p.id===q.pack)?.name||q.pack;$('triviaDiff').textContent={easy:'سهل',medium:'متوسط',hard:'صعب',expert:'محنكين'}[q.difficulty]||q.difficulty;$('triviaMode').textContent={direct:'مباشر',clues:'من أنا؟',list:'عدّد'}[q.type];$('triviaQ').textContent=q.q;$('triviaA').classList.add('hidden');$('triviaA').innerHTML=Array.isArray(q.a)?q.a.join(' • '):q.a;$('triviaHints').innerHTML='';$('triviaBidBox').classList.toggle('hidden',q.type!=='list');$('triviaBid').textContent=triviaState.bid;if(q.type==='clues'){(q.hints||[]).forEach((h,i)=>{const b=document.createElement('button');b.className='ghost wide';b.textContent=`كشف التلميح ${i+1}`;b.onclick=()=>{b.outerHTML=`<div class="hint">${i+1}. ${h}</div>`};$('triviaHints').appendChild(b)})}record('trivia',{pack:q.pack,type:q.type})}
function changeBid(n){triviaState.bid=clamp(triviaState.bid+n,1,12);$('triviaBid').textContent=triviaState.bid}
function toggleTriviaAnswer(){$('triviaA').classList.toggle('hidden');triviaState.revealed=true;beep()}
function awardTrivia(team){const pts=triviaState.current?.type==='list'?Math.max(1,Math.ceil(triviaState.bid/3)):1;triviaState[team]+=pts;$(team==='a'?'taScore':'tbScore').textContent=triviaState[team];beep(800);buzz();const teamName=$(team==='a'?'teamA':'teamB').value;addScore(teamName,pts);if(triviaState[team]>=triviaState.target){setTimeout(()=>{alert(`🏆 ${teamName} فاز!`);triviaState[team]=0},100)}else nextTrivia()}

let playerCurrent=null,playerTimerActive=false,playerTurnIdx=0,playerTurnName='';
function initPlayerPacks(){$('playerPacks').innerHTML=PARTY_CONTENT.playerPacks.map(p=>packButton(p,'player',p.id==='modern'||p.id==='legends')).join('')}
function newPlayerCard(){const packs=selectedPacks('playerPacks');if(!packs.length){toast('اختار باك');return}const level=$('playerLevel').value;const pool=PARTY_CONTENT.players.filter(p=>p.packs.some(x=>packs.includes(x))&&(level==='all'||p.difficulty===level));playerCurrent=uniquePick('players',pool);if(!playerCurrent){toast('ما في لاعبين بالفلتر');return}playerTurnName=state.names.length?state.names[playerTurnIdx++%state.names.length]:'صاحب الدور';$('playerCard').classList.add('hidden');$('playerPass').classList.remove('hidden');$('playerPass').querySelector('.big').textContent=`مرّر الهاتف لـ ${playerTurnName}`;$('playerImg').removeAttribute('src');record('player',{pack:playerCurrent.packs[0]})}
function showPlayerCard(){$('playerPass').classList.add('hidden');$('playerCard').classList.remove('hidden');$('playerName').textContent=playerCurrent.name;$('playerDifficulty').textContent={easy:'سهل',medium:'متوسط',hard:'صعب'}[playerCurrent.difficulty];$('playerPack').textContent=(PARTY_CONTENT.playerPacks.find(p=>playerCurrent.packs.includes(p.id))||{}).name||'';loadPlayerImage(playerCurrent.en);const sec=+$('playerTime').value;if(sec){$('playerTimer').classList.remove('hidden');countdown($('playerTimer'),sec,()=>toast('⏱ انتهى الوقت'))}else $('playerTimer').classList.add('hidden')}
async function loadPlayerImage(en){const img=$('playerImg');img.style.opacity=.35;try{const r=await fetch(`https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(en)}`);const j=await r.json();if(j.thumbnail?.source)img.src=j.thumbnail.source;else throw 0;img.onload=()=>img.style.opacity=1}catch{img.removeAttribute('src');img.alt=playerCurrent.name;img.style.opacity=1}}
function playerSolved(){if(playerTurnName&&playerTurnName!=='صاحب الدور')addScore(playerTurnName,1);beep(900);toast(`✅ نقطة لـ ${playerTurnName}`);newPlayerCard()}

let fakeState={};
function initFake(){uniqueVals(PARTY_CONTENT.fake,'pack').forEach(p=>$('fakePack').insertAdjacentHTML('beforeend',`<option>${p}</option>`))}
function startFake(){if(!requirePlayers(3))return;const packv=$('fakePack').value;const pool=PARTY_CONTENT.fake.filter(x=>packv==='all'||x.pack===packv);const card=uniquePick('fake',pool),order=shuffle(state.names),faker=pick(order);fakeState={card,order,faker,idx:0,votes:{}};$('fakeReveal').classList.add('hidden');$('fakeDebate').classList.add('hidden');$('fakeVote').classList.add('hidden');$('fakePass').classList.remove('hidden');renderFakePass();record('fake',{pack:card.pack})}
function renderFakePass(){const name=fakeState.order[fakeState.idx];$('fakePass').innerHTML=`<div class="handoffIcon">🔒</div><div class="big">أعطِ الهاتف لـ ${name}</div><div class="muted">خلي الكل يبعد نظره</div><button class="primary" onclick="revealFakeForPlayer()">أنا ${name} — اكشف</button>`}
function revealFakeForPlayer(){const name=fakeState.order[fakeState.idx],ans=name===fakeState.faker?fakeState.card.fake:fakeState.card.truth;$('fakePass').innerHTML=`<div class="pill">${fakeState.card.pack}</div><div class="question">${fakeState.card.q}</div><div class="answer">إجابتك: ${ans}</div><button class="primary" onclick="hideFakeAndNext()">حفظت — خبّي الشاشة</button>`}
function hideFakeAndNext(){fakeState.idx++;if(fakeState.idx<fakeState.order.length){renderFakePass()}else{$('fakePass').classList.add('hidden');$('fakeDebate').classList.remove('hidden');$('fakePrompt').textContent=fakeState.card.q;countdown($('fakeTimer'),+$('fakeTime').value,()=>startFakeVoting())}}
function startFakeVoting(){closeTimer();fakeState.voteIdx=0;$('fakeDebate').classList.add('hidden');$('fakeVote').classList.remove('hidden');renderFakeVote()}
function renderFakeVote(){if(fakeState.voteIdx>=fakeState.order.length){finishFakeVote();return}const voter=fakeState.order[fakeState.voteIdx];$('fakeVote').innerHTML=`<div class="handoffIcon">🗳️</div><div class="big">دور ${voter}</div><div class="muted">اختار سرًا من تعتقد معه الجواب المزوّر</div><div class="packGrid">${state.names.filter(n=>n!==voter).map(n=>`<button class="packBtn" onclick="castFakeVote('${escapeJs(n)}')"><b>${n}</b></button>`).join('')}</div>`}
function castFakeVote(name){const voter=fakeState.order[fakeState.voteIdx];fakeState.votes[voter]=name;fakeState.voteIdx++;buzz();renderFakeVote()}
function finishFakeVote(){$('fakeVote').classList.add('hidden');$('fakeReveal').classList.remove('hidden');$('fakeTrue').textContent=fakeState.card.truth;$('fakeFalse').textContent=fakeState.card.fake;$('fakerName').textContent=`🕵️ المزوّر: ${fakeState.faker}`;const counts={};Object.values(fakeState.votes).forEach(n=>counts[n]=(counts[n]||0)+1);$('fakeVoteResults').innerHTML=Object.entries(counts).sort((a,b)=>b[1]-a[1]).map(([n,c])=>`<div class="resultItem"><span>${n}</span><b>${c} أصوات</b></div>`).join('');let caught=0;Object.entries(fakeState.votes).forEach(([v,n])=>{if(n===fakeState.faker){addScore(v,1);caught++}});if(caught<Math.ceil(state.names.length/2))addScore(fakeState.faker,2);beep(caught>=Math.ceil(state.names.length/2)?850:300,.16)}
function escapeJs(s){return s.replace(/\\/g,'\\\\').replace(/'/g,"\\'")}

let syncState={};
function initSync(){uniqueVals(PARTY_CONTENT.sync,'pack').filter(x=>x!=='خلطة').forEach(p=>$('syncPack').insertAdjacentHTML('beforeend',`<option>${p}</option>`))}
function startSyncMatch(){if(!requirePlayers(3))return;syncState={round:0,max:+$('syncRounds').value,pack:$('syncPack').value};nextSyncRound()}
function nextSyncRound(){if(syncState.round>=syncState.max){$('syncResults').innerHTML=`<h3>🏁 انتهت المباراة</h3>${leaderboardHTML()}`;$('syncResults').classList.remove('hidden');return}syncState.round++;const pool=PARTY_CONTENT.sync.filter(x=>syncState.pack==='all'||x.pack===syncState.pack);syncState.card=uniquePick('sync',pool);syncState.idx=0;syncState.answers={};$('syncResults').classList.add('hidden');$('syncTurn').classList.remove('hidden');renderSyncTurn()}
function renderSyncTurn(){if(syncState.idx>=state.names.length){showSyncResults();return}const n=state.names[syncState.idx];$('syncTurn').innerHTML=`<div class="pill">جولة ${syncState.round}/${syncState.max}</div><div class="big">أعطِ الهاتف لـ ${n}</div><div class="question">${syncState.card.q}</div><input id="syncInput" placeholder="جواب سري…" autocomplete="off"><button class="primary wide" onclick="submitSync()">ثبت وخبّي</button>`;setTimeout(()=>$('syncInput')?.focus(),100)}
function submitSync(){const v=$('syncInput').value.trim();if(!v){toast('اكتب جواب');return}syncState.answers[state.names[syncState.idx]]=v;syncState.idx++;renderSyncTurn()}
function showSyncResults(){$('syncTurn').classList.add('hidden');$('syncResults').classList.remove('hidden');const groups={};Object.entries(syncState.answers).forEach(([n,a])=>(groups[norm(a)]??=[]).push([n,a]));let html=`<div class="pill">${syncState.card.q}</div><h3>النتائج</h3>`;Object.values(groups).forEach(g=>{const pts=g.length===2?3:g.length>=3?1:0;g.forEach(([n])=>pts&&addScore(n,pts));html+=`<div class="resultItem"><span>${g.map(x=>x[0]).join(' + ')}</span><b>${g[0][1]} ${pts?`• +${pts}`:''}</b></div>`});html+=`<button class="primary wide" onclick="nextSyncRound()">الجولة التالية</button>`;$('syncResults').innerHTML=html;record('sync')}

let scaleState={};
function initScale(){uniqueVals(PARTY_CONTENT.scale,'pack').filter(x=>x!=='خلطة').forEach(p=>$('scalePack').insertAdjacentHTML('beforeend',`<option>${p}</option>`));$('scaleSlider').oninput=e=>$('scaleGuessVal').textContent=e.target.value}
function startScaleMatch(){if(!requirePlayers(3))return;scaleState={round:0,max:+$('scaleRounds').value,pack:$('scalePack').value,leaderIdx:0};nextScale()}
function nextScale(){if(scaleState.round>=scaleState.max){$('scaleReveal').innerHTML=`<h3>🏁 انتهت المباراة</h3>${leaderboardHTML()}`;$('scaleReveal').classList.remove('hidden');return}scaleState.round++;const pool=PARTY_CONTENT.scale.filter(x=>scaleState.pack==='all'||x.pack===scaleState.pack);scaleState.card=uniquePick('scale',pool);scaleState.target=Math.floor(Math.random()*101);scaleState.leader=state.names[scaleState.leaderIdx++%state.names.length];$('scaleGuess').classList.add('hidden');$('scaleReveal').classList.add('hidden');$('scaleLeader').classList.remove('hidden');$('scaleLeader').innerHTML=`<div class="handoffIcon">🎯</div><div class="big">القائد: ${scaleState.leader}</div><div class="scaleLabels"><span>${scaleState.card.left}</span><span>${scaleState.card.right}</span></div><div class="timer">${scaleState.target}</div><div class="muted">أعطِ تلميحًا يناسب هذا الموقع. لا تقل الرقم.</div><button class="primary" onclick="openScaleGuess()">خبّي الرقم ومرّر الهاتف</button>`;record('scale')}
function openScaleGuess(){$('scaleLeader').classList.add('hidden');$('scaleGuess').classList.remove('hidden');$('scaleLeft').textContent=scaleState.card.left;$('scaleRight').textContent=scaleState.card.right;$('scaleSlider').value=50;$('scaleGuessVal').textContent=50}
function revealScale(){const g=+$('scaleSlider').value,d=Math.abs(g-scaleState.target),pts=d<=5?4:d<=10?3:d<=20?2:d<=30?1:0;if(pts)addScore(scaleState.leader,pts);$('scaleGuess').classList.add('hidden');$('scaleReveal').classList.remove('hidden');$('scaleReveal').innerHTML=`<div class="big">الهدف ${scaleState.target} • تخمينكم ${g}</div><div class="timer">${pts} نقاط</div><div class="muted">الفرق ${d}</div><button class="primary" onclick="nextScale()">الجولة التالية</button>`;beep(pts?800:250,.14)}

let tabooState={};
function initTaboo(){$('tabooPacks').innerHTML=['خلطة','كرة قدم','تقنية','سفر','أكل','منوعات'].map((p,i)=>`<button class="packBtn ${i===0?'selected':''}" data-pack="${p}" onclick="singlePack(this,'tabooPacks')"><b>${p}</b></button>`).join('')}
function singlePack(btn,id){$$(`#${id} .packBtn`).forEach(x=>x.classList.remove('selected'));btn.classList.add('selected')}
function startTaboo(){tabooState={a:0,b:0,turn:'a',time:+$('tabooTime').value,pack:selectedPacks('tabooPacks')[0]||'خلطة',penalty:+$('tabooPenalty').value};$('tabAName').textContent=$('tabooA').value;$('tabBName').textContent=$('tabooB').value;$('tabAScore').textContent=0;$('tabBScore').textContent=0;$('tabooPlay').classList.remove('hidden');startTabooTurn()}
function startTabooTurn(){tabooState.turnPts=0;$('tabTurn').textContent=`دور ${tabooState.turn==='a'?$('tabooA').value:$('tabooB').value}`;nextTabooCard();countdown($('tabTimer'),tabooState.time,endTabooTurn,$('tabProgress'))}
function nextTabooCard(){let pool=PARTY_CONTENT.taboo.filter(x=>tabooState.pack==='خلطة'||x.pack===tabooState.pack||x.pack==='خلطة');const c=uniquePick('taboo',pool);tabooState.card=c;$('tabWord').textContent=c.word;$('tabForbidden').innerHTML=c.forbidden.map(w=>`<span>${w}</span>`).join('')}
function tabCorrect(){tabooState[tabooState.turn]++;tabooState.turnPts++;$(tabooState.turn==='a'?'tabAScore':'tabBScore').textContent=tabooState[tabooState.turn];beep(900);buzz();nextTabooCard()}
function tabPass(){if(tabooState.penalty){tabooState[tabooState.turn]=Math.max(0,tabooState[tabooState.turn]-tabooState.penalty);$(tabooState.turn==='a'?'tabAScore':'tabBScore').textContent=tabooState[tabooState.turn]}nextTabooCard()}
function tabViolation(){tabooState[tabooState.turn]=Math.max(0,tabooState[tabooState.turn]-1);$(tabooState.turn==='a'?'tabAScore':'tabBScore').textContent=tabooState[tabooState.turn];beep(220);buzz(100);nextTabooCard()}
function endTabooTurn(){const name=tabooState.turn==='a'?$('tabooA').value:$('tabooB').value;addScore(name,tabooState.turnPts);record('taboo');tabooState.turn=tabooState.turn==='a'?'b':'a';toast(`انتهى الدور • ${tabooState.turnPts} صح`);setTimeout(startTabooTurn,1200)}

let drawState={},canvas,ctx,drawHistory=[];
function initDraw(){uniqueVals(PARTY_CONTENT.draw,'pack').filter(x=>x!=='خلطة').forEach(p=>$('drawPack').insertAdjacentHTML('beforeend',`<option>${p}</option>`));canvas=$('canvas');ctx=canvas.getContext('2d');setupCanvasEvents()}
function setupCanvasEvents(){let drawing=false;const pos=e=>{const r=canvas.getBoundingClientRect(),t=e.touches?e.touches[0]:e;return{x:(t.clientX-r.left)*canvas.width/r.width,y:(t.clientY-r.top)*canvas.height/r.height}};const start=e=>{e.preventDefault();drawing=true;drawHistory.push(canvas.toDataURL());const p=pos(e);ctx.beginPath();ctx.moveTo(p.x,p.y)};const move=e=>{if(!drawing)return;e.preventDefault();const p=pos(e);ctx.lineWidth=+$('brushSize').value;ctx.lineCap='round';ctx.strokeStyle='#08111d';ctx.lineTo(p.x,p.y);ctx.stroke()};const end=()=>drawing=false;canvas.addEventListener('pointerdown',start);canvas.addEventListener('pointermove',move);window.addEventListener('pointerup',end);canvas.addEventListener('touchstart',start,{passive:false});canvas.addEventListener('touchmove',move,{passive:false});canvas.addEventListener('touchend',end)}
function resetCanvas(){const r=canvas.getBoundingClientRect();canvas.width=Math.max(600,Math.floor(r.width*2));canvas.height=600;ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);drawHistory=[]}
function clearCanvas(){resetCanvas()}
function undoCanvas(){const src=drawHistory.pop();if(!src)return;const im=new Image();im.onload=()=>{ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(im,0,0)};im.src=src}
function startDraw(){if(!requirePlayers(3))return;const pack=$('drawPack').value,pool=PARTY_CONTENT.draw.filter(x=>pack==='all'||x.pack===pack||x.pack==='خلطة'),card=uniquePick('draw',pool);let order=shuffle(state.names),len=+$('drawLength').value||order.length;order=order.slice(0,Math.min(len,order.length));drawState={order,idx:0,seed:card.word,current:card.word,steps:[{type:'word',value:card.word,who:'البداية'}]};$('drawReveal').classList.add('hidden');$('drawTask').classList.add('hidden');$('drawPass').classList.remove('hidden');renderDrawPass();record('draw',{pack})}
function renderDrawPass(){const n=drawState.order[drawState.idx],isDraw=drawState.idx%2===0;$('drawPass').innerHTML=`<div class="handoffIcon">📱</div><div class="big">أعطِ الهاتف لـ ${n}</div><div class="muted">مهمتك التالية: ${isDraw?'رسم':'تخمين'}</div><button class="primary" onclick="openDrawTask()">أنا ${n} — جاهز</button>`}
function openDrawTask(){const n=drawState.order[drawState.idx],isDraw=drawState.idx%2===0;$('drawPass').classList.add('hidden');$('drawTask').classList.remove('hidden');$('drawWho').textContent=`${n} • ${isDraw?'ارسم':'خمّن'}`;$('drawPrompt').textContent=isDraw?`ارسم: ${drawState.current}`:'شو بتتوقع الرسم؟';$('canvasArea').classList.toggle('hidden',!isDraw);$('guessArea').classList.toggle('hidden',isDraw);if(isDraw)requestAnimationFrame(resetCanvas);else $('drawGuess').value=''}
function submitDrawing(){const data=canvas.toDataURL('image/jpeg',.65);drawState.steps.push({type:'image',value:data,who:drawState.order[drawState.idx]});drawState.current=data;advanceDraw()}
function submitGuess(){const v=$('drawGuess').value.trim();if(!v){toast('اكتب تخمين');return}drawState.steps.push({type:'guess',value:v,who:drawState.order[drawState.idx]});drawState.current=v;advanceDraw()}
function advanceDraw(){drawState.idx++;$('drawTask').classList.add('hidden');if(drawState.idx>=drawState.order.length){showDrawReveal()}else{$('drawPass').classList.remove('hidden');renderDrawPass()}}
function showDrawReveal(){$('drawReveal').classList.remove('hidden');$('drawChain').innerHTML=drawState.steps.map((s,i)=>`<div class="chainItem"><b>${i}. ${s.who}</b>${s.type==='image'?`<img src="${s.value}" alt="رسم">`:`<div class="big">${s.value}</div>`}</div>`).join('')}

let bowl={};
function startBowl(){const words=shuffle(PARTY_CONTENT.bowlWords).slice(0,+$('bowlWords').value);bowl={base:words,deck:shuffle(words),round:1,turn:'a',a:0,b:0,time:+$('bowlTime').value,current:null};$('bowlAName').textContent=$('bowlA').value;$('bowlBName').textContent=$('bowlB').value;$('bowlAScore').textContent=0;$('bowlBScore').textContent=0;$('bowlEnd').classList.add('hidden');$('bowlPlay').classList.remove('hidden');startBowlTurn()}
const bowlRules={1:'اشرح بأي كلمات ما عدا الكلمة نفسها',2:'مسموح كلمة واحدة فقط كتلميح',3:'تمثيل فقط — ممنوع الكلام'};
function startBowlTurn(){if(!bowl.deck.length){if(bowl.round===3){finishBowl();return}bowl.round++;bowl.deck=shuffle(bowl.base);toast(`🔥 الجولة ${bowl.round}`)}$('bowlRound').textContent=`الجولة ${bowl.round}/3 • ${bowl.turn==='a'?$('bowlA').value:$('bowlB').value}`;$('bowlRule').textContent=bowlRules[bowl.round];nextBowlWord();countdown($('bowlTimer'),bowl.time,()=>{bowl.turn=bowl.turn==='a'?'b':'a';record('bowl',{round:bowl.round});setTimeout(startBowlTurn,900)})}
function nextBowlWord(){if(!bowl.deck.length){closeTimer();startBowlTurn();return}bowl.current=bowl.deck.shift();$('bowlWord').textContent=bowl.current}
function bowlCorrect(){bowl[bowl.turn]++;$(bowl.turn==='a'?'bowlAScore':'bowlBScore').textContent=bowl[bowl.turn];beep(900);nextBowlWord()}
function bowlSkip(){if(bowl.current)bowl.deck.push(bowl.current);nextBowlWord()}
function finishBowl(){closeTimer();$('bowlPlay').classList.add('hidden');$('bowlEnd').classList.remove('hidden');const an=$('bowlA').value,bn=$('bowlB').value,w=bowl.a===bowl.b?'تعادل!':`${bowl.a>bowl.b?an:bn} فاز!`;addScore(an,bowl.a);addScore(bn,bowl.b);$('bowlEnd').innerHTML=`<div class="big">🏆 ${w}</div><div class="timer">${bowl.a} — ${bowl.b}</div><button class="primary" onclick="startBowl()">إعادة</button>`}

let bomb={};
function initBomb(){uniqueVals(PARTY_CONTENT.bomb,'pack').forEach(p=>$('bombPack').insertAdjacentHTML('beforeend',`<option>${p}</option>`))}
function startBombMatch(){if(!requirePlayers(3))return;bomb={round:0,max:+$('bombRounds').value,pack:$('bombPack').value,holderIdx:0};$('bombResult').classList.add('hidden');$('bombPlay').classList.remove('hidden');nextBombRound()}
function nextBombRound(){if(bomb.round>=bomb.max){$('bombPlay').classList.add('hidden');$('bombResult').classList.remove('hidden');const strikes=Object.entries(state.session.strikes).sort((a,b)=>a[1]-b[1]);$('bombResult').innerHTML=`<h3>💣 انتهت القنبلة</h3><div class="leaderboard">${strikes.map(([n,s])=>`<div><span>${n}</span><b>${s} ضربات</b></div>`).join('')}</div><button class="primary" onclick="startBombMatch()">إعادة</button>`;return}bomb.round++;const pool=PARTY_CONTENT.bomb.filter(x=>bomb.pack==='all'||x.pack===bomb.pack);bomb.card=uniquePick('bomb',pool);bomb.order=shuffle(state.names);bomb.holderIdx=0;bomb.exploded=false;$('bombRound').textContent=`جولة ${bomb.round}/${bomb.max} • ${bomb.card.pack}`;$('bombPrompt').textContent=bomb.card.q;updateBombHolder();const ms=25000+Math.floor(Math.random()*30000);closeTimer();activeTimer=setTimeout(explodeBomb,ms);record('bomb',{pack:bomb.card.pack})}
function updateBombHolder(){$('bombHolder').textContent=`الهاتف مع: ${bomb.order[bomb.holderIdx]}`}
function bombPass(){if(bomb.exploded)return;bomb.holderIdx=(bomb.holderIdx+1)%bomb.order.length;updateBombHolder();beep(720,.035);buzz(18)}
function explodeBomb(){bomb.exploded=true;const loser=bomb.order[bomb.holderIdx];$('bombVisual').textContent='💥';addStrike(loser);beep(170,.35);buzz([150,80,200]);$('bombPassBtn').disabled=true;setTimeout(()=>{$('bombVisual').textContent='💣';$('bombPassBtn').disabled=false;toast(`💥 انفجرت عند ${loser}`);nextBombRound()},1800)}

function leaderboardHTML(){const scores=Object.entries(state.session.scores).sort((a,b)=>b[1]-a[1]);return `<div class="leaderboard">${scores.map(([n,s],i)=>`<div><span>${i<3?['🥇','🥈','🥉'][i]:''} ${n}</span><b>${s}</b></div>`).join('')||'<div class="muted">لا توجد نقاط بعد</div>'}</div>`}
function updateOnline(){const d=$('onlineDot');d.classList.toggle('offline',!navigator.onLine);d.title=navigator.onLine?'Online':'Offline'}
window.addEventListener('online',updateOnline);window.addEventListener('offline',updateOnline);
function boot(){renderGameGrid();renderNames();initTriviaSetup();initPlayerPacks();initFake();initSync();initScale();initTaboo();initDraw();initBomb();updateOnline();renderHomeStats();$('sessionSubtitle').textContent='جهاز واحد • 2–10 لاعبين • تعمل بدون إنترنت';if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});maybeWake()}
boot();
