(()=>{
'use strict';
if(!window.PN_CAPS)return;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function duelGames(){return GAME_DEFS.filter(g=>PN_CAPS.supports(g.id,{players:2,format:'duel'}))}
window.showDuelHubV31=function(){let m=document.getElementById('duelHubV31');if(!m){m=document.createElement('div');m.id='duelHubV31';m.className='modal partyOSModal';m.onclick=e=>{if(e.target===m)m.classList.remove('open')};m.innerHTML='<div class="modalCard"><div class="nav"><div class="big">⚔️ ألعاب لاعبين</div><button class="ghost" onclick="document.getElementById(\'duelHubV31\').classList.remove(\'open\')">إغلاق</button></div><div class="partyOSBody"></div></div>';document.body.appendChild(m)}const originals=new Set(['blindBid','splitSignal','riskLadder','wordTrap','memoryClash']);const all=duelGames().sort((a,b)=>Number(originals.has(b.id))-Number(originals.has(a.id)));m.querySelector('.partyOSBody').innerHTML=`<div class="duelHubHero31"><span>2 PLAYERS</span><h2>مش لازم تكونوا شلة كبيرة.</h2><p>ألعاب أصلية للمواجهة والتعاون، ومعها ألعاب من المكتبة بتشتغل ممتاز لاثنين.</p></div><div class="duelHubGrid31">${all.map(g=>{const c=PN_CAPS.get(g.id),o=originals.has(g.id);return `<button class="duelHubCard31 ${o?'original':''}" onclick="launchDuelV31('${g.id}')"><span>${g.emoji}</span><div><b>${esc(g.name)}</b><small>${o?'✨ أصلية لـ2':'متوافقة مع لاعبين'} • ~${PN_DIRECTOR31?.minutes?.(g.id)||12} د</small></div>${o?'<i>ORIGINAL</i>':''}</button>`}).join('')}</div><div class="directorNotice31">📱 حاليًا هذه المواجهات تعمل على نفس الهاتف. البنية جاهزة لإضافة جهاز لكل لاعب والأونلاين لاحقًا بدون تغيير قواعد الألعاب.</div>`;m.classList.add('open')};
window.launchDuelV31=function(id){localStorage.setItem('pn.guestCount','2');if(state.names.length<2)window.PN_ENSURE_GUESTS_V31?.(2);document.getElementById('duelHubV31')?.classList.remove('open');showScreen(id)};
function install(){const mini=document.querySelector('.partyOSMiniV30');if(mini&&!document.getElementById('duelHubBtn31'))mini.insertAdjacentHTML('afterbegin','<button id="duelHubBtn31" onclick="showDuelHubV31()">⚔️ لاعبين</button>');const actions=document.querySelector('.partyOSActionsV30');if(actions&&!document.getElementById('duelQuick31'))actions.insertAdjacentHTML('beforeend','<button id="duelQuick31" onclick="showDuelHubV31()"><span>⚔️</span><b>لاعبين</b><small>مواجهات وتعاون لـ2</small></button>')}
setTimeout(install,250);setTimeout(install,1000);
})();