(()=>{
'use strict';
const C=window.PARTY_V26_CONTENT;if(!C)return;
if(!document.getElementById('worldV26Style')){const l=document.createElement('link');l.id='worldV26Style';l.rel='stylesheet';l.href='world-v26.css?v=20260912-world1';document.head.appendChild(l)}
const V=window.PARTY_V26={five:{},majority:{},order:{},emoji:{},estimate:{},memory:{},whisper:{},favoriteOnly:false};
const AVATARS=['🦁','🐯','🐆','🦊','🐺','🐻','🐼','🦅','🦉','🐲','🦈','🐙','⚡','🔥','🌙','⭐','👑','🎯','🎮','⚽','🚀','🧠','🎩','🛡️'];
const LKEY='pn.lifetime.v26';
const lifetime=(()=>{try{return {rounds:0,games:{},recent:[],favorites:[],badges:[],avatars:{},shares:0,launches:0,...JSON.parse(localStorage.getItem(LKEY)||'{}')}}catch{return {rounds:0,games:{},recent:[],favorites:[],badges:[],avatars:{},shares:0,launches:0}}})();
lifetime.launches=(lifetime.launches||0)+1;
const saveLife=()=>localStorage.setItem(LKEY,JSON.stringify(lifetime));saveLife();
const hash=s=>[...String(s||'')].reduce((a,c)=>(a*31+c.charCodeAt(0))>>>0,7);
const avatarFor=n=>lifetime.avatars?.[n]||AVATARS[hash(n)%AVATARS.length];
const gameBy=id=>GAME_DEFS.find(g=>g.id===id);
const clean=s=>(s||'').toLowerCase().replace(/[ًٌٍَُِّْـ]/g,'').replace(/[أإآ]/g,'ا').replace(/ة/g,'ه').replace(/ى/g,'ي').replace(/[^\p{L}\p{N}\s]/gu,' ').replace(/\s+/g,' ').trim();
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function uniqueFrom(key,list){if(!list.length)return null;state.session.used[key]??=[];let pool=list.map((x,i)=>({x,i})).filter(o=>!state.session.used[key].includes(o.i));if(!pool.length){state.session.used[key]=[];pool=list.map((x,i)=>({x,i}))}const o=pick(pool);state.session.used[key].push(o.i);persist();return o.x}
function playerAt(i=0){return state.names.length?state.names[i%state.names.length]:'صاحب الدور'}
function need(n){return requirePlayers(n)}
function setHTML(id,html){const e=$(id);if(e)e.innerHTML=html}
function show(id){$(id)?.classList.remove('hidden')}function hide(id){$(id)?.classList.add('hidden')}

const NEW_GAMES=[
 {id:'five',emoji:'⏱️',name:'خمس ثواني',desc:'3 إجابات قبل ما الوقت يهرب',players:'2–10',time:'10–25 د'},
 {id:'majority',emoji:'🗳️',name:'اختيار الأغلبية',desc:'صوّت بسرية واكتشف وين راح رأي الشلة',players:'3–10',time:'10–25 د'},
 {id:'order',emoji:'🔢',name:'رتّبها',desc:'رتّب الأحداث والأشياء بالترتيب الصح',players:'2–10',time:'10–25 د'},
 {id:'emoji',emoji:'🧩',name:'فك الشفرة',desc:'إيموجي واحد ممكن يخبي لاعب أو فيلم أو فكرة',players:'2–10',time:'8–20 د'},
 {id:'estimate',emoji:'📏',name:'أقرب رقم',desc:'كل واحد يخمّن بسرية والأقرب يكسب',players:'2–10',time:'10–25 د'},
 {id:'memory',emoji:'👁️',name:'لمحة',desc:'شوف 8 كلمات بسرعة وبعدها اختبر ذاكرتك',players:'2–10',time:'10–20 د'},
 {id:'whisper',emoji:'🤫',name:'همسة',desc:'مرّر الجملة بالأذن وشوف شو بيوصل بالآخر',players:'3–10',time:'10–25 د'}
];
NEW_GAMES.forEach(g=>{if(!GAME_DEFS.some(x=>x.id===g.id))GAME_DEFS.push(g)});
Object.assign(GAME_PRESENTATION,{five:{cat:'quick',label:'سرعة • كلام',a:'#df6c21',b:'#b31447',glow:'rgba(223,108,33,.20)'},majority:{cat:'social',label:'تصويت • شلة',a:'#6f4cdf',b:'#bd1d56',glow:'rgba(111,76,223,.2)'},order:{cat:'mind',label:'ترتيب • معرفة',a:'#2368d8',b:'#6332c3',glow:'rgba(35,104,216,.18)'},emoji:{cat:'quick',label:'شفرة • سرعة',a:'#2a77db',b:'#ac2057',glow:'rgba(42,119,219,.2)'},estimate:{cat:'mind',label:'تخمين • أرقام',a:'#2672c9',b:'#1f8e87',glow:'rgba(31,142,135,.18)'},memory:{cat:'mind',label:'ذاكرة • تركيز',a:'#415bd6',b:'#8f2bad',glow:'rgba(65,91,214,.18)'},whisper:{cat:'social',label:'ضحك • همس',a:'#a3276d',b:'#d66a2a',glow:'rgba(163,39,109,.18)'}});
Object.assign(HELP,{
 five:{title:'⏱️ خمس ثواني',players:'2–10',goal:'اذكر 3 إجابات صحيحة قبل انتهاء الوقت.',steps:['اختار الفئة والوقت وعدد الجولات.','الدور ينتقل بين اللاعبين تلقائيًا.','اضغط ابدأ ليظهر التحدي ويبدأ المؤقت.','نجح = نقطتان، فشل = بدون نقاط.'],tip:'7 ثواني ممتازة لأول مباراة؛ 5 ثواني تصير فوضى حلوة.'},
 majority:{title:'🗳️ اختيار الأغلبية',players:'3–10',goal:'اختر A أو B بسرية، والنقطة لمن كان مع الأغلبية.',steps:['كل لاعب يستلم الهاتف وحده.','يقرأ السؤال ويختار أحد الخيارين.','بعد آخر تصويت تنكشف النسب.','كل من اختار رأي الأغلبية يأخذ نقطة.'],tip:'ما في إجابة صح؛ اللعبة تكشف ذوق الشلة.'},
 order:{title:'🔢 رتّبها',players:'2–10',goal:'رتّب العناصر بالترتيب المطلوب.',steps:['يظهر سؤال وأربع بطاقات مخلوطة.','اضغط البطاقات بالترتيب الذي تراه صحيحًا.','يمكنك إعادة الترتيب قبل التثبيت.','كلما كان ترتيبك أدق تأخذ نقاطًا أكثر.'],tip:'ممتازة للمحنكين لأنها تختبر معرفة التفاصيل مش الحفظ السريع.'},
 emoji:{title:'🧩 فك الشفرة',players:'2–10',goal:'اعرف الاسم أو الفكرة من الإيموجي.',steps:['اختار الفئة.','الدور ينتقل تلقائيًا.','اقرأ الشفرة وحاول تخمّن.','اكشف الجواب أو احسبها صح للاعب.'],tip:'استخدم كرة القدم للسهرة الكروية وخلطة للضحك.'},
 estimate:{title:'📏 أقرب رقم',players:'2–10',goal:'أقرب تخمين للرقم الحقيقي يأخذ نقطتين.',steps:['كل لاعب يكتب تخمينه بسرية.','لا أحد يرى تخمين غيره.','بعد آخر لاعب تظهر كل التخمينات.','الأقرب للجواب يأخذ نقطتين، والتعادل يكافئ الاثنين.'],tip:'خلي الإجابات أرقام فقط، والتطبيق يحسب الفرق.'},
 memory:{title:'👁️ لمحة',players:'2–10',goal:'تذكر أكبر عدد من الكلمات التي ظهرت.',steps:['صاحب الدور يرى 8 كلمات لثوانٍ قليلة.','بعدها تختفي وتظهر 16 كلمة.','اختار الثمانية التي تعتقد أنك شفتها.','النقاط حسب عدد الاختيارات الصحيحة.'],tip:'8 ثواني تحدّي قوي؛ 12 ثانية أريح.'},
 whisper:{title:'🤫 همسة',players:'3–10',goal:'حافظوا على الجملة كما هي حتى آخر لاعب.',steps:['أول لاعب يقرأ الجملة بسرية.','يخبّي الشاشة ويهمسها للشخص التالي مرة واحدة.','تستمر الهمسة حتى آخر لاعب.','آخر لاعب يكتب ما وصل له، والتطبيق يقارن النتيجة بالأصل.'],tip:'كل ما كانت الجملة أطول، النهاية أغرب 😂.'}
});

function screensHTML(){return `
<section id="five" class="screen"><div class="nav"><button class="back" onclick="home()">← الرئيسية</button><button class="help" onclick="help('five')">؟ كيف نلعب</button></div><div class="gameHero"><span class="gameIcon">⏱️</span><div><h2>خمس ثواني</h2><p>3 إجابات، ضغط وقت، ودور يلف على الشلة.</p></div></div><div class="panel v26Setup"><div class="row compact"><label>الفئة</label><select id="fivePack"><option value="all">خلطة</option><option value="football">كرة قدم</option><option value="general">منوعات</option><option value="fun">ضحك</option></select><label>الوقت</label><select id="fiveTime"><option value="5">5 ث</option><option value="7" selected>7 ث</option><option value="10">10 ث</option></select><label>الجولات</label><select id="fiveRounds"><option>10</option><option selected>15</option><option>20</option></select></div><button class="primary wide" onclick="startFiveV26()">ابدأ التحدي</button></div><div id="fiveStage" class="panel v26Stage hidden"></div></section>
<section id="majority" class="screen"><div class="nav"><button class="back" onclick="home()">← الرئيسية</button><button class="help" onclick="help('majority')">؟ كيف نلعب</button></div><div class="gameHero"><span class="gameIcon">🗳️</span><div><h2>اختيار الأغلبية</h2><p>اختيارات سرية تكشف ذوق الشلة.</p></div></div><div class="panel"><div class="row compact"><label>الجولات</label><select id="majorityRounds"><option>5</option><option selected>8</option><option>12</option></select></div><button class="primary wide" onclick="startMajorityV26()">ابدأ المباراة</button></div><div id="majorityStage" class="panel v26Stage hidden"></div></section>
<section id="order" class="screen"><div class="nav"><button class="back" onclick="home()">← الرئيسية</button><button class="help" onclick="help('order')">؟ كيف نلعب</button></div><div class="gameHero"><span class="gameIcon">🔢</span><div><h2>رتّبها</h2><p>المعرفة وحدها مش كفاية — لازم الترتيب يكون صح.</p></div></div><div class="panel"><div class="row compact"><label>الجولات</label><select id="orderRounds"><option>5</option><option selected>8</option><option>12</option></select></div><button class="primary wide" onclick="startOrderV26()">ابدأ المباراة</button></div><div id="orderStage" class="panel v26Stage hidden"></div></section>
<section id="emoji" class="screen"><div class="nav"><button class="back" onclick="home()">← الرئيسية</button><button class="help" onclick="help('emoji')">؟ كيف نلعب</button></div><div class="gameHero"><span class="gameIcon">🧩</span><div><h2>فك الشفرة</h2><p>من كم إيموجي إلى اسم كامل.</p></div></div><div class="panel"><div class="row compact"><label>الفئة</label><select id="emojiPack"><option value="all">خلطة</option><option value="football">كرة قدم</option><option value="movies">أفلام</option><option value="general">منوعات</option></select></div><button class="primary wide" onclick="startEmojiV26()">بطاقة جديدة</button></div><div id="emojiStage" class="panel v26Stage hidden"></div></section>
<section id="estimate" class="screen"><div class="nav"><button class="back" onclick="home()">← الرئيسية</button><button class="help" onclick="help('estimate')">؟ كيف نلعب</button></div><div class="gameHero"><span class="gameIcon">📏</span><div><h2>أقرب رقم</h2><p>لا تحتاج تعرف الجواب — بس لازم تكون أقرب واحد.</p></div></div><div class="panel"><button class="primary wide" onclick="startEstimateV26()">سؤال جديد</button></div><div id="estimateStage" class="panel v26Stage hidden"></div></section>
<section id="memory" class="screen"><div class="nav"><button class="back" onclick="home()">← الرئيسية</button><button class="help" onclick="help('memory')">؟ كيف نلعب</button></div><div class="gameHero"><span class="gameIcon">👁️</span><div><h2>لمحة</h2><p>8 كلمات، ثوانٍ قليلة، وبعدها الذاكرة تحكم.</p></div></div><div class="panel"><div class="row compact"><label>وقت الحفظ</label><select id="memoryTime"><option value="8" selected>8 ث</option><option value="10">10 ث</option><option value="12">12 ث</option></select></div><button class="primary wide" onclick="startMemoryV26()">جولة جديدة</button></div><div id="memoryStage" class="panel v26Stage hidden"></div></section>
<section id="whisper" class="screen"><div class="nav"><button class="back" onclick="home()">← الرئيسية</button><button class="help" onclick="help('whisper')">؟ كيف نلعب</button></div><div class="gameHero"><span class="gameIcon">🤫</span><div><h2>همسة</h2><p>الجملة تبدأ بشيء وتنتهي غالبًا بشيء ثاني 😂.</p></div></div><div class="panel"><label class="tiny">جملة خاصة اختيارية</label><input id="whisperCustom" placeholder="اكتب جملة من عندك أو اتركها فارغة"><button class="primary wide" onclick="startWhisperV26()">ابدأ جولة</button></div><div id="whisperStage" class="panel v26Stage hidden"></div></section>`}
const main=document.querySelector('main');if(main&&!$('five'))main.insertAdjacentHTML('beforeend',screensHTML());
if(!$('smartModal'))document.body.insertAdjacentHTML('beforeend',`<div id="smartModal" class="modal" onclick="if(event.target===this)closeModal('smartModal')"><div class="modalCard"><div class="nav"><div class="big">✨ السهرة الذكية</div><button class="ghost" onclick="closeModal('smartModal')">إغلاق</button></div><div id="smartBodyV26"></div></div></div><div id="achievementsModal" class="modal" onclick="if(event.target===this)closeModal('achievementsModal')"><div class="modalCard"><div class="nav"><div class="big">🏅 الإنجازات</div><button class="ghost" onclick="closeModal('achievementsModal')">إغلاق</button></div><div id="achievementsBodyV26"></div></div></div><div id="playerStudioModal" class="modal" onclick="if(event.target===this)closeModal('playerStudioModal')"><div class="modalCard"><div class="nav"><div class="big">🎭 شخصيات اللاعبين</div><button class="ghost" onclick="closeModal('playerStudioModal')">إغلاق</button></div><div id="playerStudioBodyV26"></div></div></div><div id="smartDockV26" class="smartDockV26 hidden"></div>`);

window.startFiveV26=function(){if(!need(2))return;V.five={round:0,max:+$('fiveRounds').value,idx:0,pack:$('fivePack').value,time:+$('fiveTime').value};show('fiveStage');nextFiveV26()};
window.nextFiveV26=function(){const s=V.five;if(s.round>=s.max){setHTML('fiveStage',`<div class="v26Result good"><div class="v26Mega">🏁</div><h2>خلص التحدي</h2><button class="primary" onclick="startFiveV26()">إعادة</button></div>`);return}s.round++;s.player=playerAt(s.idx++);const pool=C.fiveSec.filter(x=>s.pack==='all'||x[0]===s.pack);s.card=uniqueFrom('v26.five',pool);setHTML('fiveStage',`<div class="v26Player"><span class="avatar">${avatarFor(s.player)}</span>${esc(s.player)} • ${s.round}/${s.max}</div><div class="v26Prompt">جاهز للتحدي؟</div><div class="muted center">اضغط ابدأ، بعدها لازم تقول 3 إجابات.</div><button class="gold wide" onclick="runFiveV26()">⏱️ ابدأ ${s.time} ثواني</button>`)};
window.runFiveV26=function(){const s=V.five;setHTML('fiveStage',`<div class="v26Player"><span class="avatar">${avatarFor(s.player)}</span>${esc(s.player)}</div><div class="v26Prompt">${esc(s.card[1])}</div><div id="fiveTimerV26" class="v26Timer">${s.time}</div><div class="actions"><button class="primary" onclick="finishFiveV26(true)">✅ نجح</button><button class="danger" onclick="finishFiveV26(false)">❌ فشل</button></div>`);countdown($('fiveTimerV26'),s.time,()=>finishFiveV26(false))};
window.finishFiveV26=function(ok){closeTimer();const s=V.five;if(s.lock)return;s.lock=true;if(ok)addScore(s.player,2);record('five',{ok});setHTML('fiveStage',`<div class="v26Result ${ok?'good':'bad'}"><div class="v26Mega">${ok?'✅':'⏱️'}</div><h2>${ok?`+2 لـ ${esc(s.player)}`:'انتهى الوقت'}</h2><button class="primary" onclick="V26UnlockFive()">التالي</button></div>`)};window.V26UnlockFive=function(){V.five.lock=false;nextFiveV26()};

window.startMajorityV26=function(){if(!need(3))return;V.majority={round:0,max:+$('majorityRounds').value};show('majorityStage');nextMajorityV26()};
window.nextMajorityV26=function(){const s=V.majority;if(s.round>=s.max){setHTML('majorityStage','<div class="v26Result good"><div class="v26Mega">🏁</div><h2>انتهت المباراة</h2><button class="primary" onclick="startMajorityV26()">إعادة</button></div>');return}s.round++;s.card=uniqueFrom('v26.majority',C.majority);s.order=shuffle(state.names);s.idx=0;s.votes={};renderMajorityVoteV26()};
window.renderMajorityVoteV26=function(){const s=V.majority;if(s.idx>=s.order.length){finishMajorityV26();return}const n=s.order[s.idx];setHTML('majorityStage',`<div class="v26Player"><span class="avatar">${avatarFor(n)}</span>دور ${esc(n)} • جولة ${s.round}/${s.max}</div><div class="v26Prompt">${esc(s.card[2])}</div><div class="muted center">اختيارك سري</div><div class="voteButtonsV26"><button class="voteA" onclick="voteMajorityV26('a')">${esc(s.card[0])}</button><button class="voteB" onclick="voteMajorityV26('b')">${esc(s.card[1])}</button></div>`)};
window.voteMajorityV26=function(v){const s=V.majority;s.votes[s.order[s.idx]]=v;s.idx++;buzz();renderMajorityVoteV26()};
window.finishMajorityV26=function(){const s=V.majority,a=Object.values(s.votes).filter(v=>v==='a').length,b=Object.values(s.votes).filter(v=>v==='b').length,w=a===b?null:(a>b?'a':'b');if(w)Object.entries(s.votes).forEach(([n,v])=>v===w&&addScore(n,1));record('majority',{a,b});setHTML('majorityStage',`<div class="v26Prompt">${esc(s.card[2])}</div><div class="voteBarV26"><i style="width:${a/(a+b)*100}%"></i><i style="width:${b/(a+b)*100}%"></i></div><div class="voteNumbersV26"><span>${esc(s.card[0])}: ${a}</span><span>${esc(s.card[1])}: ${b}</span></div><div class="v26Result ${w?'good':''}"><b>${w?`الأغلبية: ${esc(w==='a'?s.card[0]:s.card[1])}`:'تعادل — ما في نقاط'}</b></div><button class="primary wide" onclick="nextMajorityV26()">الجولة التالية</button>`)};

window.startOrderV26=function(){if(!need(2))return;V.order={round:0,max:+$('orderRounds').value,idx:0};show('orderStage');nextOrderV26()};
window.nextOrderV26=function(){const s=V.order;if(s.round>=s.max){setHTML('orderStage','<div class="v26Result good"><div class="v26Mega">🏁</div><h2>انتهت المباراة</h2><button class="primary" onclick="startOrderV26()">إعادة</button></div>');return}s.round++;s.player=playerAt(s.idx++);s.card=uniqueFrom('v26.order',C.order);s.pool=shuffle(s.card.items);s.chosen=[];renderOrderV26()};
window.renderOrderV26=function(){const s=V.order;setHTML('orderStage',`<div class="v26Player"><span class="avatar">${avatarFor(s.player)}</span>${esc(s.player)} • ${s.round}/${s.max}</div><div class="v26Prompt">${esc(s.card.q)}</div><div class="orderChosenV26">${s.chosen.map((x,i)=>`<span>${i+1}. ${esc(x)}</span>`).join('')||'<span class="muted">اضغط العناصر بالترتيب</span>'}</div><div class="orderPoolV26">${s.pool.filter(x=>!s.chosen.includes(x)).map(x=>`<button class="ghost" onclick="chooseOrderV26('${encodeURIComponent(x)}')">${esc(x)}</button>`).join('')}</div><div class="actions"><button class="ghost" onclick="resetOrderV26()">↶ إعادة</button>${s.chosen.length===s.card.answer.length?'<button class="gold" onclick="submitOrderV26()">ثبت الترتيب</button>':''}</div>`)};
window.chooseOrderV26=function(x){V.order.chosen.push(decodeURIComponent(x));renderOrderV26()};window.resetOrderV26=function(){V.order.chosen=[];renderOrderV26()};
window.submitOrderV26=function(){const s=V.order;let exact=0;s.card.answer.forEach((x,i)=>{if(s.chosen[i]===x)exact++});const pts=exact===s.card.answer.length?3:exact>=3?2:exact>=2?1:0;if(pts)addScore(s.player,pts);record('order',{exact,pts});setHTML('orderStage',`<div class="v26Result ${pts?'good':'bad'}"><h2>${pts?`+${pts} لـ ${esc(s.player)}`:'مش هالمرة'}</h2><div class="tiny">الترتيب الصحيح</div><div class="orderChosenV26">${s.card.answer.map((x,i)=>`<span>${i+1}. ${esc(x)}</span>`).join('')}</div>${s.card.note?`<p class="muted">${esc(s.card.note)}</p>`:''}<button class="primary" onclick="nextOrderV26()">التالي</button></div>`)};

window.startEmojiV26=function(){if(!need(2))return;const pack=$('emojiPack').value;const pool=C.emoji.filter(x=>pack==='all'||x[0]===pack);V.emoji.idx=(V.emoji.idx||0);V.emoji.player=playerAt(V.emoji.idx++);V.emoji.card=uniqueFrom('v26.emoji',pool);show('emojiStage');setHTML('emojiStage',`<div class="v26Player"><span class="avatar">${avatarFor(V.emoji.player)}</span>${esc(V.emoji.player)}</div><div class="v26Badge">${esc(V.emoji.card[3])}</div><div class="emojiCodeV26">${V.emoji.card[1]}</div><div id="emojiAnswerV26" class="answer hidden">${esc(V.emoji.card[2])}</div><div class="actions"><button class="gold" onclick="$('emojiAnswerV26').classList.remove('hidden')">👁 كشف</button><button class="primary" onclick="solveEmojiV26()">✅ عرفها</button><button class="ghost" onclick="startEmojiV26()">⏭ التالي</button></div>`)};
window.solveEmojiV26=function(){addScore(V.emoji.player,1);record('emoji');toast(`+1 لـ ${V.emoji.player}`);startEmojiV26()};

window.startEstimateV26=function(){if(!need(2))return;V.estimate={card:uniqueFrom('v26.estimate',C.estimate),order:shuffle(state.names),idx:0,guesses:{}};show('estimateStage');renderEstimateV26()};
window.renderEstimateV26=function(){const s=V.estimate;if(s.idx>=s.order.length){finishEstimateV26();return}const n=s.order[s.idx];setHTML('estimateStage',`<div class="v26Player"><span class="avatar">${avatarFor(n)}</span>دور ${esc(n)}</div><div class="v26Prompt">${esc(s.card[0])}</div><input id="estimateInputV26" class="estimateInputV26" inputmode="decimal" type="number" step="any" placeholder="اكتب تخمينك"><button class="primary wide" onclick="submitEstimateV26()">ثبت وخبّي</button>`);setTimeout(()=>$('estimateInputV26')?.focus(),80)};
window.submitEstimateV26=function(){const v=parseFloat($('estimateInputV26').value);if(!Number.isFinite(v)){toast('اكتب رقم');return}const s=V.estimate;s.guesses[s.order[s.idx]]=v;s.idx++;renderEstimateV26()};
window.finishEstimateV26=function(){const s=V.estimate,target=+s.card[1],rows=Object.entries(s.guesses).map(([n,v])=>({n,v,d:Math.abs(v-target)})).sort((a,b)=>a.d-b.d),best=rows[0]?.d,winners=rows.filter(r=>r.d===best);winners.forEach(r=>addScore(r.n,2));record('estimate',{target});setHTML('estimateStage',`<div class="v26Prompt">الجواب: ${target} ${esc(s.card[2])}</div><div class="estimateListV26">${rows.map(r=>`<div class="estimateRowV26 ${r.d===best?'winner':''}"><span>${avatarFor(r.n)} ${esc(r.n)}</span><b>${r.v}</b><small>فرق ${Number(r.d.toFixed(2))}</small></div>`).join('')}</div><div class="v26Result good">🏆 ${winners.map(r=>esc(r.n)).join(' + ')} +2</div><button class="primary wide" onclick="startEstimateV26()">سؤال جديد</button>`)};

window.startMemoryV26=function(){if(!need(2))return;V.memory.idx=(V.memory.idx||0);V.memory.player=playerAt(V.memory.idx++);V.memory.card=uniqueFrom('v26.memory',C.memory);V.memory.selected=[];show('memoryStage');setHTML('memoryStage',`<div class="v26Player"><span class="avatar">${avatarFor(V.memory.player)}</span>${esc(V.memory.player)}</div><div class="v26Prompt">جاهز للحفظ؟</div><button class="gold wide" onclick="runMemoryV26()">👁️ ابدأ</button>`)};
window.runMemoryV26=function(){const s=V.memory,t=+$('memoryTime').value;setHTML('memoryStage',`<div class="v26Player"><span class="avatar">${avatarFor(s.player)}</span>${esc(s.player)}</div><div id="memoryTimerV26" class="v26Timer">${t}</div><div class="memoryWordsV26">${s.card[1].map(w=>`<span>${esc(w)}</span>`).join('')}</div>`);countdown($('memoryTimerV26'),t,showMemoryChoicesV26)};
window.showMemoryChoicesV26=function(){closeTimer();const s=V.memory;s.options=shuffle([...s.card[1],...s.card[2]]);setHTML('memoryStage',`<div class="v26Player">${avatarFor(s.player)} ${esc(s.player)}</div><div class="v26Prompt">اختار الكلمات الثمانية اللي شفتها</div><div id="memoryOptionsV26" class="memoryOptionsV26">${s.options.map((w,i)=>`<button onclick="toggleMemoryV26(${i},this)">${esc(w)}</button>`).join('')}</div><div class="tiny center" id="memoryCountV26">0 / 8</div><button class="gold wide" onclick="submitMemoryV26()">ثبت</button>`)};
window.toggleMemoryV26=function(i,b){const s=V.memory,w=s.options[i],at=s.selected.indexOf(w);if(at>=0){s.selected.splice(at,1);b.classList.remove('selected')}else{if(s.selected.length>=8){toast('اختار 8 فقط');return}s.selected.push(w);b.classList.add('selected')}$('memoryCountV26').textContent=`${s.selected.length} / 8`};
window.submitMemoryV26=function(){const s=V.memory;if(s.selected.length!==8){toast('اختار 8 كلمات');return}const correct=s.selected.filter(w=>s.card[1].includes(w)).length,pts=correct===8?3:correct>=6?2:correct>=4?1:0;if(pts)addScore(s.player,pts);record('memory',{correct});setHTML('memoryStage',`<div class="v26Result ${pts?'good':'bad'}"><div class="v26Mega">${correct}/8</div><h2>${pts?`+${pts} لـ ${esc(s.player)}`:'بدها تركيز أكثر 😄'}</h2><p class="muted">الكلمات الصحيحة: ${s.card[1].map(esc).join(' • ')}</p><button class="primary" onclick="startMemoryV26()">جولة جديدة</button></div>`)};

window.startWhisperV26=function(){if(!need(3))return;V.whisper.idx=(V.whisper.idx||0);const custom=$('whisperCustom').value.trim();V.whisper.phrase=custom||uniqueFrom('v26.whisper',C.whisper);V.whisper.first=playerAt(V.whisper.idx++);V.whisper.last=state.names[(state.names.indexOf(V.whisper.first)-1+state.names.length)%state.names.length];show('whisperStage');setHTML('whisperStage',`<div class="v26Player"><span class="avatar">${avatarFor(V.whisper.first)}</span>${esc(V.whisper.first)} فقط يشوف الشاشة</div><div class="whisperPhraseV26">${esc(V.whisper.phrase)}</div><div class="muted center">احفظها، بعدها اضغط وخبّي الشاشة.</div><button class="primary wide" onclick="hideWhisperV26()">حفظت الجملة</button>`)};
window.hideWhisperV26=function(){const s=V.whisper;setHTML('whisperStage',`<div class="v26Mega">🤫</div><div class="v26Prompt">ابدأ الهمس</div><p class="muted center">${esc(s.first)} يهمس للشخص التالي مرة واحدة، وكل شخص يمررها للي بعده.</p><p class="center">آخر واحد: <b>${esc(s.last)}</b></p><button class="gold wide" onclick="finalWhisperV26()">وصلت لآخر لاعب</button>`)};
window.finalWhisperV26=function(){const s=V.whisper;setHTML('whisperStage',`<div class="v26Player">${avatarFor(s.last)} ${esc(s.last)}</div><div class="v26Prompt">اكتب الجملة اللي وصلتك</div><textarea id="whisperFinalV26" rows="3" placeholder="اكتبها هنا..."></textarea><button class="primary wide" onclick="scoreWhisperV26()">قارن النتيجة</button>`)};
window.scoreWhisperV26=function(){const s=V.whisper,got=$('whisperFinalV26').value.trim();if(!got){toast('اكتب الجملة');return}const a=new Set(clean(s.phrase).split(' ').filter(Boolean)),b=new Set(clean(got).split(' ').filter(Boolean));const hit=[...a].filter(x=>b.has(x)).length,score=a.size?Math.round(hit/a.size*100):0,pts=score>=70?2:score>=40?1:0;if(pts){addScore(s.first,pts);addScore(s.last,pts)}record('whisper',{similarity:score});setHTML('whisperStage',`<div class="v26Result ${score>=70?'good':score<40?'bad':''}"><div class="v26Mega">${score}%</div><div class="tiny">الأصل</div><p>${esc(s.phrase)}</p><div class="tiny">اللي وصل</div><p>${esc(got)}</p><h3>${score>=70?'وصلت بشكل ممتاز 👏':score>=40?'قريبة بشكل مفاجئ 😄':'تحولت لجملة ثانية تمامًا 😂'}</h3><button class="primary" onclick="startWhisperV26()">جولة جديدة</button></div>`)};

const oldRecord=window.record;window.record=function(game,detail={}){oldRecord(game,detail);lifetime.rounds=(lifetime.rounds||0)+1;lifetime.games[game]=(lifetime.games[game]||0)+1;saveLife();checkAchievementsV26();updateHubV26()};
const oldShowScreen=window.showScreen;window.showScreen=function(id){oldShowScreen(id);if(gameBy(id)){lifetime.recent=[id,...(lifetime.recent||[]).filter(x=>x!==id)].slice(0,6);saveLife()}renderRecentV26();renderSmartDockV26()};
const ACH=[['first','🎉','أول صافرة','العب أول جولة',()=>lifetime.rounds>=1],['warm','🔥','سخنت السهرة','العب 25 جولة',()=>lifetime.rounds>=25],['century','💯','ماراثون','العب 100 جولة',()=>lifetime.rounds>=100],['explore5','🗺️','مستكشف','جرّب 5 ألعاب مختلفة',()=>Object.keys(lifetime.games).length>=5],['explore10','🚀','مستكشف محترف','جرّب 10 ألعاب مختلفة',()=>Object.keys(lifetime.games).length>=10],['all','👑','ملك الـParty Hub',`جرّب ${GAME_DEFS.length} لعبة مختلفة`,()=>Object.keys(lifetime.games).length>=GAME_DEFS.length],['share','📨','جيب الشلة','شارك اللعبة مرة',()=>lifetime.shares>=1],['fan','⭐','مفضلاتك جاهزة','احفظ 3 ألعاب بالمفضلة',()=>lifetime.favorites.length>=3]];
window.checkAchievementsV26=function(){ACH.forEach(([id,em,n,d,ok])=>{if(ok()&&!lifetime.badges.includes(id)){lifetime.badges.push(id);saveLife();toast(`🏅 إنجاز جديد: ${n}`)}})};
window.showAchievementsV26=function(){checkAchievementsV26();const unique=Object.keys(lifetime.games).length;$('achievementsBodyV26').innerHTML=`<div class="lifetimeHeroV26"><div><b>${lifetime.rounds||0}</b><span>جولة</span></div><div><b>${unique}</b><span>ألعاب</span></div><div><b>${lifetime.badges.length}</b><span>إنجاز</span></div></div><div class="achievementGridV26">${ACH.map(([id,em,n,d,ok])=>`<div class="achievementV26 ${ok()?'':'locked'}"><span>${em}</span><b>${n}</b><small>${d}</small></div>`).join('')}</div>`;$('achievementsModal').classList.add('open')};

window.showPlayerStudioV26=function(){if(!state.names.length){toast('أضف أسماء اللاعبين أولًا');return}renderPlayerStudioV26();$('playerStudioModal').classList.add('open')};
window.renderPlayerStudioV26=function(){$('playerStudioBodyV26').innerHTML=`<p class="muted">اضغط الإيموجي لتغييره. الاختيار محفوظ على جهازك.</p><div class="playerStudioV26">${state.names.map(n=>`<div class="playerRowV26"><button class="avatarButtonV26" onclick="cycleAvatarV26('${encodeURIComponent(n)}')">${avatarFor(n)}</button><b>${esc(n)}</b><small>شخصية اللاعب</small></div>`).join('')}</div>`};
window.cycleAvatarV26=function(enc){const n=decodeURIComponent(enc),cur=avatarFor(n),i=AVATARS.indexOf(cur);lifetime.avatars[n]=AVATARS[(i+1)%AVATARS.length];saveLife();renderPlayerStudioV26();decorateNameChipsV26()};
function decorateNameChipsV26(){const chips=$$('#nameChips .chip');chips.forEach((c,i)=>{const n=state.names[i];if(!n)return;if(!c.querySelector('.profileAvatarV26'))c.insertAdjacentHTML('afterbegin',`<span class="profileAvatarV26">${avatarFor(n)}</span>`)})}
const oldRenderNames=window.renderNames;window.renderNames=function(){oldRenderNames();decorateNameChipsV26()};

const VIBES={balanced:{name:'متوازنة',emoji:'✨',pool:null},football:{name:'كروية',emoji:'⚽',pool:['trivia','player','emoji','five','order','estimate','bomb']},brain:{name:'ذكاء وتركيز',emoji:'🧠',pool:['trivia','scale','sync','order','estimate','memory','emoji']},laughs:{name:'ضحك وشلة',emoji:'😂',pool:['fake','draw','bowl','whisper','five','majority','taboo','bomb']},fast:{name:'سريعة',emoji:'⚡',pool:['five','emoji','bomb','player','majority','taboo']}};
window.showSmartPartyV26=function(){const s=state.session.smartNight;let body=`<p class="muted">اختار الوقت والمود، وأنا أركب Playlist متنوعة تناسب عددكم بدون تكرار ألعاب.</p><div class="smartGridV26"><label>مدة السهرة<select id="smartDurationV26"><option value="30">30 دقيقة</option><option value="60" selected>60 دقيقة</option><option value="90">90 دقيقة</option><option value="120">120 دقيقة</option></select></label><label>المود<select id="smartVibeV26">${Object.entries(VIBES).map(([id,v])=>`<option value="${id}">${v.emoji} ${v.name}</option>`).join('')}</select></label></div><button class="gold wide" style="margin-top:12px" onclick="buildSmartPartyV26()">✨ ابنِ السهرة</button>`;if(s?.games?.length)body+=smartQueueHTMLV26(s);$('smartBodyV26').innerHTML=body;$('smartModal').classList.add('open')};
function smartQueueHTMLV26(s){return `<div class="smartQueueV26">${s.games.map((id,i)=>{const g=gameBy(id);return `<div class="smartQueueItemV26 ${i<s.index?'done':i===s.index?'current':''}"><span>${g?.emoji||'🎮'}</span><div><b>${g?.name||id}</b><small>${i<s.index?'مكتملة':i===s.index?'المحطة الحالية':`المحطة ${i+1}`}</small></div>${i===s.index&&!s.complete?`<button class="primary small" onclick="launchSmartGameV26()">ابدأ</button>`:''}</div>`}).join('')}</div>${s.complete?'<div class="v26Result good"><h3>🏆 خلصت السهرة الذكية!</h3></div>':'<div class="actions"><button class="ghost" onclick="cancelSmartPartyV26()">إلغاء الخطة</button></div>'}`}
window.buildSmartPartyV26=function(){if(!need(2))return;const duration=+$('smartDurationV26').value,vibe=$('smartVibeV26').value,count=duration<=30?4:duration<=60?6:duration<=90?8:10,minPlayers=state.names.length;let pool=GAME_DEFS.filter(g=>minPlayers>=parseInt(g.players));const pref=VIBES[vibe].pool;if(pref)pool=pool.filter(g=>pref.includes(g.id));if(pool.length<count){const extra=GAME_DEFS.filter(g=>minPlayers>=parseInt(g.players)&&!pool.some(x=>x.id===g.id));pool=[...pool,...extra]}const games=shuffle(pool).slice(0,Math.min(count,pool.length)).map(g=>g.id);state.session.smartNight={active:true,complete:false,games,index:0,vibe,duration,startedAt:Date.now()};persist();renderSmartDockV26();showSmartPartyV26()};
window.launchSmartGameV26=function(){const s=state.session.smartNight;if(!s?.active||s.complete)return;closeModal('smartModal');showScreen(s.games[s.index])};
window.smartNextV26=function(){const s=state.session.smartNight;if(!s?.active)return;s.index++;if(s.index>=s.games.length){s.complete=true;s.active=false;persist();renderSmartDockV26();toast('🏆 خلصت السهرة الذكية!');home();return}persist();showScreen(s.games[s.index]);renderSmartDockV26()};
window.cancelSmartPartyV26=function(){state.session.smartNight=null;persist();renderSmartDockV26();closeModal('smartModal');toast('تم إلغاء الخطة')};
window.renderSmartDockV26=function(){const e=$('smartDockV26'),s=state.session.smartNight;if(!e)return;if(!s?.active||s.complete||$('home')?.classList.contains('active')){e.classList.add('hidden');return}const g=gameBy(s.games[s.index]),next=gameBy(s.games[s.index+1]);e.classList.remove('hidden');e.innerHTML=`<span>${g?.emoji||'🎮'}</span><div><b>${g?.name||'اللعبة الحالية'} • ${s.index+1}/${s.games.length}</b><small>${next?`التالي: ${next.name}`:'آخر محطة'}</small></div><button class="gold small" onclick="smartNextV26()">التالي ⏭</button>`};

window.shareGameV26=async function(){const data={title:'ليلة التحدي',text:'جرّب لعبة ليلة التحدي 🎉',url:'https://vyronashop-blip.github.io/party-night/'};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(data.url);toast('تم نسخ الرابط')}lifetime.shares=(lifetime.shares||0)+1;saveLife();checkAchievementsV26()}catch(e){if(e?.name!=='AbortError')toast('ما قدرت أشارك الرابط')}};

const applyA11yV26=()=>{document.documentElement.classList.toggle('v26LargeText',state.settings.v26Text==='large');document.documentElement.classList.toggle('v26HighContrast',!!state.settings.v26Contrast);document.documentElement.classList.toggle('v26ReduceMotion',!!state.settings.v26ReduceMotion)};applyA11yV26();
window.setV26Setting=function(k,v){state.settings[k]=v;persist();applyA11yV26()};
const oldCountdown=window.countdown;window.countdown=function(el,seconds,onEnd,progressEl){const scale=Number(state.settings.v26TimerScale||1);return oldCountdown(el,Math.max(1,Math.round(seconds*scale)),onEnd,progressEl)};
const oldShowSettings=window.showSettings;window.showSettings=function(){oldShowSettings();const b=$('settingsBody');if(!b||$('v26SettingsBlock'))return;b.insertAdjacentHTML('beforeend',`<div id="v26SettingsBlock"><h3>♿ راحة وتجربة اللعب</h3><div class="helpSteps"><label class="helpStep"><span>🔤 نص أكبر</span><input type="checkbox" ${state.settings.v26Text==='large'?'checked':''} onchange="setV26Setting('v26Text',this.checked?'large':'normal')"></label><label class="helpStep"><span>✨ تقليل الحركة</span><input type="checkbox" ${state.settings.v26ReduceMotion?'checked':''} onchange="setV26Setting('v26ReduceMotion',this.checked)"></label><label class="helpStep"><span>◐ تباين أعلى</span><input type="checkbox" ${state.settings.v26Contrast?'checked':''} onchange="setV26Setting('v26Contrast',this.checked)"></label><label class="helpStep"><span>⏱️ تمديد المؤقتات</span><select onchange="setV26Setting('v26TimerScale',this.value)"><option value="1" ${String(state.settings.v26TimerScale||1)==='1'?'selected':''}>عادي</option><option value="1.5" ${String(state.settings.v26TimerScale)==='1.5'?'selected':''}>×1.5 مريح</option><option value="2" ${String(state.settings.v26TimerScale)==='2'?'selected':''}>×2 ممتد</option></select></label></div></div>`)};

function injectHubV26(){const status=$('presetStatus');if(status&&!$('v26Hub'))status.insertAdjacentHTML('afterend',`<div id="v26Hub" class="v26Hub"><div class="v26SmartHero"><span class="v26Badge">WORLD-CLASS PARTY FLOW</span><h3>✨ خلّي اللعبة ترتب السهرة عنك</h3><p>حدد وقتكم والمود، ونبني لكم مسار ألعاب متنوع يناسب عدد اللاعبين.</p><div class="v26HeroActions"><button class="gold" onclick="showSmartPartyV26()">ابدأ سهرة ذكية</button><button class="ghost" onclick="showAchievementsV26()">🏅 الإنجازات</button><button class="ghost shareChipV26" onclick="shareGameV26()">📨 مشاركة</button></div></div><div id="recentAreaV26"></div></div>`);const title=document.querySelector('#home .sectionTitle');if(title&&!$('libraryToolsV26'))title.insertAdjacentHTML('afterend',`<div id="libraryToolsV26" class="libraryToolsV26"><div class="librarySearchV26"><span>⌕</span><input id="gameSearchV26" placeholder="ابحث عن لعبة…" oninput="filterGamesV26()"></div><button id="favToggleV26" class="ghost libraryToggleV26" onclick="toggleFavoritesV26()">★ المفضلة</button><button class="ghost libraryToggleV26" onclick="showPlayerStudioV26()">🎭 اللاعبين</button></div>`);const hero=document.querySelector('.matchHeroCopy p');if(hero)hero.textContent=`${GAME_DEFS.length} لعبة، بطولة، سهرة ذكية، إنجازات، باكات ضخمة، ونظام نقاط من تلفون واحد — بروح كروية زرقاء وحمراء.`;renderRecentV26();decorateGameCardsV26();updateHubV26()}
function renderRecentV26(){const e=$('recentAreaV26');if(!e)return;const ids=(lifetime.recent||[]).filter(id=>gameBy(id));e.innerHTML=ids.length?`<div class="tiny" style="margin-bottom:6px">تابع من آخر ألعابك</div><div class="recentStripV26">${ids.map(id=>{const g=gameBy(id);return `<button class="recentGameV26" onclick="showScreen('${id}')"><span>${g.emoji}</span>${g.name}</button>`}).join('')}</div>`:''}
window.toggleFavoriteV26=function(id){const a=lifetime.favorites||(lifetime.favorites=[]),i=a.indexOf(id);if(i>=0)a.splice(i,1);else a.push(id);saveLife();checkAchievementsV26();decorateGameCardsV26();filterGamesV26()};
window.toggleFavoritesV26=function(){V.favoriteOnly=!V.favoriteOnly;$('favToggleV26')?.classList.toggle('active',V.favoriteOnly);filterGamesV26()};
window.filterGamesV26=function(){const q=clean($('gameSearchV26')?.value||'');$$('#gameGrid .gameCard').forEach(card=>{const id=card.dataset.gameV26||'',text=clean(card.textContent),hideIt=(q&&!text.includes(q))||(V.favoriteOnly&&!lifetime.favorites.includes(id));card.dataset.hiddenV26=hideIt?'1':'0'})};
function decorateGameCardsV26(){$$('#gameGrid .gameCard').forEach(card=>{const play=card.querySelector('button[onclick*="showScreen"]');const m=play?.getAttribute('onclick')?.match(/showScreen\('([^']+)'\)/);if(!m)return;const id=m[1];card.dataset.gameV26=id;let f=card.querySelector('.favoriteV26');if(!f){f=document.createElement('button');f.className='favoriteV26';f.type='button';card.appendChild(f)}f.textContent=lifetime.favorites.includes(id)?'★':'☆';f.onclick=e=>{e.stopPropagation();toggleFavoriteV26(id)}});filterGamesV26()}
function updateHubV26(){const count=(PARTY_CONTENT.trivia?.length||0)+(PARTY_CONTENT.players?.length||0)+(PARTY_CONTENT.fake?.length||0)+(PARTY_CONTENT.sync?.length||0)+(PARTY_CONTENT.scale?.length||0)+(PARTY_CONTENT.taboo?.length||0)+(PARTY_CONTENT.draw?.length||0)+(PARTY_CONTENT.bomb?.length||0)+(PARTY_CONTENT.bowlWords?.length||0)+C.fiveSec.length+C.majority.length+C.order.length+C.emoji.length+C.estimate.length+C.memory.length+C.whisper.length;const e=$('contentCount');if(e)e.textContent=`${count}+ بطاقة ومهمة • ${GAME_DEFS.length} لعبة`}
const grid=$('gameGrid');if(grid)new MutationObserver(()=>{decorateGameCardsV26();updateHubV26()}).observe(grid,{childList:true});

try{if(PARTY_PRESETS.football){['five','emoji','order'].forEach(id=>!PARTY_PRESETS.football.games.includes(id)&&PARTY_PRESETS.football.games.push(id))}if(PARTY_PRESETS.experts){['order','estimate','memory'].forEach(id=>!PARTY_PRESETS.experts.games.includes(id)&&PARTY_PRESETS.experts.games.push(id))}if(PARTY_PRESETS.family){['majority','order','memory','whisper','emoji'].forEach(id=>!PARTY_PRESETS.family.games.includes(id)&&PARTY_PRESETS.family.games.push(id))}if(PARTY_PRESETS.quick){['five','emoji','majority'].forEach(id=>!PARTY_PRESETS.quick.games.includes(id)&&PARTY_PRESETS.quick.games.push(id))}if(PARTY_PRESETS.chaos)PARTY_PRESETS.chaos.games=GAME_DEFS.map(g=>g.id);if(PARTY_PRESETS.cule){['five','emoji','order'].forEach(id=>!PARTY_PRESETS.cule.games.includes(id)&&PARTY_PRESETS.cule.games.push(id))}}catch{}
window.showAbout=function(){$('aboutBody').innerHTML=`<div class="creatorHero"><div class="creatorMark">YN</div><div><div class="eyebrow">CREATOR</div><h2>يزن عبد الحليم</h2><p>لعبة <b>ليلة التحدي</b> من صنع وتطوير يزن عبد الحليم.</p></div></div><div class="aboutFacts"><div><b>${GAME_DEFS.length}</b><span>لعبة جماعية</span></div><div><b>2–10</b><span>لاعبين</span></div><div><b>Offline</b><span>بعد أول تحميل</span></div></div><p class="muted center">سهرة عربية كاملة: تلفون واحد، ألعاب متنوعة، بطولة، سهرة ذكية، إنجازات وتخصيص.</p>`;$('aboutModal').classList.add('open')};
const oldNewNight=window.newNight;window.newNight=function(){const before=state.session.id;oldNewNight();if(state.session.id!==before){state.session.smartNight=null;persist();renderSmartDockV26()}};

try{renderFiltersV22();renderGameGridV22()}catch{try{renderGameGrid()}catch{}}injectHubV26();renderNames();checkAchievementsV26();renderSmartDockV26();
})();
