(()=>{
'use strict';
const C=window.PN_V27_CONTENT;if(!C)return;
const G=[
 {id:'court',emoji:'⚖️',name:'محكمة الأصدقاء',desc:'اتهام طريف + دفاع + تصويت سري',players:'3–10',time:'15–30 د'},
 {id:'pitch',emoji:'🎤',name:'أقنعني',desc:'بيع فكرة مستحيلة خلال 30 ثانية',players:'3–10',time:'10–25 د'},
 {id:'forbidden',emoji:'🚫',name:'الممنوع',desc:'ممنوع سري يلاحقك طول السهرة',players:'3–10',time:'طول السهرة'},
 {id:'mission',emoji:'🕶️',name:'العميل السري',desc:'مهمات سرية تنفذها بدون ما تنكشف',players:'3–10',time:'20–90 د'},
 {id:'chain',emoji:'🔗',name:'السلسلة',desc:'جواب سريع بدون تكرار قبل انتهاء الوقت',players:'2–10',time:'10–25 د'}
];
G.forEach(g=>{if(!GAME_DEFS.some(x=>x.id===g.id))GAME_DEFS.push(g)});
try{Object.assign(GAME_PRESENTATION,{court:{cat:'social',label:'تصويت • ضحك',a:'#6b42dc',b:'#b91e54',glow:'rgba(107,66,220,.2)'},pitch:{cat:'social',label:'إبداع • إقناع',a:'#d26b24',b:'#a8215c',glow:'rgba(210,107,36,.2)'},forbidden:{cat:'social',label:'Meta • طول السهرة',a:'#b52245',b:'#dc8a25',glow:'rgba(181,34,69,.2)'},mission:{cat:'social',label:'سري • مهمات',a:'#244fc0',b:'#6f32b7',glow:'rgba(36,79,192,.2)'},chain:{cat:'quick',label:'سرعة • كلمات',a:'#2779d6',b:'#198a78',glow:'rgba(39,121,214,.2)'}})}catch{}
Object.assign(HELP,{
 court:{title:'⚖️ محكمة الأصدقاء',players:'3–10',goal:'دافع عن نفسك وخلي الأغلبية تبرئك من تهمة سخيفة.',steps:['تختار اللعبة متهمًا وتهمة عشوائية.','المتهم عنده 20 ثانية يدافع عن نفسه.','الهاتف يمر على اللاعبين للتصويت: مذنب أو بريء.','إذا تمت تبرئته يأخذ نقطتين، واللي صوت مع الأغلبية يأخذ نقطة.'],tip:'لا تحولها لنقاش شخصي — الاتهامات كلها طريفة وخيالية.'},
 pitch:{title:'🎤 أقنعني',players:'3–10',goal:'سوّق فكرة غريبة خلال وقت قصير.',steps:['يظهر للاعب منتج أو فكرة مستحيلة.','عنده 30 ثانية يقنع المجموعة بشرائها.','بعد انتهاء الوقت المجموعة تقرر إذا اقتنعت.','إذا نجح يأخذ نقطتين.'],tip:'كل ما كان البيع جديًا لمنتج سخيف، اللعبة تضحك أكثر.'},
 forbidden:{title:'🚫 الممنوع',players:'3–10',goal:'تجنب ممنوعك السري طوال السهرة.',steps:['كل لاعب يرى ممنوعًا خاصًا به بسرية.','تستمروا تلعبوا باقي الألعاب بشكل طبيعي.','إذا أحد خالف ممنوعه، اضغط «انمسك».','آخر السهرة اكشفوا الممنوعات وشوفوا مين نجا.'],tip:'هذه لعبة Meta تشتغل فوق كل الألعاب الثانية.'},
 mission:{title:'🕶️ العميل السري',players:'3–10',goal:'نفّذ مهمتك بدون ما يعرفوا أنك تحاول.',steps:['كل لاعب يستلم مهمة سرية.','ترجعوا للسهرة وتنفذوا المهمات طبيعيًا.','إذا نجحت، علّم مهمتك كمكتملة.','في النهاية تنكشف المهمات؛ المهمة الناجحة = 3 نقاط.'],tip:'لا تستعجل المهمة؛ أفضل اللحظات لما تنفذها بشكل طبيعي.'},
 chain:{title:'🔗 السلسلة',players:'2–10',goal:'قل جوابًا صحيحًا جديدًا قبل انتهاء الوقت.',steps:['تظهر فئة مثل «لاعبون لعبوا لبرشلونة».','كل لاعب عنده ثوانٍ قليلة ليقول جوابًا غير مكرر.','صح = نقطة وانتقال للدور التالي.','إذا علق أو كرر، يأخذ ضربة وتتغير الفئة.'],tip:'5 ثواني للمحنكين، 8 ثواني للعب المريح.'}
});
const V={court:{},pitch:{},forbidden:{},mission:{},chain:{}};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const choose=a=>a[Math.floor(Math.random()*a.length)];const shuffled=a=>{a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
function addScreens(){if(document.getElementById('court'))return;document.querySelector('main')?.insertAdjacentHTML('beforeend',`
<section id="court" class="screen"><div class="nav"><button class="back" onclick="home()">← الرئيسية</button><button class="help" onclick="help('court')">؟ كيف نلعب</button></div><div class="gameHero"><span class="gameIcon">⚖️</span><div><h2>محكمة الأصدقاء</h2><p>دفاع، تصويت، وبراءة أو إدانة 😂</p></div></div><div class="panel"><div class="row compact"><label>الجولات</label><select id="courtRounds"><option>5</option><option selected>8</option><option>12</option></select><label>وقت الدفاع</label><select id="courtTime"><option value="15">15 ث</option><option value="20" selected>20 ث</option><option value="30">30 ث</option></select></div><button class="primary wide" onclick="startCourtV27()">ابدأ المحكمة</button></div><div id="courtStage" class="panel metaGameStage hidden"></div></section>
<section id="pitch" class="screen"><div class="nav"><button class="back" onclick="home()">← الرئيسية</button><button class="help" onclick="help('pitch')">؟ كيف نلعب</button></div><div class="gameHero"><span class="gameIcon">🎤</span><div><h2>أقنعني</h2><p>بيع المستحيل وكأنك أفضل مسوّق بالعالم.</p></div></div><div class="panel"><div class="row compact"><label>الجولات</label><select id="pitchRounds"><option>5</option><option selected>8</option><option>12</option></select><label>الوقت</label><select id="pitchTime"><option value="20">20 ث</option><option value="30" selected>30 ث</option><option value="45">45 ث</option></select></div><button class="primary wide" onclick="startPitchV27()">ابدأ التحدي</button></div><div id="pitchStage" class="panel metaGameStage hidden"></div></section>
<section id="forbidden" class="screen"><div class="nav"><button class="back" onclick="home()">← الرئيسية</button><button class="help" onclick="help('forbidden')">؟ كيف نلعب</button></div><div class="gameHero"><span class="gameIcon">🚫</span><div><h2>الممنوع</h2><p>قانون سري لكل لاعب يظل معه طول السهرة.</p></div></div><div class="panel"><button class="primary wide" onclick="startForbiddenV27()">🎴 توزيع ممنوعات جديدة</button><button class="ghost wide" onclick="showForbiddenBoardV27()">📋 لوحة المتابعة</button></div><div id="forbiddenStage" class="panel metaGameStage hidden"></div></section>
<section id="mission" class="screen"><div class="nav"><button class="back" onclick="home()">← الرئيسية</button><button class="help" onclick="help('mission')">؟ كيف نلعب</button></div><div class="gameHero"><span class="gameIcon">🕶️</span><div><h2>العميل السري</h2><p>نفذ مهمتك وسط السهرة بدون ما ينكشف هدفك.</p></div></div><div class="panel"><button class="primary wide" onclick="startMissionsV27()">🕶️ توزيع مهمات</button><button class="ghost wide" onclick="showMissionBoardV27()">📋 متابعة المهمات</button></div><div id="missionStage" class="panel metaGameStage hidden"></div></section>
<section id="chain" class="screen"><div class="nav"><button class="back" onclick="home()">← الرئيسية</button><button class="help" onclick="help('chain')">؟ كيف نلعب</button></div><div class="gameHero"><span class="gameIcon">🔗</span><div><h2>السلسلة</h2><p>جاوب بسرعة — ممنوع التكرار.</p></div></div><div class="panel"><div class="row compact"><label>الوقت</label><select id="chainTime"><option value="5">5 ث 🔥</option><option value="7" selected>7 ث</option><option value="10">10 ث</option></select></div><button class="primary wide" onclick="startChainV27()">ابدأ سلسلة</button></div><div id="chainStage" class="panel metaGameStage hidden"></div></section>`)}

// Court
window.startCourtV27=function(){if(!requirePlayers(3))return;V.court={round:0,max:+document.getElementById('courtRounds').value||8,votes:[],voter:0};show('courtStage');nextCourtV27()};function show(id){document.getElementById(id)?.classList.remove('hidden')}function set(id,h){const e=document.getElementById(id);if(e)e.innerHTML=h}
window.nextCourtV27=function(){const s=V.court;if(s.round>=s.max){set('courtStage',`<div class="center"><div style="font-size:55px">⚖️</div><h2>انتهت المحكمة</h2><button class="primary" onclick="startCourtV27()">محاكمة جديدة</button></div>`);return}s.round++;s.accused=choose(state.names);s.charge=choose(C.court);s.voters=state.names.filter(n=>n!==s.accused);s.voter=0;s.votes=[];set('courtStage',`<div class="center"><div class="pill">القضية ${s.round}/${s.max}</div><div class="metaPrompt">${esc(s.accused)} متهم بأنه…<br><b>${esc(s.charge)}</b></div><div id="courtTimerV27" class="timer">${+document.getElementById('courtTime').value||20}</div><p class="muted">${esc(s.accused)} يدافع عن نفسه الآن.</p><button class="gold" onclick="startCourtVotingV27()">🗳️ ابدأ التصويت</button></div>`);countdown(document.getElementById('courtTimerV27'),+document.getElementById('courtTime').value||20,()=>toast('انتهى وقت الدفاع'))};
window.startCourtVotingV27=function(){closeTimer();V.court.voter=0;courtVotePass()};function courtVotePass(){const s=V.court;if(s.voter>=s.voters.length)return revealCourt();const n=s.voters[s.voter];set('courtStage',`<div class="privacyCard"><div class="handoffIcon">📱</div><div class="big">سلّم الهاتف لـ ${esc(n)}</div><p class="muted">تصويت سري على ${esc(s.accused)}</p><button class="primary" onclick="courtVoteScreenV27()">أنا ${esc(n)} — صوّت</button></div>`)}
window.courtVoteScreenV27=function(){const s=V.court,n=s.voters[s.voter];set('courtStage',`<div class="center"><div class="metaPrompt">هل ${esc(s.accused)} مذنب؟</div><div class="voteGrid"><button onclick="courtVoteV27('${esc(n)}','guilty')">👨‍⚖️ مذنب</button><button onclick="courtVoteV27('${esc(n)}','innocent')">😇 بريء</button></div></div>`)};window.courtVoteV27=function(n,v){V.court.votes.push({n,v});V.court.voter++;courtVotePass()};function revealCourt(){const s=V.court,g=s.votes.filter(x=>x.v==='guilty').length,i=s.votes.length-g,verdict=g>i?'guilty':i>g?'innocent':'tie';if(verdict==='innocent')addScore(s.accused,2);if(verdict!=='tie')s.votes.filter(x=>x.v===verdict).forEach(x=>addScore(x.n,1));record('court',{verdict});set('courtStage',`<div class="center"><div style="font-size:55px">${verdict==='guilty'?'🔨':verdict==='innocent'?'😇':'🤝'}</div><h2>${verdict==='guilty'?'مذنب!':verdict==='innocent'?'بريء!':'تعادل هيئة المحلفين'}</h2><p>${g} مذنب • ${i} بريء</p><button class="primary" onclick="nextCourtV27()">القضية التالية</button></div>`)}

// Pitch
window.startPitchV27=function(){if(!requirePlayers(3))return;V.pitch={round:0,max:+document.getElementById('pitchRounds').value||8,index:0};show('pitchStage');nextPitchV27()};window.nextPitchV27=function(){const s=V.pitch;if(s.round>=s.max){set('pitchStage','<div class="center"><div style="font-size:55px">🎤</div><h2>انتهت جولات الإقناع</h2><button class="primary" onclick="startPitchV27()">إعادة</button></div>');return}s.round++;s.player=state.names[s.index++%state.names.length];s.prompt=choose(C.pitch);set('pitchStage',`<div class="center"><div class="pill">${esc(s.player)} • ${s.round}/${s.max}</div><div class="metaPrompt">${esc(s.prompt)}</div><div id="pitchTimerV27" class="timer">${+document.getElementById('pitchTime').value||30}</div><button class="gold" onclick="startPitchTimerV27()">🎤 ابدأ الوقت</button></div>`)};window.startPitchTimerV27=function(){const sec=+document.getElementById('pitchTime').value||30;countdown(document.getElementById('pitchTimerV27'),sec,()=>{set('pitchStage',`<div class="center"><h2>هل اقتنعتوا؟</h2><div class="voteGrid"><button onclick="judgePitchV27(true)">👏 اقتنعنا</button><button onclick="judgePitchV27(false)">😂 مستحيل</button></div></div>`)})};window.judgePitchV27=function(ok){if(ok)addScore(V.pitch.player,2);record('pitch',{ok});set('pitchStage',`<div class="center"><div style="font-size:50px">${ok?'👏':'😂'}</div><h2>${ok?'+2 نقاط للمسوّق':'المحاولة الجاية أحسن'}</h2><button class="primary" onclick="nextPitchV27()">التالي</button></div>`)};

// Forbidden meta-game
window.startForbiddenV27=function(){if(!requirePlayers(3))return;const pool=shuffled(C.forbidden);V.forbidden={assign:state.names.map((n,i)=>({n,rule:pool[i%pool.length],caught:false})),i:0,active:true};localStorage.setItem('pn.forbidden.v27',JSON.stringify(V.forbidden));show('forbiddenStage');forbiddenPass()};function forbiddenPass(){const s=V.forbidden;if(s.i>=s.assign.length){set('forbiddenStage',`<div class="center"><div style="font-size:55px">🤫</div><h2>كل واحد عرف ممنوعه</h2><p class="muted">ارجعوا لباقي الألعاب. الممنوع يظل شغال بالخلفية.</p><button class="gold" onclick="home()">رجوع للسهرة</button><button class="ghost" onclick="showForbiddenBoardV27()">لوحة المتابعة</button></div>`);return}const a=s.assign[s.i];set('forbiddenStage',`<div class="privacyCard"><div class="handoffIcon">📱</div><div class="big">الهاتف لـ ${esc(a.n)}</div><button class="primary" onclick="revealForbiddenV27()">اكشف ممنوعي</button></div>`)}window.revealForbiddenV27=function(){const s=V.forbidden,a=s.assign[s.i];set('forbiddenStage',`<div class="missionCard"><div class="tiny">ممنوعك السري</div><div class="secret">${esc(a.rule)}</div><button class="primary" onclick="hideForbiddenNextV27()">حفظت — اخفِ ومرّر</button></div>`)};window.hideForbiddenNextV27=function(){V.forbidden.i++;localStorage.setItem('pn.forbidden.v27',JSON.stringify(V.forbidden));forbiddenPass()};window.showForbiddenBoardV27=function(){try{if(!V.forbidden.active)V.forbidden=JSON.parse(localStorage.getItem('pn.forbidden.v27')||'null')||{}}catch{}if(!V.forbidden?.assign){toast('وزّع الممنوعات أولًا');return}show('forbiddenStage');set('forbiddenStage',`<div class="forbiddenBoard">${V.forbidden.assign.map((a,i)=>`<div class="forbiddenPlayer ${a.caught?'caught':''}"><span>${a.caught?'❌':'🫣'}</span><b>${esc(a.n)}</b><button class="ghost small" onclick="catchForbiddenV27(${i})">${a.caught?'انمسك':'انمسك؟'}</button></div>`).join('')}</div><button class="gold wide" onclick="revealForbiddenAllV27()">👁 كشف الممنوعات</button>`)};window.catchForbiddenV27=function(i){const a=V.forbidden.assign[i];if(a.caught)return;a.caught=true;addStrike(a.n);state.session.scores[a.n]=Math.max(0,(state.session.scores[a.n]||0)-1);persist();localStorage.setItem('pn.forbidden.v27',JSON.stringify(V.forbidden));showForbiddenBoardV27()};window.revealForbiddenAllV27=function(){record('forbidden',{caught:V.forbidden.assign.filter(x=>x.caught).length});set('forbiddenStage',`<div class="forbiddenBoard">${V.forbidden.assign.map(a=>`<div class="forbiddenPlayer"><span>${a.caught?'❌':'🏆'}</span><div><b>${esc(a.n)}</b><small>${esc(a.rule)}</small></div></div>`).join('')}</div>`)};

// Secret Missions
window.startMissionsV27=function(){if(!requirePlayers(3))return;const pool=shuffled(C.missions);V.mission={assign:state.names.map((n,i)=>({n,mission:pool[i%pool.length],done:false})),i:0,active:true};localStorage.setItem('pn.mission.v27',JSON.stringify(V.mission));show('missionStage');missionPass()};function missionPass(){const s=V.mission;if(s.i>=s.assign.length){set('missionStage',`<div class="center"><div style="font-size:55px">🕶️</div><h2>المهمات بدأت</h2><p class="muted">نفذوها خلال باقي السهرة بدون ما تنكشفوا.</p><button class="gold" onclick="home()">رجوع للسهرة</button><button class="ghost" onclick="showMissionBoardV27()">متابعة</button></div>`);return}const a=s.assign[s.i];set('missionStage',`<div class="privacyCard"><div class="handoffIcon">📱</div><div class="big">الهاتف لـ ${esc(a.n)}</div><button class="primary" onclick="revealMissionV27()">اكشف المهمة</button></div>`)}window.revealMissionV27=function(){const a=V.mission.assign[V.mission.i];set('missionStage',`<div class="missionCard"><div class="tiny">مهمتك السرية</div><div class="secret">${esc(a.mission)}</div><button class="primary" onclick="missionNextV27()">حفظت — اخفِ ومرّر</button></div>`)};window.missionNextV27=function(){V.mission.i++;localStorage.setItem('pn.mission.v27',JSON.stringify(V.mission));missionPass()};window.showMissionBoardV27=function(){try{if(!V.mission.active)V.mission=JSON.parse(localStorage.getItem('pn.mission.v27')||'null')||{}}catch{}if(!V.mission?.assign){toast('وزّع المهمات أولًا');return}show('missionStage');set('missionStage',`<p class="muted center">اضغط «تمت» فقط لما صاحب المهمة يعلن نجاحه. المهمة نفسها تظل مخفية.</p><div class="forbiddenBoard">${V.mission.assign.map((a,i)=>`<div class="forbiddenPlayer ${a.done?'caught':''}"><span>${a.done?'✅':'🕶️'}</span><b>${esc(a.n)}</b><button class="ghost small" ${a.done?'disabled':''} onclick="completeMissionV27(${i})">${a.done?'تمت':'تمت؟'}</button></div>`).join('')}</div><button class="gold wide" onclick="revealMissionsAllV27()">👁 نهاية المهمات وكشفها</button>`)};window.completeMissionV27=function(i){const a=V.mission.assign[i];if(a.done)return;a.done=true;addScore(a.n,3);localStorage.setItem('pn.mission.v27',JSON.stringify(V.mission));showMissionBoardV27()};window.revealMissionsAllV27=function(){record('mission',{done:V.mission.assign.filter(x=>x.done).length});set('missionStage',`<div class="forbiddenBoard">${V.mission.assign.map(a=>`<div class="forbiddenPlayer"><span>${a.done?'✅':'❌'}</span><div><b>${esc(a.n)}</b><small>${esc(a.mission)}</small></div></div>`).join('')}</div>`)};

// Chain
window.startChainV27=function(){if(!requirePlayers(2))return;V.chain={cat:choose(C.chains),i:0,answers:[],streak:0};show('chainStage');renderChainTurn()};function renderChainTurn(){const s=V.chain,n=state.names[s.i%state.names.length],sec=+document.getElementById('chainTime').value||7;set('chainStage',`<div class="center"><div class="pill">دور ${esc(n)}</div><div class="chainWord">${esc(s.cat)}</div><div id="chainTimerV27" class="timer">${sec}</div><p class="muted">قول جواب جديد بصوت عالي</p><div class="actions"><button class="primary" onclick="chainGoodV27()">✅ قال جواب</button><button class="danger" onclick="chainFailV27()">💥 علق / كرر</button></div><div class="tiny">السلسلة الحالية: ${s.streak}</div></div>`);countdown(document.getElementById('chainTimerV27'),sec,()=>chainFailV27())}window.chainGoodV27=function(){closeTimer();const s=V.chain,n=state.names[s.i%state.names.length];addScore(n,1);s.streak++;s.i++;record('chain',{ok:true,cat:s.cat});renderChainTurn()};window.chainFailV27=function(){closeTimer();const s=V.chain,n=state.names[s.i%state.names.length];addStrike(n);record('chain',{ok:false,cat:s.cat});s.cat=choose(C.chains.filter(x=>x!==s.cat));s.streak=0;s.i++;toast(`💥 ضربة على ${n}`);renderChainTurn()};

function appendCards(){const grid=document.getElementById('gameGrid');if(!grid)return;G.forEach(g=>{if(grid.querySelector(`[data-pro-game="${g.id}"]`))return;const x=typeof GAME_PRESENTATION!=='undefined'?GAME_PRESENTATION[g.id]:null;const a=document.createElement('article');a.className='gameCard';a.dataset.proGame=g.id;a.style.cssText=`--cardA:${x?.a||'#2f6cff'};--cardB:${x?.b||'#a80c35'};--cardGlow:${x?.glow||'rgba(47,108,255,.18)'}`;a.innerHTML=`<button class="favoriteStar" onclick="toggleProFavoriteV27('${g.id}',this)">☆</button><div class="emoji">${g.emoji}</div><div class="gameCopy"><span class="gameCategory">${x?.label||'PARTY'}</span><h3>${g.name}</h3><p>${g.desc}</p><div class="gameMeta"><span>👥 ${g.players}</span><span>⏱ ${g.time}</span></div></div><div class="cardButtons"><button class="play" onclick="showScreen('${g.id}')">ابدأ اللعب</button><button class="info" onclick="help('${g.id}')">طريقة اللعب</button></div>`;grid.appendChild(a)});const count=document.getElementById('contentCount');if(count)count.textContent=`${GAME_DEFS.length} لعبة • 1000+ بطاقة ومهمة`;const hero=document.querySelector('.matchHeroCopy p');if(hero)hero.textContent=`${GAME_DEFS.length} لعبة، Challenge 30 PRO، مواسم، Profiles، Game Master، TV Mode، باكات ضخمة، ونظام سهرة كامل من تلفون واحد.`}
window.toggleProFavoriteV27=function(id,b){PN_PRO.favorites??=[];const i=PN_PRO.favorites.indexOf(id);if(i>=0)PN_PRO.favorites.splice(i,1);else PN_PRO.favorites.push(id);localStorage.setItem('pn.pro.v27',JSON.stringify(PN_PRO));b.classList.toggle('active');b.textContent=b.classList.contains('active')?'★':'☆'};
try{['court','pitch','forbidden','mission','chain'].forEach(id=>{if(PARTY_PRESETS.chaos&&!PARTY_PRESETS.chaos.games.includes(id))PARTY_PRESETS.chaos.games.push(id)});['court','pitch','forbidden','mission'].forEach(id=>{if(PARTY_PRESETS.family&&!PARTY_PRESETS.family.games.includes(id))PARTY_PRESETS.family.games.push(id)});if(PARTY_PRESETS.quick&&!PARTY_PRESETS.quick.games.includes('chain'))PARTY_PRESETS.quick.games.push('chain')}catch{}
addScreens();appendCards();setTimeout(appendCards,400);window.addEventListener('pageshow',()=>setTimeout(appendCards,100));
})();