(()=>{
'use strict';
if(!document.getElementById('giftV28Style')){const l=document.createElement('link');l.id='giftV28Style';l.rel='stylesheet';l.href='gift-v28.css?v=20260912-gift1';document.head.appendChild(l)}
const C=window.PN_GIFT_CONTENT={
  quotes:[
    'لو فزت بمليون اليوم، أول شيء رح أعمله…','أكثر أكلة ممكن آكلها أسبوع كامل…','لو لازم أعيش بمدينة واحدة طول حياتي…','لاعب كرة قدم أتمنى أقابله…','فيلم أقدر أعيده عشر مرات…','أسوأ عادة عندي وقت السهرة…','لو فتحت مطعم، اسمه رح يكون…','شيء ما بقدر أطلع من البيت بدونه…','أكثر تطبيق بفتحه بدون سبب…','لو صار عندي يوم إجازة كامل بدون مسؤوليات…','أغنية مستحيل أتخطاها إذا اشتغلت…','نادي غير فريقي أقدر أحترمه…','أفضل وجبة بعد منتصف الليل…','لو أقدر أتعلم مهارة فورًا…','أغرب شيء ممكن أشتريه لو صار معي مصاري كثير…','مكان نفسي أسافرله بكرا…','أكثر مسلسل ندمت إني خلصته بسرعة…','شيء الناس بتحبه وأنا مش فاهم ليش…','لو عندي زر يرجعني لسنة معينة…','أفضل لاعب شفته بعيني على الشاشة…','أسوأ نوع رسائل ممكن توصلني…','لو لازم أختار سيارة واحدة عشر سنين…','الشيء اللي دايمًا أنساه…','لو أقدر أحذف اختراع واحد من العالم…','أفضل وقت في اليوم بالنسبة إلي…','لو لازم أعيش بدون قهوة أو بدون حلويات…','أكثر شيء يضحكني بسرعة…','لو كنت مدرب كرة، أول قاعدة بالفريق…','أسوأ عذر للتأخير…','لو لازم آكل من مطعم واحد شهر كامل…'
  ],
  convergence:[
    'شيء بارد','لاعب أسطوري','مدينة للسفر','شيء لونه أحمر','أكلة سريعة','شيء موجود بالسيارة','شيء بالمطبخ','نادي كرة قدم','حيوان سريع','فيلم مشهور','تطبيق هاتف','ماركة سيارة','شيء بالملعب','مشروب صباحي','شيء غالي','شيء يسبب ضحك','شيء نستخدمه بالصيف','شيء موجود بغرفة النوم','لاعب برازيلي','دولة أوروبية','شيء يبدأ بحرف م','شيء نخاف ننساه','هدية مناسبة','شيء يعمل صوتًا عاليًا','وظيفة صعبة','شيء دائري','شيء مرتبط بالبحر','شيء تحطه بالجيب','شيء يحتاج كهرباء','شيء الناس تتنافس عليه'
  ]
};
const GIFT_GAMES=[
 {id:'whoSaid',emoji:'🗣️',name:'مين قالها؟',desc:'إجابات مجهولة — خمّن مين كتبها',players:'3–10',time:'15–30 د'},
 {id:'converge',emoji:'🤝',name:'كلمة مشتركة',desc:'شخصان يحاولان الوصول لنفس الكلمة',players:'2–10',time:'10–25 د'}
];
GIFT_GAMES.forEach(g=>{if(!GAME_DEFS.some(x=>x.id===g.id))GAME_DEFS.push(g)});
try{Object.assign(GAME_PRESENTATION,{whoSaid:{cat:'social',label:'مجهول • تخمين',a:'#7e48d8',b:'#bc2058',glow:'rgba(126,72,216,.2)'},converge:{cat:'mind',label:'تفكير • ثنائي',a:'#1f74c9',b:'#169879',glow:'rgba(31,116,201,.2)'}})}catch{}
Object.assign(HELP,{
 whoSaid:{title:'🗣️ مين قالها؟',players:'3–10',goal:'اكتشف مين صاحب الإجابة المجهولة.',steps:['كل لاعب يكتب جوابًا على نفس السؤال بسرية.','اللعبة تختار جوابًا واحدًا وتعرضه بدون اسم.','باقي اللاعبين يصوتون سرًا على من كتب الجواب.','كل تخمين صحيح = نقطة، وصاحب الجواب يأخذ نقطتين إذا ما حدا كشفه.'],tip:'أفضل الأسئلة تكون شخصية خفيفة بدون إحراج.'},
 converge:{title:'🤝 كلمة مشتركة',players:'2–10',goal:'لاعبان يكتبان نفس الكلمة بدون ما يشوفوا جواب بعض.',steps:['اللعبة تختار لاعبين وموضوعًا.','كل واحد يكتب كلمة بسرية.','إذا تطابقوا، يربحوا نقاط حسب سرعة الوصول.','إذا اختلفوا، الكلمتان تصيران تلميحين لمحاولة جديدة حتى 5 محاولات.'],tip:'لا تختار كلمة غريبة جدًا؛ حاول تفكر كيف الشخص الثاني يفكر.'}
});
const V={who:{},conv:{}};const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const choose=a=>a[Math.floor(Math.random()*a.length)];const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};const clean=s=>String(s||'').trim().toLowerCase().replace(/[أإآ]/g,'ا').replace(/ة/g,'ه').replace(/ى/g,'ي').replace(/\s+/g,' ');
function show(id){document.getElementById(id)?.classList.remove('hidden')}function set(id,h){const e=document.getElementById(id);if(e)e.innerHTML=h}
function addScreens(){if(document.getElementById('whoSaid'))return;document.querySelector('main')?.insertAdjacentHTML('beforeend',`
<section id="whoSaid" class="screen"><div class="nav"><button class="back" onclick="home()">← الرئيسية</button><button class="help" onclick="help('whoSaid')">؟ كيف نلعب</button></div><div class="gameHero"><span class="gameIcon">🗣️</span><div><h2>مين قالها؟</h2><p>كل الأجوبة سرية… بس مين كتب هاي؟</p></div></div><div class="panel"><div class="row compact"><label>الجولات</label><select id="whoRounds"><option>3</option><option selected>5</option><option>8</option></select></div><button class="primary wide" onclick="startWhoSaidV28()">ابدأ المباراة</button></div><div id="whoStage" class="panel metaGameStage hidden"></div></section>
<section id="converge" class="screen"><div class="nav"><button class="back" onclick="home()">← الرئيسية</button><button class="help" onclick="help('converge')">؟ كيف نلعب</button></div><div class="gameHero"><span class="gameIcon">🤝</span><div><h2>كلمة مشتركة</h2><p>فكروا بنفس الطريقة ووصلوا لنفس الكلمة.</p></div></div><div class="panel"><div class="row compact"><label>الجولات</label><select id="convRounds"><option>3</option><option selected>5</option><option>8</option></select></div><button class="primary wide" onclick="startConvergeV28()">ابدأ المباراة</button></div><div id="convStage" class="panel metaGameStage hidden"></div></section>`)}

// Who Said It
window.startWhoSaidV28=function(){if(!requirePlayers(3))return;V.who={round:0,max:+document.getElementById('whoRounds').value||5};show('whoStage');nextWhoRound()};function nextWhoRound(){const s=V.who;if(s.round>=s.max){set('whoStage','<div class="center"><div style="font-size:55px">🗣️</div><h2>انتهت المباراة</h2><button class="primary" onclick="startWhoSaidV28()">إعادة</button></div>');return}s.round++;s.prompt=choose(C.quotes);s.answers=[];s.writer=0;collectWho()}
function collectWho(){const s=V.who;if(s.writer>=state.names.length)return pickWhoTarget();const n=state.names[s.writer];set('whoStage',`<div class="privacyCard"><div class="handoffIcon">📱</div><div class="big">الهاتف لـ ${esc(n)}</div><div class="metaPrompt">${esc(s.prompt)}</div><button class="primary" onclick="whoWriteV28()">أنا ${esc(n)} — اكتب</button></div>`)}
window.whoWriteV28=function(){const s=V.who,n=state.names[s.writer];set('whoStage',`<div class="center"><div class="metaPrompt">${esc(s.prompt)}</div><input id="whoInputV28" class="secretInput" autocomplete="off" placeholder="جوابك السري"><button class="primary wide" onclick="saveWhoAnswerV28('${encodeURIComponent(n)}')">حفظ وإخفاء</button></div>`);setTimeout(()=>document.getElementById('whoInputV28')?.focus(),80)};window.saveWhoAnswerV28=function(enc){const v=document.getElementById('whoInputV28').value.trim();if(!v){toast('اكتب جواب');return}V.who.answers.push({n:decodeURIComponent(enc),v});V.who.writer++;collectWho()};
function pickWhoTarget(){const s=V.who;s.target=choose(s.answers);s.voters=state.names.filter(n=>n!==s.target.n);s.voteIndex=0;s.votes=[];whoVotePass()}
function whoVotePass(){const s=V.who;if(s.voteIndex>=s.voters.length)return revealWho();const n=s.voters[s.voteIndex];set('whoStage',`<div class="privacyCard"><div class="handoffIcon">📱</div><div class="big">صوّت يا ${esc(n)}</div><div class="quoteAnswer">“${esc(s.target.v)}”</div><button class="primary" onclick="whoVoteScreenV28()">مين كتبها؟</button></div>`)}
window.whoVoteScreenV28=function(){const s=V.who,n=s.voters[s.voteIndex];set('whoStage',`<div class="center"><div class="quoteAnswer">“${esc(s.target.v)}”</div><div class="suspectGrid">${state.names.filter(x=>x!==n).map(x=>`<button onclick="whoVoteV28('${encodeURIComponent(n)}','${encodeURIComponent(x)}')">${esc(x)}</button>`).join('')}</div></div>`)};window.whoVoteV28=function(voter,guess){V.who.votes.push({voter:decodeURIComponent(voter),guess:decodeURIComponent(guess)});V.who.voteIndex++;whoVotePass()};function revealWho(){const s=V.who,correct=s.votes.filter(x=>x.guess===s.target.n);correct.forEach(x=>addScore(x.voter,1));if(!correct.length)addScore(s.target.n,2);record('whoSaid',{correct:correct.length});set('whoStage',`<div class="center"><div class="quoteAnswer">“${esc(s.target.v)}”</div><h2>كتبها: ${esc(s.target.n)} 🎭</h2><p>${correct.length?`${correct.length} عرفوا صاحبها`:'ولا واحد عرفه — +2 لصاحب الجواب!'}</p><button class="primary" onclick="nextWhoRoundV28()">الجولة التالية</button></div>`)}window.nextWhoRoundV28=nextWhoRound;

// Convergence
window.startConvergeV28=function(){if(!requirePlayers(2))return;V.conv={round:0,max:+document.getElementById('convRounds').value||5,pairIndex:0};show('convStage');nextConvRound()};function nextConvRound(){const s=V.conv;if(s.round>=s.max){set('convStage','<div class="center"><div style="font-size:55px">🤝</div><h2>خلصت جولات التوافق</h2><button class="primary" onclick="startConvergeV28()">إعادة</button></div>');return}s.round++;s.pair=[state.names[s.pairIndex++%state.names.length],state.names[s.pairIndex++%state.names.length]];if(s.pair[0]===s.pair[1])s.pair[1]=state.names[(s.pairIndex++)%state.names.length];s.anchor=[choose(C.convergence)];s.attempt=1;convInput(0)}
function convInput(i){const s=V.conv;if(i>=2)return convReveal();const n=s.pair[i];set('convStage',`<div class="privacyCard"><div class="handoffIcon">📱</div><div class="big">الهاتف لـ ${esc(n)}</div><div class="tiny">المحاولة ${s.attempt}/5</div><div class="bridgeWords">${s.anchor.map(x=>`<span>${esc(x)}</span>`).join('')}</div><button class="primary" onclick="convWriteV28(${i})">اكتب كلمة سرًا</button></div>`)}window.convWriteV28=function(i){const s=V.conv,n=s.pair[i];set('convStage',`<div class="center"><div class="bridgeWords">${s.anchor.map(x=>`<span>${esc(x)}</span>`).join('')}</div><input id="convInputV28" class="secretInput" autocomplete="off" placeholder="كلمة واحدة"><button class="primary wide" onclick="saveConvV28(${i},'${encodeURIComponent(n)}')">حفظ</button></div>`)};window.saveConvV28=function(i,n){const v=document.getElementById('convInputV28').value.trim();if(!v){toast('اكتب كلمة');return}V.conv.answers??=[];V.conv.answers[i]=v;convInput(i+1)};
function convReveal(){const s=V.conv,a=s.answers[0],b=s.answers[1],match=clean(a)===clean(b);if(match){const pts=Math.max(1,6-s.attempt);s.pair.forEach(n=>addScore(n,pts));record('converge',{attempt:s.attempt});set('convStage',`<div class="center"><div class="convergeSuccess">🤝</div><h2>نفس الكلمة!</h2><div class="bridgeWords"><span>${esc(a)}</span></div><p>+${pts} لكل واحد</p><button class="primary" onclick="nextConvergeV28()">الجولة التالية</button></div>`);return}set('convStage',`<div class="center"><h3>مش نفس الشيء… قربتوا؟</h3><div class="bridgeWords"><span>${esc(a)}</span><span>${esc(b)}</span></div><button class="gold" onclick="continueConvergeV28()">محاولة جديدة من الكلمتين</button></div>`)}window.continueConvergeV28=function(){const s=V.conv;if(s.attempt>=5){record('converge',{attempt:0});set('convStage',`<div class="center"><div style="font-size:50px">😅</div><h2>ما التقيتوا هالمرة</h2><button class="primary" onclick="nextConvergeV28()">جولة جديدة</button></div>`);return}s.anchor=[...s.answers];s.answers=[];s.attempt++;convInput(0)};window.nextConvergeV28=nextConvRound;

// Events Center
const EVENTS={
 champions:{emoji:'🏆',name:'ليلة الأبطال',desc:'دوري الأبطال + محنكين + مباريات معرفة',packs:['ucl','football-expert','barca-expert'],games:['trivia','player','order','emoji','five']},
 clasico:{emoji:'🔵🔴',name:'ليلة الكلاسيكو',desc:'برشلونة × مدريد ومنافسة كروية',packs:['barca','barca-pep','barca-history','barca-expert','madrid'],games:['trivia','player','five','chain']},
 worldcup:{emoji:'🌍',name:'مونديال',desc:'كأس العالم والمنتخبات',packs:['world-cup','football-general','football-expert'],games:['trivia','player','estimate','order']},
 retro:{emoji:'📼',name:'كرة 2000s',desc:'نوستالجيا نجوم وبطولات الألفينات',packs:['football-2000s','ucl','barca-history'],games:['trivia','player','whoSaid','chain']},
 ramadan:{emoji:'🌙',name:'سهرة رمضانية',desc:'دين، منوعات وألعاب اجتماعية عائلية',packs:['religion','general','geography'],games:['trivia','sync','majority','converge','draw']},
 summer:{emoji:'☀️',name:'خلطة الصيف',desc:'ضحك، سرعة، رسم وتحديات خفيفة',packs:['general','movies','tech'],games:['five','bomb','draw','pitch','whoSaid','whisper']}
};
function activeEvent(){return state.settings.eventV28&&EVENTS[state.settings.eventV28]}
window.showEventsV28=function(){const active=state.settings.eventV28;openGiftModal('eventsV28','🎪 Events Center',`<div class="eventGrid">${Object.entries(EVENTS).map(([id,e])=>`<div class="eventCard ${active===id?'active':''}"><div class="eventEmoji">${e.emoji}</div><h4>${e.name}</h4><p>${e.desc}</p><button onclick="activateEventV28('${id}')">${active===id?'مفعّل ✓':'تفعيل'}</button></div>`).join('')}</div>${active?'<button class="ghost wide" onclick="clearEventV28()">إلغاء الحدث والرجوع للوضع العادي</button>':''}`)};
window.activateEventV28=function(id){const e=EVENTS[id];if(!e)return;state.settings.eventV28=id;state.settings.mixPool=[...e.games];persist();try{document.querySelectorAll('#triviaPacks .packBtn').forEach(b=>b.classList.toggle('selected',e.packs.includes(b.dataset.pack)));const d=document.getElementById('triviaDifficulty');if(d)d.value=id==='clasico'?'hard':'medium'}catch{}closeGift('eventsV28');renderEventBanner();toast(`${e.emoji} تم تفعيل ${e.name}`)};window.clearEventV28=function(){delete state.settings.eventV28;state.settings.mixPool=null;persist();closeGift('eventsV28');renderEventBanner();toast('تم إلغاء الحدث')};
function renderEventBanner(){let b=document.getElementById('eventBannerV28'),e=activeEvent();if(!e){b?.remove();return}if(!b){b=document.createElement('div');b.id='eventBannerV28';b.className='eventBanner';document.getElementById('seasonCardV27')?.after(b)}if(b)b.innerHTML=`<span>${e.emoji}</span><div><b>${e.name}</b><small>${e.desc}</small></div><button class="ghost small" onclick="showEventsV28()">تغيير</button>`}

// Cosmetics / Locker
const THEMES={blau:{name:'Blaugrana Night',sw:'linear-gradient(90deg,#163fa6,#a80c35,#f4c96b)',need:0},midnight:{name:'Midnight Purple',sw:'linear-gradient(90deg,#3947a8,#6e2d86,#8ed5ff)',need:80},emerald:{name:'Emerald Arena',sw:'linear-gradient(90deg,#087c79,#11614c,#b9f38b)',need:180},royal:{name:'Royal Night',sw:'linear-gradient(90deg,#342b8f,#7d1d66,#ffe08b)',need:300},sunset:{name:'Sunset Cup',sw:'linear-gradient(90deg,#c34c32,#932f62,#ffd27a)',need:500}};
const FRAMES={none:{name:'بدون إطار',need:0},silver:{name:'Silver',need:100},gold:{name:'Gold Champion',need:250},neon:{name:'Neon',need:450}};
function cosmetics(){PN_PRO.cosmetics??={theme:'blau',frame:'none',sound:'stadium'};return PN_PRO.cosmetics}function totalXP(){return Object.values(PN_PRO.profiles||{}).reduce((a,p)=>a+(p.xp||0),0)+(PN_PRO.seasonXP||0)}
function applyCosmetics(){const c=cosmetics();document.documentElement.dataset.pnTheme=c.theme==='blau'?'':c.theme;document.documentElement.classList.remove('frame-silver','frame-gold','frame-neon');if(c.frame!=='none')document.documentElement.classList.add(`frame-${c.frame}`)}
window.showLockerV28=function(){const c=cosmetics(),xp=totalXP();openGiftModal('lockerV28','🎁 Locker',`<div class="lockerHero"><div class="lockerPreview">👑</div><h3>${xp} Cosmetic XP</h3><p class="muted">كل اللعب والإنجازات تفتح خيارات شكلية فقط — بدون أي أفضلية باللعب.</p></div><h3>🎨 الثيمات</h3><div class="cosmeticGrid">${Object.entries(THEMES).map(([id,t])=>`<button class="cosmeticCard ${xp<t.need?'locked':''} ${c.theme===id?'selected':''}" ${xp<t.need?'disabled':''} onclick="selectCosmeticV28('theme','${id}')"><div class="themeSwatch" style="--sw:${t.sw}"></div><b>${t.name}</b><small>${t.need?`يفتح عند ${t.need} XP`:'الافتراضي'}</small></button>`).join('')}</div><h3>🖼️ إطارات اللاعبين</h3><div class="cosmeticGrid">${Object.entries(FRAMES).map(([id,t])=>`<button class="cosmeticCard ${xp<t.need?'locked':''} ${c.frame===id?'selected':''}" ${xp<t.need?'disabled':''} onclick="selectCosmeticV28('frame','${id}')"><b>${id==='gold'?'🏆':id==='neon'?'✨':id==='silver'?'🥈':'◯'} ${t.name}</b><small>${t.need?`يفتح عند ${t.need} XP`:'مفتوح'}</small></button>`).join('')}</div><h3>🔊 صوت الاحتفال</h3><div class="chips">${['stadium','arcade','classic'].map(s=>`<button class="chip ${c.sound===s?'selected':''}" onclick="selectCosmeticV28('sound','${s}')">${s==='stadium'?'🏟️ Stadium':s==='arcade'?'🕹️ Arcade':'🎵 Classic'}</button>`).join('')}</div>`)};
window.selectCosmeticV28=function(k,v){const c=cosmetics(),xp=totalXP(),def=k==='theme'?THEMES[v]:k==='frame'?FRAMES[v]:null;if(def&&xp<def.need){toast('لسا مقفول');return}c[k]=v;localStorage.setItem('pn.pro.v27',JSON.stringify(PN_PRO));applyCosmetics();showLockerV28();if(k==='sound')playGiftSoundV28()};window.playGiftSoundV28=function(){const s=cosmetics().sound;try{if(s==='stadium'){beep(520,.08);setTimeout(()=>beep(660,.08),90);setTimeout(()=>beep(820,.14),180)}else if(s==='arcade'){beep(880,.05);setTimeout(()=>beep(1180,.06),70);setTimeout(()=>beep(1500,.08),140)}else{beep(660,.1);setTimeout(()=>beep(880,.15),120)}}catch{}};
const oldChamp=window.champAward;if(oldChamp)window.champAward=function(n){oldChamp(n);if(state.session.championship?.complete)playGiftSoundV28()};

// Extra content filters
window.showExtraFiltersV28=function(){const v=state.settings.extraFilterV28||'all';openGiftModal('filtersV28','🧹 فلاتر السهرة',`<div class="filterChoiceGrid">${[['all','🌍 الكل'],['noFootball','🚫⚽ بدون كرة'],['noPersonal','🛡️ بدون ألعاب شخصية'],['familySafe','👨‍👩‍👧 عائلي هادئ']].map(([id,n])=>`<button class="${v===id?'active':''}" onclick="setExtraFilterV28('${id}')">${n}</button>`).join('')}</div><p class="muted">الفلتر يغيّر المكتبة والاختيار العشوائي فقط؛ تقدر ترجع «الكل» بأي وقت.</p>`)};
window.setExtraFilterV28=function(v){state.settings.extraFilterV28=v;persist();closeGift('filtersV28');applyExtraFilter();toast('تم تحديث فلتر السهرة')};function applyExtraFilter(){const v=state.settings.extraFilterV28||'all',football=new Set(['trivia','player']),personal=new Set(['fake','court','mission','whoSaid']),familyBlock=new Set(['court','mission','forbidden']);document.querySelectorAll('#gameGrid .gameCard').forEach(card=>{const id=card.dataset.proGame||card.querySelector('.play')?.getAttribute('onclick')?.match(/showScreen\('([^']+)'/)?.[1];let hide=false;if(v==='noFootball')hide=football.has(id);if(v==='noPersonal')hide=personal.has(id);if(v==='familySafe')hide=familyBlock.has(id);card.style.display=hide?'none':''});if(v==='noFootball')document.querySelectorAll('#triviaPacks .packBtn').forEach(b=>{if(/football|ucl|world-cup|barca|madrid|premier/.test(b.dataset.pack||''))b.classList.remove('selected')})}

function openGiftModal(id,title,html){let m=document.getElementById(id);if(!m){m=document.createElement('div');m.id=id;m.className='modal';m.onclick=e=>{if(e.target===m)m.classList.remove('open')};m.innerHTML=`<div class="modalCard"><div class="nav"><div class="big">${title}</div><button class="ghost" onclick="document.getElementById('${id}').classList.remove('open')">إغلاق</button></div><div class="giftBody"></div></div>`;document.body.appendChild(m)}m.querySelector('.giftBody').innerHTML=html;m.classList.add('open');return m}function closeGift(id){document.getElementById(id)?.classList.remove('open')}

function addGiftHub(){const h=document.getElementById('home');if(!h)return;let r=document.getElementById('giftHubRowV28');if(!r){r=document.createElement('div');r.id='giftHubRowV28';r.className='giftHubRow';r.innerHTML=`<button onclick="showEventsV28()"><span>🎪</span><b>Events</b></button><button onclick="showLockerV28()"><span>🎁</span><b>Locker</b></button><button onclick="showExtraFiltersV28()"><span>🧹</span><b>فلاتر</b></button>`;document.getElementById('proCommandBarV27')?.after(r)}renderEventBanner();applyCosmetics();applyExtraFilter()}
function appendCards(){const grid=document.getElementById('gameGrid');if(!grid)return;GIFT_GAMES.forEach(g=>{if(grid.querySelector(`[data-pro-game="${g.id}"]`))return;const x=typeof GAME_PRESENTATION!=='undefined'?GAME_PRESENTATION[g.id]:null,a=document.createElement('article');a.className='gameCard';a.dataset.proGame=g.id;a.style.cssText=`--cardA:${x?.a||'#2f6cff'};--cardB:${x?.b||'#a80c35'};--cardGlow:${x?.glow||'rgba(47,108,255,.18)'}`;a.innerHTML=`<button class="favoriteStar" onclick="toggleProFavoriteV27?.('${g.id}',this)">☆</button><div class="emoji">${g.emoji}</div><div class="gameCopy"><span class="gameCategory">${x?.label||'PARTY'}</span><h3>${g.name}</h3><p>${g.desc}</p><div class="gameMeta"><span>👥 ${g.players}</span><span>⏱ ${g.time}</span></div></div><div class="cardButtons"><button class="play" onclick="showScreen('${g.id}')">ابدأ اللعب</button><button class="info" onclick="help('${g.id}')">طريقة اللعب</button></div>`;grid.appendChild(a)});const c=document.getElementById('contentCount');if(c)c.textContent=`${GAME_DEFS.length} لعبة • 1000+ بطاقة ومهمة`;applyExtraFilter()}
try{['whoSaid','converge'].forEach(id=>{if(PARTY_PRESETS.chaos&&!PARTY_PRESETS.chaos.games.includes(id))PARTY_PRESETS.chaos.games.push(id)});['whoSaid','converge'].forEach(id=>{if(PARTY_PRESETS.family&&!PARTY_PRESETS.family.games.includes(id))PARTY_PRESETS.family.games.push(id)})}catch{}
addScreens();appendCards();addGiftHub();setTimeout(()=>{appendCards();addGiftHub()},500);window.addEventListener('pageshow',()=>setTimeout(()=>{appendCards();addGiftHub()},100));
})();