(()=>{
'use strict';
if(typeof GAME_DEFS==='undefined'||typeof state==='undefined')return;
const K='pn.partyos.v30';
const O=window.PN_PARTY_OS=(()=>{try{return {playlists:[],queue:[],queueIndex:0,pulse:{energy:'normal',mood:'balanced',noise:'normal'},filters:{family:false,noPersonal:false,noFootball:false,footballOnly:false},surprises:0,...JSON.parse(localStorage.getItem(K)||'{}')}}catch{return {playlists:[],queue:[],queueIndex:0,pulse:{energy:'normal',mood:'balanced',noise:'normal'},filters:{family:false,noPersonal:false,noFootball:false,footballOnly:false},surprises:0}}})();
const save=()=>localStorage.setItem(K,JSON.stringify(O));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const choose=a=>a[Math.floor(Math.random()*a.length)];
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const minPlayers=g=>parseInt(String(g.players||'2').match(/\d+/)?.[0]||2,10);
const game=id=>GAME_DEFS.find(g=>g.id===id);
const gp=id=>{try{return typeof GAME_PRESENTATION!=='undefined'?GAME_PRESENTATION[id]:null}catch{return null}};
const cat=id=>gp(id)?.cat||({trivia:'mind',player:'football',fake:'social',sync:'social',scale:'mind',taboo:'team',draw:'creative',bowl:'team',bomb:'quick',five:'quick',majority:'social',order:'mind',emoji:'quick',estimate:'mind',memory:'mind',whisper:'social',court:'social',pitch:'creative',forbidden:'social',mission:'social',chain:'quick',whoSaid:'social',converge:'mind'}[id]||'social');
const FOOTBALL=new Set(['trivia','player']);
const PERSONAL=new Set(['whoSaid','court','fake','majority']);
function modal(id,title){let m=document.getElementById(id);if(!m){m=document.createElement('div');m.id=id;m.className='modal partyOSModal';m.onclick=e=>{if(e.target===m)m.classList.remove('open')};m.innerHTML=`<div class="modalCard"><div class="nav"><div class="big">${title}</div><button class="ghost" onclick="document.getElementById('${id}').classList.remove('open')">إغلاق</button></div><div class="partyOSBody"></div></div>`;document.body.appendChild(m)}return m}
function openModal(id,title,html){const m=modal(id,title);m.querySelector('.partyOSBody').innerHTML=html;m.classList.add('open');return m}
function playerCount(){return state.names.length||Number(localStorage.getItem('pn.guestCount')||0)||4}
function eligible(){const n=playerCount();return GAME_DEFS.filter(g=>minPlayers(g)<=n).filter(g=>!O.filters.noPersonal||!PERSONAL.has(g.id)).filter(g=>!O.filters.noFootball||!FOOTBALL.has(g.id)).filter(g=>!O.filters.footballOnly||FOOTBALL.has(g.id))}
function recentIds(){return (state.session?.events||[]).slice(-14).map(e=>e.game).filter(Boolean)}
function scoreGame(g,opts={}){let s=0;const c=cat(g.id),recent=recentIds();const played=state.session?.games?.[g.id]||0;if(!recent.includes(g.id))s+=8;else s-=recent.lastIndexOf(g.id)>=Math.max(0,recent.length-4)?9:2;if(!played)s+=5;s-=Math.min(played,5);if(opts.vibe==='social'&&['social','creative','team'].includes(c))s+=8;if(opts.vibe==='brain'&&c==='mind')s+=9;if(opts.vibe==='quick'&&c==='quick')s+=10;if(opts.vibe==='competitive'&&['mind','team','quick','football'].includes(c))s+=6;if(opts.vibe==='football'&&FOOTBALL.has(g.id))s+=14;if(opts.vibe==='family'&&!PERSONAL.has(g.id))s+=6;if(O.pulse.energy==='high'&&['quick','team','social'].includes(c))s+=4;if(O.pulse.energy==='low'&&['mind','social'].includes(c))s+=3;if(opts.avoidCat&&c===opts.avoidCat)s-=7;return s+Math.random()*3}
function buildQueue({minutes=60,vibe='balanced',length=0}={}){let pool=eligible();if(!pool.length)return[];const count=length||Math.max(3,Math.min(10,Math.round(minutes/12)));const q=[];let lastCat='';for(let i=0;i<count;i++){let candidates=pool.filter(g=>!q.includes(g.id));if(!candidates.length)candidates=pool;const ranked=candidates.map(g=>({g,s:scoreGame(g,{vibe,avoidCat:lastCat})})).sort((a,b)=>b.s-a.s);const pick=ranked.slice(0,Math.min(5,ranked.length))[Math.floor(Math.random()*Math.min(3,ranked.length))]?.g||ranked[0]?.g;if(!pick)break;q.push(pick.id);lastCat=cat(pick.id)}return q}
function queueCard(id,i){const g=game(id);if(!g)return'';const phase=i===0?'افتتاح':i===O.queue.length-1?'نهائي':'وسط السهرة';return `<div class="partyQueueItem ${i===O.queueIndex?'current':''}"><span class="partyQueueNum">${i+1}</span><span class="partyQueueEmoji">${g.emoji}</span><div><b>${esc(g.name)}</b><small>${phase} • ${esc(g.time||'')}</small></div>${i<O.queueIndex?'<span>✓</span>':''}</div>`}
function renderQueueBar(){let b=document.getElementById('partyQueueBarV30');if(!O.queue.length){b?.remove();return}if(!b){b=document.createElement('div');b.id='partyQueueBarV30';b.className='partyQueueBarV30';document.body.appendChild(b)}const cur=game(O.queue[O.queueIndex]),next=game(O.queue[O.queueIndex+1]);b.innerHTML=`<button onclick="showPartyQueueV30()"><span>🎛️</span><b>${O.queueIndex+1}/${O.queue.length}</b><small>${cur?esc(cur.name):'السهرة'}</small></button>${next?`<button class="queueNextV30" onclick="nextPartyGameV30()"><span>التالي</span><b>${next.emoji} ${esc(next.name)}</b></button>`:`<button class="queueNextV30" onclick="showPartyAwardsV30()"><span>النهاية</span><b>🏆 الجوائز</b></button>`}`}
window.showPartyQueueV30=function(){openModal('partyQueueV30','🎛️ مسار السهرة',`<div class="partyQueueList">${O.queue.map(queueCard).join('')}</div><div class="actions wrap"><button class="primary" onclick="nextPartyGameV30()">اللعبة التالية</button><button class="ghost" onclick="showIntermissionV30()">☕ استراحة</button><button class="ghost" onclick="saveCurrentPlaylistV30()">💾 حفظ المسار</button><button class="danger" onclick="clearPartyQueueV30()">إنهاء المسار</button></div>`)};
window.clearPartyQueueV30=function(){O.queue=[];O.queueIndex=0;save();renderQueueBar();document.getElementById('partyQueueV30')?.classList.remove('open');toast('تم إنهاء مسار السهرة')};
window.nextPartyGameV30=function(){if(!O.queue.length)return showPartyDirectorV30();if(O.queueIndex<O.queue.length-1)O.queueIndex++;save();renderQueueBar();const id=O.queue[O.queueIndex];document.querySelectorAll('.modal.open').forEach(m=>m.classList.remove('open'));window.showScreen?.(id)};
window.startPartyQueueV30=function(){if(!O.queue.length)return;O.queueIndex=0;save();renderQueueBar();document.querySelectorAll('.modal.open').forEach(m=>m.classList.remove('open'));window.showScreen?.(O.queue[0])};
window.showPartyDirectorV30=function(){openModal('partyDirectorV30','✨ Party Director',`<div class="partyDirectorHero"><span>خلّينا نرتب السهرة</span><h2>أنت اختار الجو… وإحنا نختار الألعاب.</h2></div><div class="directorGridV30"><label>⏱️ الوقت<select id="pdMinutes"><option value="30">30 دقيقة</option><option value="45">45 دقيقة</option><option value="60" selected>ساعة</option><option value="90">90 دقيقة</option><option value="120">ساعتين</option></select></label><label>🎭 المود<select id="pdVibe"><option value="balanced">متوازن</option><option value="social">ضحك واجتماعي</option><option value="competitive">تنافسي</option><option value="brain">ذكاء ومعرفة</option><option value="quick">سريع وفوضوي</option><option value="football">كروي</option><option value="family">عائلي</option></select></label><label>⚡ الطاقة<select id="pdEnergy"><option value="low">هادية</option><option value="normal" selected>طبيعية</option><option value="high">عالآخر 🔥</option></select></label><label>👥 اللاعبين<select id="pdPlayers">${[2,3,4,5,6,7,8,9,10].map(n=>`<option ${n===playerCount()?'selected':''}>${n}</option>`).join('')}</select></label></div><div class="filterTogglesV30"><label><input id="pdFamily" type="checkbox"> عائلي وبدون أسئلة شخصية</label><label><input id="pdNoFootball" type="checkbox"> بدون كرة</label><label><input id="pdFootballOnly" type="checkbox"> كرة فقط</label></div><button class="gold wide hugeBtn" onclick="buildPartyDirectorV30()">✨ ابنِ السهرة</button><div id="partyDirectorPreviewV30"></div>`)};
window.buildPartyDirectorV30=function(){const minutes=+document.getElementById('pdMinutes').value,vibe=document.getElementById('pdVibe').value,energy=document.getElementById('pdEnergy').value,n=+document.getElementById('pdPlayers').value;localStorage.setItem('pn.guestCount',n);O.pulse.energy=energy;O.pulse.mood=vibe;O.filters.family=document.getElementById('pdFamily').checked;O.filters.noPersonal=O.filters.family;O.filters.noFootball=document.getElementById('pdNoFootball').checked;O.filters.footballOnly=document.getElementById('pdFootballOnly').checked;if(O.filters.footballOnly)O.filters.noFootball=false;O.queue=buildQueue({minutes,vibe});O.queueIndex=0;save();const p=document.getElementById('partyDirectorPreviewV30');if(p)p.innerHTML=`<div class="directorPreviewV30"><div class="sectionHead"><div><b>مسار مقترح</b><small>${minutes} دقيقة • ${O.queue.length} ألعاب</small></div><button class="ghost small" onclick="buildPartyDirectorV30()">🔄 غيرها</button></div>${O.queue.map(queueCard).join('')}<div class="actions"><button class="primary hugeBtn" onclick="startPartyQueueV30()">ابدأ السهرة الآن</button><button class="ghost" onclick="saveCurrentPlaylistV30()">💾 حفظ</button></div></div>`;renderQueueBar()};
window.instantPartyV30=function(){const vibe=choose(['balanced','social','competitive','quick']);O.queue=buildQueue({minutes:45,vibe,length:4});O.queueIndex=0;save();renderQueueBar();if(!O.queue.length){toast('أضف لاعبين أو غيّر الفلاتر');return}toast('⚡ جهزت لك سهرة فورية');setTimeout(()=>window.showScreen?.(O.queue[0]),350)};
window.showNextBestV30=function(){const opts=eligible().map(g=>({g,s:scoreGame(g,{vibe:O.pulse.mood||'balanced',avoidCat:cat(recentIds().slice(-1)[0])})})).sort((a,b)=>b.s-a.s).slice(0,4);openModal('nextBestV30','🎯 شو نلعب هسا؟',`<p class="muted">حسب عددكم، الألعاب اللي لعبتوها، وطاقة السهرة.</p><div class="nextBestGridV30">${opts.map(({g},i)=>`<button onclick="document.getElementById('nextBestV30').classList.remove('open');showScreen('${g.id}')"><span>${g.emoji}</span><b>${esc(g.name)}</b><small>${i===0?'أفضل اختيار الآن':'بديل قوي'} • ${esc(g.time||'')}</small></button>`).join('')}</div>`)};
window.surpriseRouletteV30=function(){const pool=eligible();if(!pool.length)return;const m=openModal('rouletteV30','🎲 مفاجأة السهرة','<div class="rouletteV30"><div id="rouletteEmojiV30">🎲</div><h2 id="rouletteNameV30">نلف العجلة...</h2></div>');let i=0;const t=setInterval(()=>{const g=choose(pool);const em=document.getElementById('rouletteEmojiV30'),nm=document.getElementById('rouletteNameV30');if(em)em.textContent=g.emoji;if(nm)nm.textContent=g.name;try{buzz?.(18)}catch{};if(++i>=13){clearInterval(t);const final=choose(pool);em.textContent=final.emoji;nm.textContent=final.name;m.querySelector('.partyOSBody').insertAdjacentHTML('beforeend',`<button class="gold wide hugeBtn" onclick="document.getElementById('rouletteV30').classList.remove('open');showScreen('${final.id}')">ابدأ ${esc(final.name)}</button>`);O.surprises++;save()}},95)};
const BREAKS=[
'كل واحد يختار بإصبعه الشخص الأكثر احتمالًا يفوز باللعبة الجاية.','20 ثانية: ممنوع أي حدا يحكي كلمة «لا». أول واحد يغلط عليه تحدي.','بدّلوا أماكن الجلوس بسرعة خلال 15 ثانية.','كل شخص يقول كلمة واحدة تصف السهرة لحد الآن.','صاحب أقل نقاط يختار اللعبة التالية.','صاحب أعلى نقاط يعطي تحدي خفيف لأي لاعب.','كل واحد يتوقع مين رح يكون MVP بنهاية السهرة.','جولة تصفيق: اختاروا أفضل لقطة صارت اليوم.','30 ثانية استراحة ماء — ورجعوا أقوى 💧','كل واحد يحكي حقيقة غريبة يعرفها خلال 10 ثواني.','اختاروا لاعب يعمل تعليق رياضي لأول دقيقة من اللعبة الجاية.','الشخص اللي هاتفه أقل بطارية يختار المود القادم 😂','كل لاعب يعطي اللاعب اللي على يمينه لقب للسهرة.','اتفقوا على كلمة ممنوعة للـ10 دقائق الجاية.','صوتوا بسرعة: نكمل ذكاء 🧠 ولا فوضى 🔥؟','كل واحد يذكر لعبة كانت المفضلة عنده وهو صغير.','صاحب آخر نقطة مكتسبة يبدأ اللعبة التالية.','15 ثانية صمت كامل… أول واحد يضحك خسر التحدي.','اختاروا Captain للجولة القادمة.','كل شخص يعمل توقع نتيجة اللعبة القادمة.'
];
window.showIntermissionV30=function(){const text=choose(BREAKS);openModal('intermissionV30','☕ استراحة بين الألعاب',`<div class="intermissionV30"><span>⚡</span><h2>${esc(text)}</h2><div class="actions"><button class="primary" onclick="showIntermissionV30()">تحدي ثاني</button><button class="ghost" onclick="startBreakTimerV30(60)">⏱️ دقيقة راحة</button><button class="gold" onclick="document.getElementById('intermissionV30').classList.remove('open');showNextBestV30()">اختار اللعبة التالية</button></div></div>`);try{state.session.events.push({t:Date.now(),game:'intermission',detail:text});persist()}catch{}};
window.startBreakTimerV30=function(sec=60){let left=sec;const body=document.querySelector('#intermissionV30 .partyOSBody');if(!body)return;const tick=()=>{body.innerHTML=`<div class="breakTimerV30"><div>☕</div><b>${Math.floor(left/60)}:${String(left%60).padStart(2,'0')}</b><small>السهرة راجعة بعد شوي</small><button class="ghost" onclick="clearInterval(window._pnBreakTimer);showNextBestV30()">إنهاء الاستراحة</button></div>`;if(left--<=0){clearInterval(window._pnBreakTimer);try{beep?.(880,.12)}catch{};showNextBestV30()}};clearInterval(window._pnBreakTimer);tick();window._pnBreakTimer=setInterval(tick,1000)};
window.showPartyPulseV30=function(){openModal('pulseV30','💓 Party Pulse',`<p class="muted">خبر التطبيق كيف الجو هسا، عشان اقتراح اللعبة التالية يصير أذكى.</p><h3>⚡ الطاقة</h3><div class="pulseChoicesV30">${[['low','😌 هادية'],['normal','🙂 طبيعية'],['high','🔥 مولعة']].map(([v,l])=>`<button class="${O.pulse.energy===v?'active':''}" onclick="setPartyPulseV30('energy','${v}')">${l}</button>`).join('')}</div><h3>🎭 بدكم إيش؟</h3><div class="pulseChoicesV30">${[['balanced','🎲 خلطة'],['social','😂 ضحك'],['brain','🧠 تفكير'],['quick','⚡ سريع'],['competitive','🏆 تنافس'],['football','⚽ كرة']].map(([v,l])=>`<button class="${O.pulse.mood===v?'active':''}" onclick="setPartyPulseV30('mood','${v}')">${l}</button>`).join('')}</div><button class="gold wide" onclick="document.getElementById('pulseV30').classList.remove('open');showNextBestV30()">اقترح اللعبة التالية</button>`)};
window.setPartyPulseV30=function(k,v){O.pulse[k]=v;save();showPartyPulseV30()};
function profileScore(n){try{return window.PN_PRO?.profiles?.[n]?.score||state.session?.scores?.[n]||0}catch{return state.session?.scores?.[n]||0}}
window.showTeamBalancerV30=function(){if(state.names.length<4){toast('بدنا 4 لاعبين على الأقل');return}const sorted=[...state.names].sort((a,b)=>profileScore(b)-profileScore(a));const A=[],B=[];sorted.forEach((n,i)=>(i%4<2?A:B).push(n));openModal('teamsV30','⚖️ تقسيم فرق متوازن',`<p class="muted">التقسيم يعتمد على النقاط/التاريخ قدر الإمكان، وبعدين يوزع الأقوى بين الفريقين.</p><div class="balancedTeamsV30"><div><h3>🔵 الفريق A</h3>${A.map(n=>`<span>${esc(n)} <small>${profileScore(n)} pts</small></span>`).join('')}</div><div><h3>🔴 الفريق B</h3>${B.map(n=>`<span>${esc(n)} <small>${profileScore(n)} pts</small></span>`).join('')}</div></div><div class="actions"><button class="primary" onclick='applyTeamsV30(${JSON.stringify(A)},${JSON.stringify(B)})'>استخدم الفرق</button><button class="ghost" onclick="randomTeamsV30()">🎲 عشوائي</button></div>`)};
window.applyTeamsV30=function(A,B){const a=document.getElementById('teamA'),b=document.getElementById('teamB');if(a)a.value=A.join(' + ');if(b)b.value=B.join(' + ');localStorage.setItem('pn.teamA',JSON.stringify(A));localStorage.setItem('pn.teamB',JSON.stringify(B));toast('✅ تم حفظ الفرق');document.getElementById('teamsV30')?.classList.remove('open')};
window.randomTeamsV30=function(){const s=shuffle(state.names),m=Math.ceil(s.length/2);openModal('teamsV30','🎲 فرق عشوائية',`<div class="balancedTeamsV30"><div><h3>🔵 الفريق A</h3>${s.slice(0,m).map(n=>`<span>${esc(n)}</span>`).join('')}</div><div><h3>🔴 الفريق B</h3>${s.slice(m).map(n=>`<span>${esc(n)}</span>`).join('')}</div></div><button class="primary wide" onclick='applyTeamsV30(${JSON.stringify(s.slice(0,m))},${JSON.stringify(s.slice(m))})'>استخدم الفرق</button>`)};
window.spotlightPlayerV30=function(){if(!state.names.length){toast('أضف أسماء اللاعبين');return}const m=openModal('spotlightV30','🎯 مين عليه الدور؟','<div class="spotlightV30"><span>🎯</span><h2 id="spotNameV30">...</h2></div>');let i=0;const t=setInterval(()=>{document.getElementById('spotNameV30').textContent=choose(state.names);try{buzz?.(12)}catch{};if(++i>12){clearInterval(t);const n=choose(state.names);document.getElementById('spotNameV30').textContent=n;m.querySelector('.partyOSBody').insertAdjacentHTML('beforeend',`<p class="center muted">${esc(n)} يبدأ التحدي الجاي 😄</p>`) }},80)};
function tone(freq,d=.08){try{beep?.(freq,d)}catch{}}
window.partySoundV30=function(kind){if(kind==='correct'){tone(740,.05);setTimeout(()=>tone(980,.08),70)}if(kind==='wrong'){tone(190,.18)}if(kind==='whistle'){tone(1200,.05);setTimeout(()=>tone(900,.05),70)}if(kind==='drum'){[180,220,260,320].forEach((f,i)=>setTimeout(()=>tone(f,.08),i*100))}if(kind==='win'){[523,659,784,1046].forEach((f,i)=>setTimeout(()=>tone(f,.1),i*90))}try{buzz?.(kind==='wrong'?120:35)}catch{}};
window.showHostDeckV30=function(){const mins=Math.max(1,Math.round((Date.now()-(state.session?.startedAt||Date.now()))/60000));openModal('hostDeckV30','🎛️ Host Deck',`<div class="hostStatsV30"><div><b>${playerCount()}</b><small>لاعب</small></div><div><b>${state.session?.rounds||0}</b><small>جولة</small></div><div><b>${mins}</b><small>دقيقة</small></div></div><div class="hostDeckGridV30"><button onclick="showNextBestV30()">🎯<b>اللعبة التالية</b></button><button onclick="showPartyPulseV30()">💓<b>Party Pulse</b></button><button onclick="showTeamBalancerV30()">⚖️<b>قسّم فرق</b></button><button onclick="spotlightPlayerV30()">🎯<b>اختار لاعب</b></button><button onclick="showIntermissionV30()">☕<b>استراحة</b></button><button onclick="surpriseRouletteV30()">🎲<b>مفاجأة</b></button></div><h3>🔊 Soundboard</h3><div class="soundboardV30"><button onclick="partySoundV30('correct')">✅ صح</button><button onclick="partySoundV30('wrong')">❌ غلط</button><button onclick="partySoundV30('whistle')">📣 صافرة</button><button onclick="partySoundV30('drum')">🥁 تشويق</button><button onclick="partySoundV30('win')">🏆 فوز</button></div><button class="ghost wide" onclick="showPartyAwardsV30()">🏅 جوائز السهرة</button>`)};
window.showPartyAwardsV30=function(){const scores=Object.entries(state.session?.scores||{}).sort((a,b)=>b[1]-a[1]),strikes=Object.entries(state.session?.strikes||{}).sort((a,b)=>b[1]-a[1]),games=Object.entries(state.session?.games||{}).filter(([,v])=>v>0).sort((a,b)=>b[1]-a[1]);const champ=scores[0]?.[0],chaos=strikes[0]?.[0],fav=games[0]?.[0],played=games.length;const awards=[champ&&['👑','ملك السهرة',champ,`${scores[0][1]} نقطة`],scores[1]&&['🥈','المنافس العنيد',scores[1][0],`${scores[1][1]} نقطة`],chaos&&['💣','صديق القنبلة',chaos,`${strikes[0][1]} ضربة`],fav&&['🎮','لعبة الليلة',game(fav)?.name||fav,`${games[0][1]} جولات`],['🧭','تنوع السهرة',`${played} ألعاب مختلفة`,played>=6?'سهرة متنوعة جدًا 🔥':'لسا في مجال نجرب أكثر']].filter(Boolean);openModal('awardsV30','🏅 جوائز السهرة',`<div class="awardsHeroV30"><span>🏆</span><h2>${champ?`مبروك ${esc(champ)}!`:'السهرة لسا شغالة'}</h2></div><div class="awardsGridV30">${awards.map(a=>`<div><span>${a[0]}</span><b>${esc(a[1])}</b><strong>${esc(a[2])}</strong><small>${esc(a[3])}</small></div>`).join('')}</div><div class="actions"><button class="primary" onclick="home();document.getElementById('awardsV30').classList.remove('open')">كمّل السهرة</button><button class="ghost" onclick="newNight()">سهرة جديدة</button></div>`)};
window.saveCurrentPlaylistV30=function(){if(!O.queue.length){toast('ما في مسار محفوظ حاليًا');return}const name=prompt('اسم الـPlaylist:',`سهرة ${new Date().toLocaleDateString('ar')}`);if(!name)return;O.playlists.unshift({id:Date.now(),name,queue:[...O.queue]});O.playlists=O.playlists.slice(0,12);save();toast('💾 تم حفظ الـPlaylist')};
window.showSavedPlaylistsV30=function(){openModal('playlistsV30','💾 Playlists السهرة',`${O.playlists.length?`<div class="savedListsV30">${O.playlists.map(p=>`<div><div><b>${esc(p.name)}</b><small>${p.queue.length} ألعاب</small></div><button onclick="loadPlaylistV30(${p.id})">تشغيل</button><button class="danger small" onclick="deletePlaylistV30(${p.id})">حذف</button></div>`).join('')}</div>`:'<p class="muted">احفظ أي مسار من Party Director حتى يظهر هنا.</p>'}<button class="gold wide" onclick="showPartyDirectorV30()">✨ ابنِ Playlist جديدة</button>`)};
window.loadPlaylistV30=function(id){const p=O.playlists.find(x=>x.id===id);if(!p)return;O.queue=[...p.queue];O.queueIndex=0;save();renderQueueBar();document.querySelectorAll('.modal.open').forEach(m=>m.classList.remove('open'));startPartyQueueV30()};window.deletePlaylistV30=function(id){O.playlists=O.playlists.filter(x=>x.id!==id);save();showSavedPlaylistsV30()};
function injectHome(){if(document.getElementById('partyOSV30'))return;const anchor=document.getElementById('v26Hub')||document.getElementById('seasonCardV27')||document.getElementById('presetStatus');if(!anchor)return;anchor.insertAdjacentHTML('afterend',`<section id="partyOSV30" class="partyOSV30"><div class="partyOSHead"><div><span class="partyOSBadge">PARTY OS</span><h2>🎉 شغّل السهرة… مش بس لعبة</h2><p>ابدأ فورًا أو خلّي Party Director يرتب الليلة حسب عددكم والجو.</p></div><button class="partyHostButtonV30" onclick="showHostDeckV30()">🎛️ Host</button></div><div class="partyOSActionsV30"><button class="instantV30" onclick="instantPartyV30()"><span>⚡</span><b>ابدأ فورًا</b><small>4 ألعاب مناسبة الآن</small></button><button onclick="showPartyDirectorV30()"><span>✨</span><b>رتّب السهرة</b><small>وقت + مود + طاقة</small></button><button onclick="surpriseRouletteV30()"><span>🎲</span><b>فاجئني</b><small>اختيار لعبة بالعجلة</small></button></div><div class="partyOSMiniV30"><button onclick="showNextBestV30()">🎯 شو نلعب هسا؟</button><button onclick="showSavedPlaylistsV30()">💾 Playlists</button><button onclick="showTeamBalancerV30()">⚖️ فرق عادلة</button><button onclick="showPartyPulseV30()">💓 Party Pulse</button></div></section>`)}
function firstRun(){if(localStorage.getItem('pn.partyos.welcome')||state.names.length||state.session?.rounds)return;localStorage.setItem('pn.partyos.welcome','1');setTimeout(()=>openModal('welcomeV30','🎉 أهلاً في ليلة التحدي',`<div class="welcomeV30"><div>🏆</div><h2>سهرتك كلها من مكان واحد.</h2><p>أضف أسماءكم، أو اضغط <b>ابدأ فورًا</b> وخلي اللعبة تختار لكم المسار.</p><div class="welcomeStepsV30"><span>1️⃣ حدّد عددكم</span><span>2️⃣ اختاروا الجو</span><span>3️⃣ العبوا — التطبيق يهتم بالباقي</span></div><button class="gold wide hugeBtn" onclick="document.getElementById('welcomeV30').classList.remove('open');showPartyDirectorV30()">جهّز أول سهرة</button></div>`),500)}
const oldHome=window.home;window.home=function(){oldHome?.();injectHome();renderQueueBar()};
setTimeout(()=>{injectHome();renderQueueBar();firstRun()},120);
})();