(()=>{
'use strict';
if(!document.getElementById('proV27Style')){const l=document.createElement('link');l.id='proV27Style';l.rel='stylesheet';l.href='pro-v27.css?v=20260912-pro1';document.head.appendChild(l)}
const K='pn.pro.v27';
const P=window.PN_PRO=(()=>{try{return {profiles:{},nights:[],achievements:[],totalRounds:0,games:{},seasonXP:0,claimed:{},customPacks:[],favorites:[],lastScreen:'home',...JSON.parse(localStorage.getItem(K)||'{}')}}catch{return {profiles:{},nights:[],achievements:[],totalRounds:0,games:{},seasonXP:0,claimed:{},customPacks:[],favorites:[],lastScreen:'home'}}})();
const save=()=>localStorage.setItem(K,JSON.stringify(P));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const EMOJIS=['🦁','🐯','🐆','🦊','🐺','🐻','🐼','🦅','🐲','🦈','⚡','🔥','🌙','⭐','👑','🎯','🎮','⚽','🚀','🧠','🎩','🛡️'];
const COLORS=['#2f6cff','#a80c35','#f0c45c','#7948d8','#1fa47d','#db6b2c','#3c8ed8','#c83375'];
const profile=n=>{if(!P.profiles[n])P.profiles[n]={xp:0,score:0,wins:0,avatar:EMOJIS[Math.abs([...n].reduce((a,c)=>a+c.charCodeAt(0),0))%EMOJIS.length],color:COLORS[Math.abs(n.length*7)%COLORS.length],title:'لاعب السهرة',badges:[]};return P.profiles[n]};
const level=xp=>Math.max(1,Math.floor(Math.sqrt((xp||0)/40))+1);const levelStart=l=>(l-1)*(l-1)*40;const levelNext=l=>l*l*40;
const gameName=id=>GAME_DEFS.find(g=>g.id===id)?.name||id;const gameEmoji=id=>GAME_DEFS.find(g=>g.id===id)?.emoji||'🎮';
function modal(id,title){let m=document.getElementById(id);if(!m){m=document.createElement('div');m.id=id;m.className='modal';m.onclick=e=>{if(e.target===m)m.classList.remove('open')};m.innerHTML=`<div class="modalCard"><div class="nav"><div class="big">${title}</div><button class="ghost" onclick="document.getElementById('${id}').classList.remove('open')">إغلاق</button></div><div class="proModalBody"></div></div>`;document.body.appendChild(m)}return m}
function openModal(id,title,html){const m=modal(id,title);m.querySelector('.proModalBody').innerHTML=html;m.classList.add('open');return m}

// ---- Profiles, XP, badges ----
const BADGES=[
 ['first','🎉','أول سهرة','العب أول جولة',()=>P.totalRounds>=1],['ten','🔟','دخل الجو','10 جولات',()=>P.totalRounds>=10],['fifty','🔥','سهرة ثقيلة','50 جولة',()=>P.totalRounds>=50],['explorer','🧭','المستكشف','جرّب 8 ألعاب مختلفة',()=>Object.keys(P.games).filter(k=>P.games[k]>0).length>=8],['world','🌍','Party Master','جرّب 16 لعبة مختلفة',()=>Object.keys(P.games).filter(k=>P.games[k]>0).length>=16],['pro','🏆','محنك','العب 20 جولة تحدّي 30',()=>P.games.trivia>=20],['social','🎭','اجتماعي','العب 10 جولات جماعية',()=>['fake','majority','whisper','sync'].reduce((a,k)=>a+(P.games[k]||0),0)>=10],['marathon','🌙','ماراثون','100 جولة إجمالًا',()=>P.totalRounds>=100],['creator','🛠️','صانع محتوى','أنشئ باك مخصص',()=>P.customPacks.length>0]
];
function checkBadges(){BADGES.forEach(([id])=>{if(!P.achievements.includes(id)&&BADGES.find(x=>x[0]===id)[4]()){P.achievements.push(id);toast(`🏅 إنجاز جديد: ${BADGES.find(x=>x[0]===id)[2]}`);try{beep(980,.13)}catch{}}});save()}
function addXP(name,xp,score=0){if(!name)return;const p=profile(name);const before=level(p.xp);p.xp+=xp;p.score+=score;const after=level(p.xp);if(after>before)toast(`⬆️ ${name} وصل المستوى ${after}`);save()}
const baseAddScore=window.addScore;window.addScore=function(name,pts=1){baseAddScore?.(name,pts);addXP(name,Math.max(2,pts*6),pts)};
const baseRecord=window.record;window.record=function(game,detail={}){baseRecord?.(game,detail);P.totalRounds++;P.games[game]=(P.games[game]||0)+1;state.names.forEach(n=>addXP(n,2,0));checkBadges();updateSeasonCard();save()};
window.showProfilesV27=function(){state.names.forEach(profile);const cards=state.names.map(n=>{const p=profile(n),l=level(p.xp),lo=levelStart(l),hi=levelNext(l),pc=Math.min(100,Math.round((p.xp-lo)/(hi-lo)*100));return `<div class="profileCard" style="box-shadow:inset 4px 0 0 ${p.color}"><button class="avatar" onclick="editProfileV27('${esc(n)}')">${p.avatar}</button><h4>${esc(n)}</h4><span class="titlePill">${esc(p.title)}</span><div class="xpBar"><i style="width:${pc}%"></i></div><div class="profileMeta"><span>Lv.${l}</span><span>${p.xp} XP</span><span>${p.score} نقطة</span></div></div>`}).join('')||'<p class="muted">أضف أسماء اللاعبين أولًا.</p>';const badges=BADGES.map(([id,em,n,d])=>`<div class="badgeCard ${P.achievements.includes(id)?'':'locked'}"><span>${em}</span><div><b>${n}</b><small>${d}</small></div></div>`).join('');openModal('profilesV27','👤 ملفات اللاعبين',`<div class="profileGrid">${cards}</div><h3>🏅 الإنجازات</h3><div class="badgeGrid">${badges}</div>`)};
window.editProfileV27=function(name){const p=profile(name);openModal('profileEditV27',`✨ ${esc(name)}`,`<div class="center"><div style="font-size:58px">${p.avatar}</div><h3>اختار الشخصية</h3><div class="chips">${EMOJIS.map(e=>`<button class="chip" onclick="setProfileAvatarV27('${esc(name)}','${e}')">${e}</button>`).join('')}</div><h3>اللقب</h3><div class="chips">${['لاعب السهرة','المحنك','ملك الضحك','الكابتن','Culé','ملك التخمين'].map(t=>`<button class="chip" onclick="setProfileTitleV27('${esc(name)}','${t}')">${t}</button>`).join('')}</div></div>`)};
window.setProfileAvatarV27=(n,a)=>{profile(n).avatar=a;save();document.getElementById('profileEditV27')?.classList.remove('open');showProfilesV27()};window.setProfileTitleV27=(n,t)=>{profile(n).title=t;save();document.getElementById('profileEditV27')?.classList.remove('open');showProfilesV27()};

// ---- Season / daily and weekly challenges ----
const season={id:'champions-26',name:'ليالي الأبطال',emoji:'🏆',desc:'موسم المعرفة والتحديات — اجمع XP وافتح ألقابًا.'};
const today=()=>new Date().toISOString().slice(0,10);function weekKey(){const d=new Date(),jan=new Date(d.getFullYear(),0,1);return `${d.getFullYear()}-W${Math.ceil((((d-jan)/86400000)+jan.getDay()+1)/7)}`}
function dailyDef(){const seed=+today().replace(/-/g,'');const defs=[['🎮','العب 5 جولات',()=>Math.min(P.totalRounds%5,5),5],['🏆','العب تحدّي 30 مرتين',()=>Math.min(P.games.trivia||0,2),2],['🧭','جرّب 3 ألعاب مختلفة',()=>Math.min(Object.keys(state.session.games||{}).filter(k=>state.session.games[k]>0).length,3),3]];return defs[seed%defs.length]}
function weeklyDef(){return ['🌍','العب 7 ألعاب مختلفة هذا الأسبوع',()=>Math.min(Object.keys(P.games).filter(k=>P.games[k]>0).length,7),7]}
function taskHTML(kind,def){const [em,n,fn,max]=def,cur=fn(),done=cur>=max,key=`${kind}:${kind==='daily'?today():weekKey()}`,claimed=P.claimed[key];return `<div class="seasonTask ${done?'done':''}"><span>${em}</span><div><b>${n}</b><small>${Math.min(cur,max)}/${max}</small></div>${done&&!claimed?`<button onclick="claimSeasonV27('${kind}')">استلم +${kind==='daily'?40:120}</button>`:claimed?'✅':''}</div>`}
window.claimSeasonV27=function(kind){const key=`${kind}:${kind==='daily'?today():weekKey()}`;if(P.claimed[key])return;const def=kind==='daily'?dailyDef():weeklyDef();if(def[2]()<def[3])return;P.claimed[key]=1;P.seasonXP+=(kind==='daily'?40:120);save();updateSeasonCard();toast('✨ تم استلام XP الموسم')};
function updateSeasonCard(){let e=document.getElementById('seasonCardV27');if(!e){e=document.createElement('div');e.id='seasonCardV27';e.className='seasonCard';const anchor=document.getElementById('presetStatus');anchor?.after(e)}if(!e)return;e.innerHTML=`<div class="seasonTop"><div><div class="eyebrow">SEASON</div><h3>${season.emoji} ${season.name}</h3><small>${season.desc}</small></div><div class="seasonXP">${P.seasonXP} XP</div></div><div class="seasonTasks">${taskHTML('daily',dailyDef())}${taskHTML('weekly',weeklyDef())}</div>`}
window.PNSeason={onGameEnd:(id,data)=>{if(data?.winner&&P.profiles[data.winner])profile(data.winner).wins=(profile(data.winner).wins||0)+1;save();updateSeasonCard()}};

// ---- Custom trivia pack creator ----
function hydrateCustomPacks(){P.customPacks.forEach(pk=>{if(!PARTY_CONTENT.triviaPacks.some(x=>x.id===pk.id))PARTY_CONTENT.triviaPacks.push({id:pk.id,name:pk.name,emoji:pk.emoji||'🧰',desc:'باك مخصص'});pk.cards.forEach((c,i)=>{const id=`${pk.id}-${i}`;if(!PARTY_CONTENT.trivia.some(x=>x.id===id))PARTY_CONTENT.trivia.push({id,pack:pk.id,difficulty:c.d||'medium',type:'direct',q:c.q,a:c.a,quality:'custom',status:'user'})})});try{initTriviaSetup?.()}catch{}}
window.showCustomPacksV27=function(){const list=P.customPacks.map(pk=>`<div class="customPackCard"><div><div><b>${pk.emoji||'🧰'} ${esc(pk.name)}</b><small>${pk.cards.length} سؤال</small></div><div><button class="ghost small" onclick="shareCustomPackV27('${pk.id}')">مشاركة</button><button class="danger small" onclick="deleteCustomPackV27('${pk.id}')">حذف</button></div></div></div>`).join('')||'<p class="muted">لسا ما عملت باكات خاصة.</p>';openModal('customPacksV27','🛠️ صانع الباكات',`${list}<button class="gold wide" onclick="editCustomPackV27()">＋ باك جديد</button><button class="ghost wide" onclick="importCustomPackV27()">📥 استيراد كود/رابط باك</button>`)};
window.editCustomPackV27=function(){openModal('packEditorV27','✍️ باك جديد',`<div class="packEditor"><input id="cpName" placeholder="اسم الباك"><input id="cpEmoji" placeholder="إيموجي مثل ⚽"><div class="packSyntax">كل سطر: السؤال | الجواب | medium<br>المستويات: easy / medium / hard / expert</div><textarea id="cpCards" placeholder="من سجل هدف برشلونة... | إنييستا | hard\nما عاصمة... | ... | medium"></textarea><button class="primary wide" onclick="saveCustomPackV27()">حفظ الباك</button></div>`)};
window.saveCustomPackV27=function(){const name=document.getElementById('cpName').value.trim(),emoji=document.getElementById('cpEmoji').value.trim()||'🧰',lines=document.getElementById('cpCards').value.split('\n').map(x=>x.trim()).filter(Boolean);if(!name||!lines.length){toast('اكتب اسم وأسئلة');return}const cards=lines.map(l=>{const [q,a,d='medium']=l.split('|').map(x=>x.trim());return {q,a,d:['easy','medium','hard','expert'].includes(d)?d:'medium'}}).filter(x=>x.q&&x.a);const id=`custom-${Date.now().toString(36)}`;P.customPacks.push({id,name,emoji,cards});save();hydrateCustomPacks();checkBadges();document.getElementById('packEditorV27')?.classList.remove('open');showCustomPacksV27();toast(`✅ تم إنشاء ${name}`)};
window.deleteCustomPackV27=function(id){if(!confirm('تحذف الباك المخصص؟'))return;P.customPacks=P.customPacks.filter(x=>x.id!==id);save();location.reload()};
function encodeObj(o){return btoa(unescape(encodeURIComponent(JSON.stringify(o)))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}function decodeObj(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return JSON.parse(decodeURIComponent(escape(atob(s))))}
window.shareCustomPackV27=async function(id){const pk=P.customPacks.find(x=>x.id===id);if(!pk)return;const url=`${location.origin}${location.pathname}?pack=${encodeObj(pk)}`;try{if(navigator.share)await navigator.share({title:`باك ${pk.name}`,text:'باك مخصص للعبة ليلة التحدي',url});else{await navigator.clipboard.writeText(url);toast('تم نسخ رابط الباك')}}catch{}}
window.importCustomPackV27=function(){const code=prompt('الصق رابط الباك أو الكود:');if(!code)return;try{const token=code.includes('pack=')?new URL(code).searchParams.get('pack'):code;const pk=decodeObj(token);pk.id=`custom-${Date.now().toString(36)}`;P.customPacks.push(pk);save();hydrateCustomPacks();toast(`📥 تم استيراد ${pk.name}`);showCustomPacksV27()}catch{toast('الكود غير صالح')}};
try{const p=new URLSearchParams(location.search).get('pack');if(p){const incoming=decodeObj(p);if(incoming?.cards&&!P.customPacks.some(x=>x.name===incoming.name&&x.cards.length===incoming.cards.length)){incoming.id=`custom-${Date.now().toString(36)}`;P.customPacks.push(incoming);save()}}}catch{}

// ---- Smart Party Director ----
const CAT={trivia:'knowledge',player:'football',fake:'social',sync:'social',scale:'mind',taboo:'teams',draw:'creative',bowl:'teams',bomb:'quick',five:'quick',majority:'social',order:'mind',emoji:'quick',estimate:'mind',memory:'mind',whisper:'social',court:'social',pitch:'creative',forbidden:'meta',mission:'meta',chain:'quick'};
function gamesForVibe(v){const sets={balanced:null,football:['trivia','player','five','emoji','order','estimate','chain'],laugh:['fake','draw','whisper','court','pitch','bomb','forbidden','mission'],mind:['trivia','order','estimate','memory','scale','sync'],quick:['five','bomb','emoji','chain','player'],family:['trivia','sync','scale','draw','memory','estimate','majority']};return sets[v]?GAME_DEFS.filter(g=>sets[v].includes(g.id)):GAME_DEFS}
function makePlaylist(minutes,vibe){let pool=gamesForVibe(vibe).filter(g=>state.names.length>=parseInt(g.players));if(!pool.length)pool=GAME_DEFS;const target=Math.max(3,Math.min(9,Math.round(minutes/15)));let out=[],last='';for(let i=0;i<target;i++){let choices=pool.filter(g=>!out.includes(g.id)&&CAT[g.id]!==last);if(!choices.length)choices=pool.filter(g=>CAT[g.id]!==last);if(!choices.length)choices=pool;const g=choices[Math.floor(Math.random()*choices.length)];out.push(g.id);last=CAT[g.id]}return out}
window.showSmartDirectorV27=function(){const d=state.session.director;openModal('directorV27','✨ المخرج الذكي',d?.games?renderDirector(d):`<div class="directorHero"><div class="bigIcon">🎬</div><h2>ابني سهرة كاملة تلقائيًا</h2><p class="muted">اللعبة توازن بين الضحك، التفكير، السرعة والتنافس بدون تكرار نفس الجو مرتين وراء بعض.</p></div><div class="directorGrid"><label>المدة<select id="dirTime"><option value="30">30 دقيقة</option><option value="60" selected>60 دقيقة</option><option value="90">90 دقيقة</option><option value="120">120 دقيقة</option></select></label><label>المود<select id="dirVibe"><option value="balanced">متوازن</option><option value="football">كروي</option><option value="laugh">ضحك</option><option value="mind">ذكاء</option><option value="quick">سريع</option><option value="family">عائلي</option></select></label></div><button class="gold wide" onclick="buildDirectorV27()">🎬 ابنِ السهرة</button>`)};
function renderDirector(d){return `<div class="directorPlaylist">${d.games.map((id,i)=>{const g=GAME_DEFS.find(x=>x.id===id);return `<div class="directorStep ${i===d.index?'current':''}"><span>${g?.emoji||'🎮'}</span><div><b>${g?.name||id}</b><small>${i<d.index?'تمت':i===d.index?'اللعبة الحالية':'قادمة'}</small></div>${i===d.index?'<b>▶</b>':''}</div>`}).join('')}</div><div class="actions wrap"><button class="primary" onclick="launchDirectorGameV27()">ابدأ الحالية</button><button class="gold" onclick="directorNextV27()">تمت — التالي</button><button class="danger" onclick="endDirectorV27()">إنهاء</button></div>`}
window.buildDirectorV27=function(){state.session.director={games:makePlaylist(+document.getElementById('dirTime').value,document.getElementById('dirVibe').value),index:0,startedAt:Date.now()};persist();showSmartDirectorV27()};window.launchDirectorGameV27=function(){const d=state.session.director;if(!d)return;document.getElementById('directorV27')?.classList.remove('open');showScreen(d.games[d.index])};window.directorNextV27=function(){const d=state.session.director;if(!d)return;d.index=Math.min(d.games.length-1,d.index+1);persist();showSmartDirectorV27()};window.endDirectorV27=function(){state.session.director=null;persist();document.getElementById('directorV27')?.classList.remove('open');toast('🎬 انتهت السهرة الذكية')};

// ---- Party codes: share setup, not live sync ----
window.sharePartyCodeV27=async function(){const payload={preset:state.settings.preset||'custom',settings:{contentMode:state.settings.contentMode||'all',timerMultiplier:state.settings.timerMultiplier||1},director:state.session.director?.games||null};const code=encodeObj(payload),url=`${location.origin}${location.pathname}?party=${code}`;try{if(navigator.share)await navigator.share({title:'ليلة التحدي',text:'افتح نفس إعدادات السهرة',url});else{await navigator.clipboard.writeText(url);toast('🔗 تم نسخ رابط السهرة')}}catch{}}
function importPartyFromURL(){try{const p=new URLSearchParams(location.search).get('party');if(!p)return;const x=decodeObj(p);if(x.settings)Object.assign(state.settings,x.settings);if(x.director)state.session.director={games:x.director,index:0,startedAt:Date.now()};if(x.preset&&typeof applyPreset==='function')setTimeout(()=>applyPreset(x.preset),200);persist();toast('🔗 تم تحميل إعدادات السهرة')}catch{}}

// ---- Stats, hall of fame, recap ----
function snapshotNight(){if(!state.session?.rounds)return;const scores=Object.entries(state.session.scores||{}).sort((a,b)=>b[1]-a[1]);P.nights.unshift({id:state.session.id,at:Date.now(),rounds:state.session.rounds,games:state.session.games,scores,winner:scores[0]?.[0]||null,duration:Date.now()-state.session.startedAt,events:(state.session.events||[]).slice(-80)});P.nights=P.nights.slice(0,30);if(scores[0])profile(scores[0][0]).wins=(profile(scores[0][0]).wins||0)+1;save()}
window.PartyProBeforeNewNight=snapshotNight;
window.showStatsHubV27=function(){const totalGames=Object.entries(P.games).sort((a,b)=>b[1]-a[1]),max=Math.max(1,...totalGames.map(x=>x[1]));const players=Object.entries(P.profiles).sort((a,b)=>b[1].score-a[1].score);const bars=totalGames.slice(0,8).map(([id,n])=>`<div class="statsBar"><span>${gameEmoji(id)} ${gameName(id)}</span><i style="--p:${Math.round(n/max*100)}%"></i><b>${n}</b></div>`).join('')||'<p class="muted">لسا ما في بيانات كافية.</p>';const podium=players.slice(0,3).map(([n,p])=>`<div><div class="avatar">${p.avatar}</div><b>${esc(n)}</b><small>${p.score} نقطة • ${p.wins||0} فوز</small></div>`).join('');openModal('statsV27','📊 Stats Hub',`<div class="statGrid"><div class="statBox"><b>${P.totalRounds}</b>جولة</div><div class="statBox"><b>${Object.keys(P.games).length}</b>لعبة مجرّبة</div><div class="statBox"><b>${P.nights.length}</b>سهرة محفوظة</div></div><h3>👑 Hall of Fame</h3><div class="hofPodium">${podium||'<div>—</div>'}</div><h3>🎮 الأكثر لعبًا</h3><div class="statsBars">${bars}</div><div class="actions wrap"><button class="gold" onclick="showRecapV27()">🎞️ Recap</button><button class="ghost" onclick="showProfilesV27()">👤 اللاعبين</button></div>`)};
window.showRecapV27=function(){const ev=(state.session.events||[]).slice().reverse().slice(0,40);const rows=ev.map(x=>`<div class="recapEvent"><span>${gameEmoji(x.game)}</span><div><b>${gameName(x.game)}</b><small>${x.type||x.pack||'جولة'}</small></div><time>${new Date(x.t).toLocaleTimeString('ar',{hour:'2-digit',minute:'2-digit'})}</time></div>`).join('')||'<p class="muted">ابدأوا اللعب عشان يتكوّن Recap.</p>';openModal('recapV27','🎞️ Recap السهرة',`<div class="recapTimeline">${rows}</div>`)};
const baseSession=window.showSession;window.showSession=function(){baseSession?.();setTimeout(()=>{const b=document.getElementById('sessionBody');if(b&&!document.getElementById('sessionProButtons'))b.insertAdjacentHTML('beforeend',`<div id="sessionProButtons" class="actions wrap"><button class="gold" onclick="showStatsHubV27()">📊 Stats Hub</button><button class="ghost" onclick="showRecapV27()">🎞️ Recap</button><button class="ghost" onclick="sharePartyCodeV27()">🔗 مشاركة الإعداد</button></div>`)},0)};

// ---- Settings / content profiles / accessibility ----
window.applyAccessibilityV27=function(){document.documentElement.classList.toggle('pn-large-text',!!state.settings.largeText);document.documentElement.classList.toggle('pn-reduce-motion',!!state.settings.reduceMotion);document.documentElement.classList.toggle('pn-high-contrast',!!state.settings.highContrast);document.documentElement.classList.add('focusRing')};
function applyContentMode(){const m=state.settings.contentMode||'all';const football=new Set(['football-general','ucl','world-cup','barca','madrid','premier','football-expert','barca-pep','barca-history','barca-expert','football-2000s']);document.querySelectorAll('#triviaPacks .packBtn').forEach(b=>{let visible=true;if(m==='football')visible=football.has(b.dataset.pack);if(m==='noReligion'&&b.dataset.pack==='religion')visible=false;if(m==='family'&&['football-expert','barca-expert'].includes(b.dataset.pack))visible=false;b.style.display=visible?'':'none';if(!visible)b.classList.remove('selected')})}
window.setProSettingV27=function(k,v){state.settings[k]=v;persist();applyAccessibilityV27();applyContentMode()};
const baseSettings=window.showSettings;window.showSettings=function(){baseSettings?.();setTimeout(()=>{const b=document.getElementById('settingsBody');if(!b)return;b.insertAdjacentHTML('beforeend',`<h3>✨ تجربة اللعب</h3><div class="helpSteps"><label class="helpStep"><span>🔠 نص أكبر</span><input type="checkbox" ${state.settings.largeText?'checked':''} onchange="setProSettingV27('largeText',this.checked)"></label><label class="helpStep"><span>🧘 تقليل الحركة</span><input type="checkbox" ${state.settings.reduceMotion?'checked':''} onchange="setProSettingV27('reduceMotion',this.checked)"></label><label class="helpStep"><span>◐ تباين أعلى</span><input type="checkbox" ${state.settings.highContrast?'checked':''} onchange="setProSettingV27('highContrast',this.checked)"></label><label class="helpStep"><span>⏱ تمديد المؤقتات</span><select onchange="setProSettingV27('timerMultiplier',+this.value)"><option value="1" ${(state.settings.timerMultiplier||1)==1?'selected':''}>عادي</option><option value="1.5" ${state.settings.timerMultiplier==1.5?'selected':''}>×1.5</option><option value="2" ${state.settings.timerMultiplier==2?'selected':''}>×2</option></select></label><label class="helpStep"><span>🧩 فلتر المحتوى</span><select onchange="setProSettingV27('contentMode',this.value);applyContentMode()"><option value="all">الكل</option><option value="family" ${state.settings.contentMode==='family'?'selected':''}>عائلي</option><option value="football" ${state.settings.contentMode==='football'?'selected':''}>كرة فقط</option><option value="noReligion" ${state.settings.contentMode==='noReligion'?'selected':''}>بدون باك الدين</option></select></label></div><button class="ghost wide" onclick="openTVV27()">📺 فتح شاشة العرض / TV</button>`);},0)};

// ---- Game Master ----
function installMaster(){if(!document.getElementById('gameMasterFab')){const b=document.createElement('button');b.id='gameMasterFab';b.className='gameMasterFab';b.textContent='🎛️';b.onclick=showGameMasterV27;document.body.appendChild(b)}if(!document.getElementById('reactionFabV27')){const b=document.createElement('button');b.id='reactionFabV27';b.className='reactionFab';b.textContent='😄';b.onclick=toggleReactionsV27;document.body.appendChild(b);const t=document.createElement('div');t.id='reactionTrayV27';t.className='reactionTray';t.innerHTML=['😂','🔥','👏','🤯','😱','❤️'].map(e=>`<button onclick="sendReactionV27('${e}')">${e}</button>`).join('');document.body.appendChild(t)}}
window.showGameMasterV27=function(){const scores=state.names.map(n=>`<div class="masterScoreRow"><span>${profile(n).avatar} ${esc(n)} <b>${state.session.scores[n]||0}</b></span><button onclick="masterScoreV27('${esc(n)}',1)">＋</button><button onclick="masterScoreV27('${esc(n)}',-1)">−</button></div>`).join('');openModal('masterV27','🎛️ Game Master',`<div class="masterGrid"><button onclick="closeTimer();toast('⏸ تم إيقاف المؤقت')">⏸ إيقاف المؤقت</button><button onclick="toggleTriviaAnswer?.()">👁 كشف</button><button onclick="nextTrivia?.()">⏭ التالي</button><button onclick="replaceTriviaQuestionV24?.()">🔄 تبديل سؤال</button><button onclick="setProSettingV27('sound',!state.settings.sound)">🔊 صوت On/Off</button><button onclick="openTVV27()">📺 TV</button><button onclick="document.documentElement.requestFullscreen?.()">⛶ ملء الشاشة</button><button onclick="home();document.getElementById('masterV27').classList.remove('open')">⌂ الرئيسية</button></div><h3>نقاط فردية سريعة</h3>${scores||'<p class="muted">أضف لاعبين من الرئيسية.</p>'}<button class="masterGrid masterDanger wide" onclick="if(confirm('إنهاء اللعبة الحالية والرجوع للرئيسية؟'))home()">🛑 إنهاء اللعبة الحالية</button>`)};
window.masterScoreV27=function(n,p){state.session.scores[n]=(state.session.scores[n]||0)+p;if(state.session.scores[n]<0)state.session.scores[n]=0;addXP(n,Math.max(0,p*2),Math.max(0,p));persist();showGameMasterV27()};

// ---- Reactions + TV presentation ----
let bc=null;try{bc=new BroadcastChannel('party-night-tv-v27')}catch{}
function snapshot(){const s=document.querySelector('.screen.active'),id=s?.id||'home';return {screen:id,title:s?.querySelector('.gameHero h2')?.textContent||'ليلة التحدي',question:s?.querySelector('.question:not(.hidden), .metaPrompt:not(.hidden), .word:not(.hidden), .chainWord:not(.hidden)')?.textContent||'',answer:!document.getElementById('triviaA')?.classList.contains('hidden')?document.getElementById('triviaA')?.textContent:'',a:document.getElementById('taScore')?.textContent||'',b:document.getElementById('tbScore')?.textContent||'',an:document.getElementById('taName')?.textContent||'',bn:document.getElementById('tbName')?.textContent||'',at:Date.now()}}
function broadcast(){const x={type:'state',data:snapshot()};try{bc?.postMessage(x);localStorage.setItem('pn.tv.state',JSON.stringify(x.data))}catch{}}
window.openTVV27=function(){const w=window.open(`${location.pathname}?presentation=1`,'PartyNightTV');if(!w)toast('اسمح بفتح نافذة جديدة، وبعدها اعرضها على التلفزيون');else toast('📺 افتحت شاشة العرض — تقدر تعمل AirPlay/Screen Mirroring')};
window.toggleReactionsV27=()=>document.getElementById('reactionTrayV27')?.classList.toggle('open');window.sendReactionV27=function(e){const d=document.createElement('div');d.className='reactionBurst';d.textContent=e;document.body.appendChild(d);setTimeout(()=>d.remove(),1200);document.getElementById('reactionTrayV27')?.classList.remove('open');try{bc?.postMessage({type:'reaction',emoji:e})}catch{}};
function presentation(){document.body.innerHTML=`<div class="tvBody"><div class="tvShell"><div class="tvBrand"><b>ليلة التحدي</b><span>BY YAZAN ABDALHALEEM</span></div><div id="tvGame" class="tvGame">جاهزين؟</div><div id="tvQuestion" class="tvQuestion">ابدأ اللعبة من الهاتف المضيف</div><div id="tvAnswer" class="answer hidden"></div><div class="tvScore"><div><span id="tvAN">الفريق A</span><b id="tvA">0</b></div><div><span id="tvBN">الفريق B</span><b id="tvB">0</b></div></div></div></div>`;const render=x=>{document.getElementById('tvGame').textContent=x.title||'ليلة التحدي';document.getElementById('tvQuestion').textContent=x.question||'متابعة السهرة...';const a=document.getElementById('tvAnswer');a.textContent=x.answer||'';a.classList.toggle('hidden',!x.answer);document.getElementById('tvAN').textContent=x.an||'الفريق A';document.getElementById('tvBN').textContent=x.bn||'الفريق B';document.getElementById('tvA').textContent=x.a||'0';document.getElementById('tvB').textContent=x.b||'0'};try{const old=JSON.parse(localStorage.getItem('pn.tv.state')||'null');if(old)render(old)}catch{}try{bc.onmessage=e=>{if(e.data.type==='state')render(e.data.data);if(e.data.type==='reaction'){const d=document.createElement('div');d.className='tvReaction';d.textContent=e.data.emoji;document.body.appendChild(d);setTimeout(()=>d.remove(),1300)}}}catch{}window.addEventListener('storage',e=>{if(e.key==='pn.tv.state')try{render(JSON.parse(e.newValue))}catch{}})}
if(new URLSearchParams(location.search).get('presentation')==='1'){presentation();return}

// ---- Home command center / resume ----
function augmentHome(){installMaster();updateSeasonCard();let q=document.querySelector('#home .quickRow');if(q&&!document.getElementById('proCommandBarV27')){const c=document.createElement('div');c.id='proCommandBarV27';c.className='proCommandBar';c.innerHTML=`<button onclick="showSmartDirectorV27()"><span>🎬</span><b>المخرج الذكي</b></button><button onclick="showProfilesV27()"><span>👤</span><b>Profiles</b></button><button onclick="showCustomPacksV27()"><span>🛠️</span><b>صانع الباكات</b></button><button onclick="showStatsHubV27()"><span>📊</span><b>Stats Hub</b></button>`;q.after(c)}let r=document.getElementById('resumeStripV27');if(state.session.rounds>0&&!r){r=document.createElement('div');r.id='resumeStripV27';r.className='resumeStrip';r.innerHTML=`<span>▶️</span><div><b>السهرة شغالة</b><small>${state.session.rounds} جولات • آخر شاشة: ${gameName(P.lastScreen)}</small></div><button class="gold small" onclick="showScreen('${P.lastScreen&&P.lastScreen!=='home'?P.lastScreen:'trivia'}')">متابعة</button>`;document.querySelector('#home .hero')?.after(r)}if(!state.session.rounds)r?.remove();applyAccessibilityV27();applyContentMode()}
const baseShowScreen=window.showScreen;window.showScreen=function(id){P.lastScreen=id;save();baseShowScreen(id);const inGame=id!=='home';document.getElementById('gameMasterFab')?.classList.toggle('show',inGame);document.getElementById('reactionFabV27')?.classList.toggle('show',inGame);document.getElementById('reactionTrayV27')?.classList.remove('open');broadcast()};const baseHomeStats=window.renderHomeStats;window.renderHomeStats=function(){baseHomeStats?.();augmentHome()};
setInterval(broadcast,900);document.addEventListener('click',()=>setTimeout(broadcast,60));

// ---- Onboarding / What's new ----
function whatsNew(){if(localStorage.getItem('pn.v27.seen'))return;localStorage.setItem('pn.v27.seen','1');setTimeout(()=>openModal('whatsNewV27','🎁 هدية التطوير',`<div class="center"><div style="font-size:55px">🌍</div><h2>ليلة التحدي كبرت كثير</h2><p class="muted">Challenge 30 PRO، Profiles وXP، مواسم، Smart Director، Custom Packs، Game Master، TV Mode، Stats Hub، ألعاب جديدة ومفاجآت.</p><button class="gold wide" onclick="document.getElementById('whatsNewV27').classList.remove('open')">يلا نلعب 🔥</button></div>`),1000)}

hydrateCustomPacks();state.names.forEach(profile);save();importPartyFromURL();applyAccessibilityV27();augmentHome();checkBadges();whatsNew();
})();