(()=>{
'use strict';
const APP_ID='com.yazan-abdalhaleem.party-night.v27';
const R=window.PN_REMOTE={room:null,roomId:null,isHost:false,names:{},votes:{},buzz:[],connected:new Set(),actions:{},loading:false};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function modal(id,title){let m=document.getElementById(id);if(!m){m=document.createElement('div');m.id=id;m.className='modal';m.onclick=e=>{if(e.target===m)m.classList.remove('open')};m.innerHTML=`<div class="modalCard"><div class="nav"><div class="big">${title}</div><button class="ghost" onclick="document.getElementById('${id}').classList.remove('open')">إغلاق</button></div><div class="remoteBody"></div></div>`;document.body.appendChild(m)}return m}
const randomRoom=()=>Array.from({length:6},()=> 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[Math.floor(Math.random()*32)]).join('');
async function lib(){if(R.lib)return R.lib;if(R.loading)while(R.loading)await new Promise(r=>setTimeout(r,100));R.loading=true;try{R.lib=await import('https://esm.run/trystero@0.25.4');return R.lib}finally{R.loading=false}}
function snapshot(){const s=document.querySelector('.screen.active'),id=s?.id||'home';const safeQuestion=['trivia','five','order','emoji','estimate','chain'].includes(id)?(s?.querySelector('.question:not(.hidden),.v26Prompt,.chainWord')?.textContent||''):'';return {screen:id,title:s?.querySelector('.gameHero h2')?.textContent||'ليلة التحدي',question:safeQuestion,a:document.getElementById('taScore')?.textContent||'',b:document.getElementById('tbScore')?.textContent||'',an:document.getElementById('taName')?.textContent||'A',bn:document.getElementById('tbName')?.textContent||'B',round:document.getElementById('triviaRoundLabel')?.textContent||''}}
function setupActions(role,myName){const room=R.room;const name=room.makeAction('name'),control=room.makeAction('control'),stateA=room.makeAction('state');R.actions={name,control,state:stateA};
 if(role==='host'){
   name.onMessage=(value,{peerId})=>{R.names[peerId]=String(value||'لاعب');R.connected.add(peerId);renderHost();stateA.send(snapshot(),{target:peerId})};
   control.onMessage=(data,{peerId})=>{const n=R.names[peerId]||'لاعب';if(data?.kind==='buzz'){if(!R.buzz.includes(peerId)){R.buzz.push(peerId);toast(`⚡ ${n} ضغط الجرس!`);try{buzz([80,30,80])}catch{}}}if(data?.kind==='vote'){R.votes[peerId]=data.value;toast(`🗳️ وصل جواب من ${n}`)}if(data?.kind==='reaction'){try{sendReactionV27?.(data.value)}catch{}}renderHost()};
   room.onPeerJoin=peerId=>{R.connected.add(peerId);stateA.send(snapshot(),{target:peerId}).catch?.(()=>{});renderHost()};room.onPeerLeave=peerId=>{R.connected.delete(peerId);delete R.names[peerId];delete R.votes[peerId];R.buzz=R.buzz.filter(x=>x!==peerId);renderHost()};
 }else{
   stateA.onMessage=data=>renderControllerState(data);room.onPeerJoin=peerId=>name.send(myName,{target:peerId});setTimeout(()=>name.send(myName),500);
 }
}
async function host(roomId){if(!navigator.onLine){toast('Remote Room يحتاج إنترنت');return}const {joinRoom}=await lib();R.roomId=roomId;R.isHost=true;R.room=joinRoom({appId:APP_ID,password:roomId},roomId);setupActions('host','HOST');setInterval(()=>{if(R.isHost&&R.room)R.actions.state?.send(snapshot()).catch?.(()=>{})},900);renderHost()}
window.openRemoteRoomV27=function(){const m=modal('remoteHostV27','📱 Remote Room Beta');m.classList.add('open');if(!R.room){m.querySelector('.remoteBody').innerHTML=`<div class="center"><div style="font-size:54px">📡</div><h2>خلي تلفونات الشلة Controllers</h2><p class="muted">WebRTC peer‑to‑peer. يحتاج إنترنت لاكتشاف الأجهزة، وبعد الاتصال البيانات تنتقل مباشرة بين الأجهزة.</p><button class="gold wide" onclick="createRemoteRoomV27()">إنشاء غرفة</button></div>`}else renderHost()};
window.createRemoteRoomV27=async function(){const id=randomRoom();const body=document.querySelector('#remoteHostV27 .remoteBody');body.innerHTML='<div class="center"><div class="timer">…</div><p>جاري فتح الغرفة</p></div>';try{await host(id)}catch(e){console.error(e);body.innerHTML='<p class="muted">تعذر فتح الغرفة. تأكد من الإنترنت وجرب مرة ثانية.</p><button class="primary wide" onclick="createRemoteRoomV27()">إعادة المحاولة</button>'}};
function roomURL(){return `${location.origin}${location.pathname}?controller=1&room=${encodeURIComponent(R.roomId)}`}
function renderHost(){const m=modal('remoteHostV27','📱 Remote Room Beta'),b=m.querySelector('.remoteBody');if(!R.roomId)return;const url=roomURL(),people=[...R.connected].map(id=>({id,n:R.names[id]||'جهاز متصل'}));const tally={A:0,B:0,C:0,D:0,YES:0,NO:0};Object.values(R.votes).forEach(v=>{if(v in tally)tally[v]++});b.innerHTML=`<div class="center"><div class="tiny">ROOM CODE</div><div style="font-size:34px;font-weight:950;letter-spacing:6px;color:#f3cf70">${R.roomId}</div><p class="muted">الشلة تفتح الرابط أو تمسح QR، تكتب اسمها، وتصير Controller.</p><img style="width:190px;max-width:70%;border-radius:14px;background:white;padding:7px" alt="QR" src="https://api.qrserver.com/v1/create-qr-code/?size=220x220&data=${encodeURIComponent(url)}"><div class="actions wrap"><button class="primary" onclick="shareRemoteRoomV27()">📨 مشاركة الرابط</button><button class="ghost" onclick="copyRemoteRoomV27()">📋 نسخ</button><button class="ghost" onclick="clearRemoteRoundV27()">🧹 مسح الجولة</button></div></div><h3>👥 متصلون (${people.length})</h3><div class="leaderboard">${people.length?people.map(p=>`<div><span>📱 ${esc(p.n)}</span><b>${R.buzz[0]===p.id?'⚡ الأول':R.votes[p.id]||'متصل'}</b></div>`).join(''):'<div class="muted">بانتظار اللاعبين…</div>'}</div><h3>🗳️ إجابات الجولة</h3><div class="chips">${Object.entries(tally).map(([k,v])=>`<span class="pill">${k}: <b>${v}</b></span>`).join('')}</div>${R.buzz.length?`<div class="panel center"><b>⚡ ترتيب الجرس</b><ol>${R.buzz.map(id=>`<li>${esc(R.names[id]||'لاعب')}</li>`).join('')}</ol></div>`:''}`;m.classList.add('open')}
window.shareRemoteRoomV27=async function(){const url=roomURL();try{if(navigator.share)await navigator.share({title:'ليلة التحدي — Remote Room',text:`ادخل الغرفة ${R.roomId}`,url});else{await navigator.clipboard.writeText(url);toast('تم نسخ الرابط')}}catch{}};window.copyRemoteRoomV27=async()=>{try{await navigator.clipboard.writeText(roomURL());toast('📋 تم نسخ رابط الغرفة')}catch{}};window.clearRemoteRoundV27=function(){R.votes={};R.buzz=[];renderHost();try{R.actions.state?.send(snapshot())}catch{}};

function controllerShell(roomId){document.body.innerHTML=`<div class="tvBody"><div class="tvShell" style="max-width:620px"><div class="tvBrand"><b>ليلة التحدي</b><span>REMOTE CONTROLLER</span></div><div id="controllerJoin"><div class="panel center"><div style="font-size:52px">📱</div><h2>غرفة ${esc(roomId)}</h2><input id="remoteName" placeholder="اسمك" style="width:100%;padding:14px;border-radius:13px"><button class="gold wide" onclick="joinRemoteControllerV27()">دخول الغرفة</button><p class="tiny">الاتصال P2P ومخصص للسهرة الحالية.</p></div></div><div id="controllerLive" class="hidden"><div class="panel center"><div class="pill" id="remoteGameTitle">ليلة التحدي</div><div class="metaPrompt" id="remoteQuestion">بانتظار المضيف…</div><div class="tvScore"><div><span id="remoteAN">A</span><b id="remoteA">0</b></div><div><span id="remoteBN">B</span><b id="remoteB">0</b></div></div></div><button class="gold wide hugeBtn" onclick="remoteSendV27('buzz','BUZZ')">⚡ الجرس</button><div class="voteGrid" style="margin-top:9px"><button onclick="remoteSendV27('vote','A')">A</button><button onclick="remoteSendV27('vote','B')">B</button><button onclick="remoteSendV27('vote','C')">C</button><button onclick="remoteSendV27('vote','D')">D</button><button onclick="remoteSendV27('vote','YES')">✅ نعم</button><button onclick="remoteSendV27('vote','NO')">❌ لا</button></div><div class="reactionTray open" style="position:static;margin-top:12px;justify-content:center">${['😂','🔥','👏','🤯','😱','❤️'].map(e=>`<button onclick="remoteSendV27('reaction','${e}')">${e}</button>`).join('')}</div></div></div></div>`}
window.joinRemoteControllerV27=async function(){const n=document.getElementById('remoteName').value.trim();if(!n){alert('اكتب اسمك');return}if(!navigator.onLine){alert('Remote Room يحتاج إنترنت');return}try{const {joinRoom}=await lib();R.roomId=new URLSearchParams(location.search).get('room');R.room=joinRoom({appId:APP_ID,password:R.roomId},R.roomId);R.isHost=false;R.myName=n;setupActions('controller',n);document.getElementById('controllerJoin').classList.add('hidden');document.getElementById('controllerLive').classList.remove('hidden')}catch(e){console.error(e);alert('تعذر الاتصال بالغرفة')}};
window.remoteSendV27=function(kind,value){if(!R.actions.control)return;R.actions.control.send({kind,value,name:R.myName}).catch?.(()=>{});const b=document.createElement('div');b.className='reactionBurst';b.textContent=kind==='buzz'?'⚡':kind==='reaction'?value:'✅';document.body.appendChild(b);setTimeout(()=>b.remove(),900)};
function renderControllerState(x){const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v||''};set('remoteGameTitle',x.title);set('remoteQuestion',x.question||'تابعوا الشاشة الرئيسية للمحتوى السري');set('remoteA',x.a||'0');set('remoteB',x.b||'0');set('remoteAN',x.an||'A');set('remoteBN',x.bn||'B')}

// Add entry points to Game Master and Settings.
const oldMaster=window.showGameMasterV27;window.showGameMasterV27=function(){oldMaster?.();setTimeout(()=>{const b=document.querySelector('#masterV27 .proModalBody');if(b&&!document.getElementById('remoteMasterBtn'))b.insertAdjacentHTML('afterbegin','<button id="remoteMasterBtn" class="primary wide" onclick="openRemoteRoomV27()">📱 Remote Room / أجهزة اللاعبين</button>')},0)};
const oldSettings=window.showSettings;window.showSettings=function(){oldSettings?.();setTimeout(()=>{const b=document.getElementById('settingsBody');if(b&&!document.getElementById('remoteSettingsBtn'))b.insertAdjacentHTML('beforeend','<button id="remoteSettingsBtn" class="primary wide" onclick="openRemoteRoomV27()">📡 Remote Room Beta</button>')},0)};

const params=new URLSearchParams(location.search);if(params.get('controller')==='1'&&params.get('room')){controllerShell(params.get('room'));return}
})();